/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {ListItemNode} from './LexicalListItemNode';
import type {ListNode} from './LexicalListNode';

import {aliasTableOf, type GeneratedJSONFactory} from 'lexical';

// The JSON number grammar, anchored, matching numberValue: `Number()` alone
// reads '0x10' as 16 and '' as 0, and neither is a shape a JSON encoder
// produces. Emitted from the same source the codegen verified against, so the
// two cannot be different functions.
const JSON_NUMBER = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/;

function num(v: unknown, d: number): number {
  if (typeof v === 'number') {
    return Number.isFinite(v) ? v : d;
  }
  if (typeof v !== 'string' || !JSON_NUMBER.test(v)) {
    return d;
  }
  const n = Number(v);
  return Number.isFinite(n) ? n : d;
}

function numC(
  v: unknown,
  d: number,
  min: number,
  max: number,
  integer: boolean,
): number {
  const n = num(v, d);
  return n >= min && n <= max && (!integer || Number.isInteger(n)) ? n : d;
}

/** ListNode's generated implementations, for its `$config`. @internal */
export const GENERATED_LIST: GeneratedJSONFactory = fields => {
  const LIST_LISTTYPE_ALIAS = aliasTableOf(fields, 'listType', 0) as {
    readonly [key: string]: 'bullet' | 'number';
  };

  /** Generated from ListNode's serialization schema. Do not edit by hand. */
  function exportListNode(node: ListNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      listType: node.__listType,
      start: node.__start,
      tag: node.__tag,
      direction: node.__dir,
      format: node.getFormatType(),
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from ListNode's serialization schema. Do not edit by hand. */
  function exportCompactListNode(node: ListNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const listType = node.__listType;
    if (listType !== undefined && listType !== 'number') {
      json.listType = listType;
    }
    const start = node.__start;
    if (start !== undefined && start !== 1) {
      json.start = start;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from ListNode's serialization schema. Do not edit by hand. */
  function updateListNode(
    node: ListNode,
    json: {readonly [key: string]: unknown},
  ): ListNode {
    let self = node;
    let n: unknown;
    let v: unknown;
    v = Object.prototype.hasOwnProperty.call(json, 'direction')
      ? json.direction
      : undefined;
    self.__dir = v === null || v === 'ltr' || v === 'rtl' ? v : null;
    v = Object.prototype.hasOwnProperty.call(json, 'format')
      ? json.format
      : undefined;
    n = self.setFormat(
      v === '' ||
        v === 'left' ||
        v === 'start' ||
        v === 'center' ||
        v === 'right' ||
        v === 'end' ||
        v === 'justify'
        ? v
        : '',
    );
    self = (n ?? self) as ListNode;
    v = Object.prototype.hasOwnProperty.call(json, 'indent')
      ? json.indent
      : undefined;
    self.__indent = numC(v, 0, 0, Infinity, true);
    v = Object.prototype.hasOwnProperty.call(json, 'textFormat')
      ? json.textFormat
      : undefined;
    n = self.setTextFormat(num(v, 0));
    self = (n ?? self) as ListNode;
    v = Object.prototype.hasOwnProperty.call(json, 'textStyle')
      ? json.textStyle
      : undefined;
    n = self.setTextStyle(typeof v === 'string' ? v : '');
    self = (n ?? self) as ListNode;
    v = Object.prototype.hasOwnProperty.call(json, 'listType')
      ? json.listType
      : undefined;
    n = self.setListType(
      typeof v === 'string' && v in LIST_LISTTYPE_ALIAS
        ? LIST_LISTTYPE_ALIAS[v]
        : v === 'number' || v === 'bullet' || v === 'check'
          ? v
          : 'number',
    );
    self = (n ?? self) as ListNode;
    v = Object.prototype.hasOwnProperty.call(json, 'start')
      ? json.start
      : undefined;
    self.__start = num(v, 1);
    return self;
  }

  /** Generated from ListNode's serialization schema. Do not edit by hand. */
  function afterCloneListNode(node: ListNode, prevNode: ListNode): void {
    node.__listType = prevNode.__listType;
    node.__start = prevNode.__start;
    node.__tag = prevNode.__tag;
  }

  return {
    exportJSON: exportListNode,
    exportCompactJSON: exportCompactListNode,
    updateFromJSON: updateListNode,
    afterCloneFrom: afterCloneListNode,
  };
};

/** ListItemNode's generated implementations, for its `$config`. @internal */
export const GENERATED_LISTITEM: GeneratedJSONFactory = () => {
  /** Generated from ListItemNode's serialization schema. Do not edit by hand. */
  function exportListItemNode(node: ListItemNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      checked: node.getChecked(),
      indent: node.getIndent(),
      value: node.__value,
      direction: node.__dir,
      format: node.getFormatType(),
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from ListItemNode's serialization schema. Do not edit by hand. */
  function exportCompactListItemNode(node: ListItemNode): {
    [key: string]: unknown;
  } {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const checked = node.getChecked();
    if (checked !== undefined) {
      json.checked = checked;
    }
    const indent = node.getIndent();
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    const value = node.__value;
    if (value !== undefined && value !== 1) {
      json.value = value;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from ListItemNode's serialization schema. Do not edit by hand. */
  function afterCloneListItemNode(
    node: ListItemNode,
    prevNode: ListItemNode,
  ): void {
    node.__checked = prevNode.__checked;
    node.__value = prevNode.__value;
  }

  return {
    exportJSON: exportListItemNode,
    exportCompactJSON: exportCompactListItemNode,
    afterCloneFrom: afterCloneListItemNode,
  };
};
