/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var m=require("lexical"),t=require("@lexical/list"),z=require("@lexical/rich-text"),aa=require("@lexical/utils"),A=require("@lexical/code"),G=require("@lexical/link");function H(a,b){let c={};for(let d of a)a=b(d),c[a]?c[a].push(d):c[a]=[d];return c}function I(a){a=H(a,b=>b.type);return{element:a.element||[],textFormat:a["text-format"]||[],textMatch:a["text-match"]||[]}}let J=/[!-/:-@[-`{-~\s]/;
function ba(a){let b=I(a),c=b.textFormat.filter(d=>1===d.format.length);return d=>{let e=[];d=(d||m.$getRoot()).getChildren();for(let f of d)d=ca(f,b.element,c,b.textMatch),null!=d&&e.push(d);return e.join("\n\n")}}function ca(a,b,c,d){for(let e of b)if(b=e.export(a,f=>K(f,c,d)),null!=b)return b;return m.$isElementNode(a)?K(a,c,d):m.$isDecoratorNode(a)?a.getTextContent():null}
function K(a,b,c){let d=[];a=a.getChildren();a:for(let e of a){for(let f of c){let g=f.export(e,h=>K(h,b,c),(h,l)=>L(h,l,b));if(null!=g){d.push(g);continue a}}m.$isLineBreakNode(e)?d.push("\n"):m.$isTextNode(e)?d.push(L(e,e.getTextContent(),b)):m.$isElementNode(e)?(d.push(K(e,b,c)),a.indexOf(e)!==a.length-1&&d.push("\n")):m.$isDecoratorNode(e)&&d.push(e.getTextContent())}return d.join("")}
function L(a,b,c){let d=b.trim(),e=d,f=new Set;for(let h of c){c=h.format[0];let l=h.tag;if(M(a,c)&&!f.has(c)){f.add(c);var g=N(a,!0);M(g,c)||(e=l+e);g=N(a,!1);M(g,c)||(e+=l)}}return b.replace(d,e)}
function N(a,b){let c=b?a.getPreviousSibling():a.getNextSibling();c||(a=a.getParentOrThrow(),a.isInline()&&(c=b?a.getPreviousSibling():a.getNextSibling()));for(;c;){if(m.$isElementNode(c)){if(!c.isInline())break;a=b?c.getLastDescendant():c.getFirstDescendant();if(m.$isTextNode(a))return a;c=b?c.getPreviousSibling():c.getNextSibling()}if(m.$isTextNode(c))return c;if(!m.$isElementNode(c))break}return null}function M(a,b){return m.$isTextNode(a)&&a.hasFormat(b)}
let O="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,da=O&&"documentMode"in document?document.documentMode:null;O&&/Mac|iPod|iPhone|iPad/.test(navigator.platform);O&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent);O&&"InputEvent"in window&&!da?"getTargetRanges"in new window.InputEvent("input"):!1;
let P=O&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),Q=O&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,ea=O&&/^(?=.*Chrome).*/i.test(navigator.userAgent),R=O&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!ea,fa=/^\s{0,3}$/;
function S(a,b,c){let d=b.length;var e=c.textFormat;var f={};var g={},h=[];for(var l of e){({tag:e}=l);f[e]=l;var p=e.replace(/(\*|\^|\+)/g,"\\$1");h.push(p);g[e]=P||Q||R?new RegExp(`(${p})(?![${p}\\s])(.*?[^${p}\\s])${p}(?!${p})`):new RegExp(`(?<![\\\\${p}])(${p})((\\\\${p})?.*?[^${p}\\s](\\\\${p})?)((?<!\\\\)|(?<=\\\\\\\\))(${p})(?![\\\\${p}])`)}f={fullMatchRegExpByTag:g,openTagsRegExp:new RegExp((P||Q||R?"":"(?<![\\\\])")+"("+h.join("|")+")","g"),transformersByTag:f};for(g=0;g<d;){h=b[g];p=!1;
for(let k of c.element)if(l=h.match(k.regExp),k.getNumberOfLines&&(e=k.getNumberOfLines(b,g),!(g+e>b.length)&&l)){p=m.$createParagraphNode();a.append(p);S(p,b.slice(g+1,g+e),c);k.replace(a.getLastChild(),a.getLastChild().getChildren(),l,!0);g+=e;g<d&&(k.closeRegExp&&b[g].match(k.closeRegExp)||b[g].match(k.regExp))&&g++;p=!0;break}if(p)continue;var B=h,u=a,q=c.element;l=f;e=c.textMatch;p=B.trim();let r=m.$createTextNode(p);h=m.$createParagraphNode();h.append(r);u.append(h);for(let {regExp:k,replace:n}of q)if(u=
B.match(k)){B=B.slice(u[0].length);r.setTextContent(B);n(h,[r],u,!0);break}T(r,l,e);h.isAttached()&&0<p.length&&(l=h.getPreviousSibling(),m.$isParagraphNode(l)||z.$isQuoteNode(l)||t.$isListNode(l))&&(e=l,t.$isListNode(l)&&(l=l.getLastDescendant(),e=null==l?null:aa.$findMatchingParent(l,t.$isListItemNode)),null!=e&&0<e.getTextContentSize()&&(e.splice(e.getChildrenSize(),0,[m.$createLineBreakNode(),...h.getChildren()]),h.remove()));g++}}
function ha(a){let b=I(a);return(c,d)=>{c=c.split("\n");d=d||m.$getRoot();d.clear();S(d,c,b);c=d.getChildren();for(let e of c){a:{c=e;if(!m.$isParagraphNode(c)){c=!1;break a}let f=c.getFirstChild();c=null==f||1===c.getChildrenSize()&&m.$isTextNode(f)&&fa.test(f.getTextContent())}c&&e.remove()}null!==m.$getSelection()&&d.selectEnd()}}
function T(a,b,c){var d=a.getTextContent();let e=ia(d,b);if(e){var f,g;if(e[0]===d)var h=a;else{d=e.index||0;let l=d+e[0].length;0===d?[h,f]=a.splitText(l):[g,h,f]=a.splitText(d,l)}h.setTextContent(e[2]);if(a=b.transformersByTag[e[1]])for(let l of a.format)h.hasFormat(l)||h.toggleFormat(l);h.hasFormat("code")||T(h,b,c);g&&T(g,b,c);f&&T(f,b,c)}else U(a,c)}
function U(a,b){a:for(;a;){for(let c of b){let d=a.getTextContent().match(c.importRegExp);if(!d)continue;let e=d.index||0,f=e+d[0].length,g,h,l;0===e?[g,a]=a.splitText(f):[h,g,l]=a.splitText(e,f);h&&U(h,b);l&&(a=l);c.replace(g,d);continue a}break}}
function ia(a,b){var c=a.match(b.openTagsRegExp);if(null==c)return null;for(let f of c){var d=f.replace(/^\s/,"");c=b.fullMatchRegExpByTag[d];if(null!=c&&(c=a.match(c),d=b.transformersByTag[d],null!=c&&null!=d)){if(!1!==d.intraword)return c;var {index:e=0}=c;d=a[e-1];e=a[e+c[0].length];if(!(d&&!J.test(d)||e&&!J.test(e)))return c}}return null}function V(a,b,c){let d=c.length;for(;b>=d;b--){let e=b-d;if(ja(a,e,c,0,d)&&" "!==a[e+d])return e}return-1}
function ja(a,b,c,d,e){for(let f=0;f<e;f++)if(a[b+f]!==c[d+f])return!1;return!0}
let W=a=>(b,c,d)=>{d=a(d);d.append(...c);b.replace(d);d.select(0,0)},X=a=>(b,c,d)=>{var e=b.getPreviousSibling(),f=b.getNextSibling();const g=t.$createListItemNode("check"===a?"x"===d[3]:void 0);t.$isListNode(f)&&f.getListType()===a?(e=f.getFirstChild(),null!==e?e.insertBefore(g):f.append(g),b.remove()):t.$isListNode(e)&&e.getListType()===a?(e.append(g),b.remove()):(f=t.$createListNode(a,"number"===a?Number(d[2]):void 0),f.append(g),b.replace(f));g.append(...c);g.select(0,0);(b=Math.floor(d[1].length/
4))&&g.setIndent(b)},Y=(a,b,c)=>{const d=[];var e=a.getChildren();let f=0;for(const h of e)if(t.$isListItemNode(h)){if(1===h.getChildrenSize()&&(e=h.getFirstChild(),t.$isListNode(e))){d.push(Y(e,b,c+1));continue}e=" ".repeat(4*c);var g=a.getListType();g="number"===g?`${a.getStart()+f}. `:"check"===g?`- [${h.getChecked()?"x":" "}] `:"- ";d.push(e+g+b(h));f++}return d.join("\n")},ka={dependencies:[z.HeadingNode],export:(a,b)=>{if(!z.$isHeadingNode(a))return null;const c=Number(a.getTag().slice(1));
return"#".repeat(c)+" "+b(a)},regExp:/^(#{1,6})\s/,replace:W(a=>z.$createHeadingNode("h"+a[1].length)),type:"element"},la={dependencies:[z.QuoteNode],export:(a,b)=>{if(!z.$isQuoteNode(a))return null;a=b(a).split("\n");b=[];for(const c of a)b.push("> "+c);return b.join("\n")},regExp:/^>\s/,replace:(a,b,c,d)=>{if(d&&(c=a.getPreviousSibling(),z.$isQuoteNode(c))){c.splice(c.getChildrenSize(),0,[m.$createLineBreakNode(),...b]);c.select(0,0);a.remove();return}c=z.$createQuoteNode();c.append(...b);a.replace(c);
c.select(0,0)},type:"element"},ma={dependencies:[A.CodeNode],export:a=>{if(!A.$isCodeNode(a))return null;const b=a.getTextContent();return"```"+(a.getLanguage()||"")+(b?"\n"+b:"")+"\n```"},getNumberOfLines:(a,b)=>{const c=/^```(\w{1,10})?\s?$/;let d=b;const e=a.length;for(;++d<e&&!a[d].match(c););return d-b},regExp:/^```(\w{1,10})?\s?$/,replace:W(a=>A.$createCodeNode(a?a[1]:void 0)),type:"element"},na={dependencies:[t.ListNode,t.ListItemNode],export:(a,b)=>t.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)[-*+]\s/,
replace:X("bullet"),type:"element"},oa={dependencies:[t.ListNode,t.ListItemNode],export:(a,b)=>t.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(?:-\s)?\s?(\[(\s|x)?\])\s/i,replace:X("check"),type:"element"},pa={dependencies:[t.ListNode,t.ListItemNode],export:(a,b)=>t.$isListNode(a)?Y(a,b,0):null,regExp:/^(\s*)(\d{1,})\.\s/,replace:X("number"),type:"element"},qa={format:["code"],tag:"`",type:"text-format"},ra={format:["highlight"],tag:"==",type:"text-format"},sa={format:["bold","italic"],tag:"***",type:"text-format"},
ta={format:["bold","italic"],intraword:!1,tag:"___",type:"text-format"},va={format:["bold"],tag:"**",type:"text-format"},wa={format:["bold"],intraword:!1,tag:"__",type:"text-format"},xa={format:["strikethrough"],tag:"~~",type:"text-format"},ya={format:["italic"],tag:"*",type:"text-format"},za={format:["italic"],intraword:!1,tag:"_",type:"text-format"},Aa={dependencies:[G.LinkNode],export:(a,b,c)=>{if(!G.$isLinkNode(a))return null;b=(b=a.getTitle())?`[${a.getTextContent()}](${a.getURL()} "${b}")`:
`[${a.getTextContent()}](${a.getURL()})`;const d=a.getFirstChild();return 1===a.getChildrenSize()&&m.$isTextNode(d)?c(d,b):b},importRegExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))/,regExp:/(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,replace:(a,b)=>{const [,c,d,e]=b;b=G.$createLinkNode(d,{title:e});const f=m.$createTextNode(c);f.setFormat(a.getFormat());b.append(f);a.replace(b)},trigger:")",type:"text-match"},Ba=[ka,la,ma,na,pa],Ca=[qa,sa,ta,
va,wa,ra,ya,za,xa],Da=[Aa],Z=[...Ba,...Ca,...Da];exports.$convertFromMarkdownString=function(a,b=Z,c){return ha(b)(a,c)};exports.$convertToMarkdownString=function(a=Z,b){return ba(a)(b)};exports.BOLD_ITALIC_STAR=sa;exports.BOLD_ITALIC_UNDERSCORE=ta;exports.BOLD_STAR=va;exports.BOLD_UNDERSCORE=wa;exports.CHECK_LIST=oa;exports.CODE=ma;exports.ELEMENT_TRANSFORMERS=Ba;exports.HEADING=ka;exports.HIGHLIGHT=ra;exports.INLINE_CODE=qa;exports.ITALIC_STAR=ya;exports.ITALIC_UNDERSCORE=za;exports.LINK=Aa;
exports.ORDERED_LIST=pa;exports.QUOTE=la;exports.STRIKETHROUGH=xa;exports.TEXT_FORMAT_TRANSFORMERS=Ca;exports.TEXT_MATCH_TRANSFORMERS=Da;exports.TRANSFORMERS=Z;exports.UNORDERED_LIST=na;exports.createBlockNode=W;
exports.registerMarkdownShortcuts=function(a,b=Z){let c=I(b),d=H(c.textFormat,({tag:f})=>f[f.length-1]),e=H(c.textMatch,({trigger:f})=>f);for(let f of b)if(b=f.type,"element"===b||"text-match"===b){b=f.dependencies;for(let g of b)if(!a.hasNode(g))throw Error(`MarkdownShortcuts: missing dependency ${g.getType()} for transformer. Ensure node dependency is included in editor initial config.`);}return a.registerUpdateListener(({tags:f,dirtyLeaves:g,editorState:h,prevEditorState:l})=>{if(!f.has("historic")&&
!a.isComposing()){var p=h.read(m.$getSelection);f=l.read(m.$getSelection);if(m.$isRangeSelection(f)&&m.$isRangeSelection(p)&&p.isCollapsed()){l=p.anchor.key;var B=p.anchor.offset,u=h._nodeMap.get(l);!m.$isTextNode(u)||!g.has(l)||1!==B&&B>f.anchor.offset+1||a.update(()=>{if(!u.hasFormat("code")){var q=u.getParent();if(null!==q&&!A.$isCodeNode(q)){var r=p.anchor.offset;b:{var k=c.element,n=q.getParent();if(m.$isRootOrShadowRoot(n)&&q.getFirstChild()===u&&(n=u.getTextContent()," "===n[r-1]))for(let {regExp:D,
replace:E}of k)if((k=n.match(D))&&k[0].length===r){n=u.getNextSiblings();let [F,ua]=u.splitText(r);F.remove();n=ua?[ua,...n]:n;E(q,n,k,!1);q=!0;break b}q=!1}if(!q){b:{k=u.getTextContent();q=e[k[r-1]];if(null!=q){r<k.length&&(k=k.slice(0,r));for(w of q)if(q=k.match(w.regExp),null!==q){k=q.index||0;n=k+q[0].length;var x=void 0;0===k?[x]=u.splitText(n):[,x]=u.splitText(k,n);x.selectNext(0,0);w.replace(x,q);var w=!0;break b}}w=!1}if(!w)b:{n=u.getTextContent();--r;var v=n[r];if(w=d[v])for(let D of w){var {tag:C}=
D;w=C.length;let E=r-w+1;if(!(1<w&&!ja(n,E,C,0,w)||" "===n[E-1])&&(x=n[r+1],!1!==D.intraword||!x||J.test(x))){q=x=u;k=V(n,E,C);for(var y=q;0>k&&(y=y.getPreviousSibling())&&!m.$isLineBreakNode(y);)m.$isTextNode(y)&&(k=y.getTextContent(),q=y,k=V(k,k.length,C));if(!(0>k||q===x&&k+w===E||(C=q.getTextContent(),0<k&&C[k-1]===v||(y=C[k-1],!1===D.intraword&&y&&!J.test(y))))){n=x.getTextContent();n=n.slice(0,E)+n.slice(r+1);x.setTextContent(n);n=q===x?n:C;q.setTextContent(n.slice(0,k)+n.slice(k+w));n=m.$getSelection();
v=m.$createRangeSelection();m.$setSelection(v);r=r-w*(q===x?2:1)+1;v.anchor.set(q.__key,k,"text");v.focus.set(x.__key,r,"text");for(let F of D.format)v.hasFormat(F)||v.formatText(F);v.anchor.set(v.focus.key,v.focus.offset,v.focus.type);for(let F of D.format)v.hasFormat(F)&&v.toggleFormat(F);m.$isRangeSelection(n)&&(v.format=n.format);break b}}}}}}}})}}})}
