/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';let aa={},ba={},da={},ea={},fa={},ha={},ka={},ma={},na={},pa={},qa={},ra={},sa={},ta={},ua={},va={},xa={},ya={},za={},Aa={},Ba={},Ca={},Fa={},Ga={},Ha={},Ia={},Ja={},Ka={},La={},Ma={},Na={},Oa={},Pa={},Qa={},Ra={},Sa={};
function r(a){let b=new URLSearchParams;b.append("code",a);for(let c=1;c<arguments.length;c++)b.append("v",arguments[c]);throw Error(`Minified Lexical error #${a}; visit https://lexical.dev/docs/error?${b} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}
let Ta="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,Ua=Ta&&"documentMode"in document?document.documentMode:null,t=Ta&&/Mac|iPod|iPhone|iPad/.test(navigator.platform),Wa=Ta&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent),Xa=Ta&&"InputEvent"in window&&!Ua?"getTargetRanges"in new window.InputEvent("input"):!1,Ya=Ta&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),Za=Ta&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&
!window.MSStream,$a=Ta&&/^(?=.*Chrome).*/i.test(navigator.userAgent),ab=Ta&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!$a,bb=Ya||Za||ab?"\u00a0":"\u200b",cb=Wa?"\u00a0":bb,db=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]/,eb=/^[^\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,
fb={bold:1,code:16,highlight:128,italic:2,strikethrough:4,subscript:32,superscript:64,underline:8},gb={directionless:1,unmergeable:2},hb={center:2,end:6,justify:4,left:1,right:3,start:5},ib={2:"center",6:"end",4:"justify",1:"left",3:"right",5:"start"},jb={normal:0,segmented:2,token:1},kb={0:"normal",2:"segmented",1:"token"},ob=!1,pb=0;function qb(a){pb=a.timeStamp}function rb(a,b,c){return b.__lexicalLineBreak===a||void 0!==a[`__lexicalKey_${c._key}`]}
function sb(a){return a.getEditorState().read(()=>{let b=v();return null!==b?b.clone():null})}
function tb(a,b,c){ob=!0;let d=100<performance.now()-pb;try{w(a,()=>{let e=v()||sb(a);var f=new Map,g=a.getRootElement(),h=a._editorState,k=a._blockCursorElement;let m=!1,n="";for(var p=0;p<b.length;p++){var l=b[p],q=l.type,u=l.target,x=ub(u,h);if(!(null===x&&u!==g||z(x)))if("characterData"===q){if(l=d&&B(x))a:{l=e;q=u;var y=x;if(C(l)){var A=l.anchor.getNode();if(A.is(y)&&l.format!==A.getFormat()){l=!1;break a}}l=3===q.nodeType&&y.isAttached()}l&&(y=vb(a._window),q=l=null,null!==y&&y.anchorNode===
u&&(l=y.anchorOffset,q=y.focusOffset),u=u.nodeValue,null!==u&&wb(x,u,l,q,!1))}else if("childList"===q){m=!0;q=l.addedNodes;for(y=0;y<q.length;y++){A=q[y];var Z=xb(A),ca=A.parentNode;null==ca||A===k||null!==Z||"BR"===A.nodeName&&rb(A,ca,a)||(Wa&&(Z=A.innerText||A.nodeValue)&&(n+=Z),ca.removeChild(A))}l=l.removedNodes;q=l.length;if(0<q){y=0;for(A=0;A<q;A++)if(ca=l[A],"BR"===ca.nodeName&&rb(ca,u,a)||k===ca)u.appendChild(ca),y++;q!==y&&(u===g&&(x=h._nodeMap.get("root")),f.set(u,x))}}}if(0<f.size)for(let [Va,
la]of f)if(D(la))for(f=la.getChildrenKeys(),g=Va.firstChild,h=0;h<f.length;h++)k=a.getElementByKey(f[h]),null!==k&&(null==g?(Va.appendChild(k),g=k):g!==k&&Va.replaceChild(k,g),g=g.nextSibling);else B(la)&&la.markDirty();f=c.takeRecords();if(0<f.length){for(g=0;g<f.length;g++)for(k=f[g],h=k.addedNodes,k=k.target,p=0;p<h.length;p++)x=h[p],u=x.parentNode,null==u||"BR"!==x.nodeName||rb(x,k,a)||u.removeChild(x);c.takeRecords()}null!==e&&(m&&(e.dirty=!0,yb(e)),Wa&&zb(a)&&e.insertRawText(n))})}finally{ob=
!1}}function Ab(a){let b=a._observer;if(null!==b){let c=b.takeRecords();tb(a,c,b)}}function Bb(a){0===pb&&Cb(a).addEventListener("textInput",qb,!0);a._observer=new MutationObserver((b,c)=>{tb(a,b,c)})}function Db(a,b){let c=a.__mode,d=a.__format;a=a.__style;let e=b.__mode,f=b.__format;b=b.__style;return(null===c||c===e)&&(null===d||d===f)&&(null===a||a===b)}function Eb(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}
function Fb(a){if(""===a.__text&&a.isSimpleText()&&!a.isUnmergeable())a.remove();else{for(var b;null!==(b=a.getPreviousSibling())&&B(b)&&b.isSimpleText()&&!b.isUnmergeable();)if(""===b.__text)b.remove();else{Db(b,a)&&(a=Eb(b,a));break}for(var c;null!==(c=a.getNextSibling())&&B(c)&&c.isSimpleText()&&!c.isUnmergeable();)if(""===c.__text)c.remove();else{Db(a,c)&&Eb(a,c);break}}}function Gb(a){Hb(a.anchor);Hb(a.focus);return a}
function Hb(a){for(;"element"===a.type;){var b=a.getNode(),c=a.offset;c===b.getChildrenSize()?(b=b.getChildAtIndex(c-1),c=!0):(b=b.getChildAtIndex(c),c=!1);if(B(b)){a.set(b.__key,c?b.getTextContentSize():0,"text");break}else if(!D(b))break;a.set(b.__key,c?b.getChildrenSize():0,"element")}}let Ib=1,Jb="function"===typeof queueMicrotask?queueMicrotask:a=>{Promise.resolve().then(a)};
function Kb(a){let b=document.activeElement;if(null===b)return!1;let c=b.nodeName;return z(ub(a))&&("INPUT"===c||"TEXTAREA"===c||"true"===b.contentEditable&&null==b.__lexicalEditor)}function Lb(a,b,c){let d=a.getRootElement();try{return null!==d&&d.contains(b)&&d.contains(c)&&null!==b&&!Kb(b)&&Mb(b)===a}catch(e){return!1}}function Mb(a){for(;null!=a;){let b=a.__lexicalEditor;if(null!=b)return b;a=Nb(a)}return null}function Ob(a){return a.isToken()||a.isSegmented()}
function Vb(a){for(;null!=a;){if(3===a.nodeType)return a;a=a.firstChild}return null}function Wb(a,b,c){b=fb[b];return a&b&&(null===c||0===(c&b))?a^b:null===c||c&b?a|b:a}function Xb(a){return B(a)||Yb(a)||z(a)}function Zb(a,b){if(null!=b)a.__key=b;else{G();99<$b&&r(14);b=F();var c=ac(),d=""+Ib++;c._nodeMap.set(d,a);D(a)?b._dirtyElements.set(d,!0):b._dirtyLeaves.add(d);b._cloneNotNeeded.add(d);b._dirtyType=1;a.__key=d}}
function bc(a){var b=a.getParent();if(null!==b){let e=a.getWritable();b=b.getWritable();var c=a.getPreviousSibling();a=a.getNextSibling();if(null===c)if(null!==a){var d=a.getWritable();b.__first=a.__key;d.__prev=null}else b.__first=null;else{d=c.getWritable();if(null!==a){let f=a.getWritable();f.__prev=d.__key;d.__next=f.__key}else d.__next=null;e.__prev=null}null===a?null!==c?(a=c.getWritable(),b.__last=c.__key,a.__next=null):b.__last=null:(a=a.getWritable(),null!==c?(c=c.getWritable(),c.__next=
a.__key,a.__prev=c.__key):a.__prev=null,e.__next=null);b.__size--;e.__parent=null}}function cc(a){99<$b&&r(14);var b=a.getLatest(),c=b.__parent,d=ac();let e=F(),f=d._nodeMap;d=e._dirtyElements;if(null!==c)a:for(;null!==c;){if(d.has(c))break a;let g=f.get(c);if(void 0===g)break;d.set(c,!1);c=g.__parent}b=b.__key;e._dirtyType=1;D(a)?d.set(b,!0):e._dirtyLeaves.add(b)}
function H(a){G();var b=F();let c=b._compositionKey;a!==c&&(b._compositionKey=a,null!==c&&(b=I(c),null!==b&&b.getWritable()),null!==a&&(a=I(a),null!==a&&a.getWritable()))}function dc(){return ec()?null:F()._compositionKey}function I(a,b){a=(b||ac())._nodeMap.get(a);return void 0===a?null:a}function xb(a,b){let c=F();a=a[`__lexicalKey_${c._key}`];return void 0!==a?I(a,b):null}function ub(a,b){for(;null!=a;){let c=xb(a,b);if(null!==c)return c;a=Nb(a)}return null}
function fc(a){let b=Object.assign({},a._decorators);return a._pendingDecorators=b}function gc(a){return a.read(()=>hc().getTextContent())}function ic(a,b){w(a,()=>{var c=ac();if(!c.isEmpty())if("root"===b)hc().markDirty();else{c=c._nodeMap;for(let [,d]of c)d.markDirty()}},null===a._pendingEditorState?{tag:"history-merge"}:void 0)}function hc(){return ac()._nodeMap.get("root")}function yb(a){G();let b=ac();null!==a&&(a.dirty=!0,a._cachedNodes=null);b._selection=a}
function jc(a){var b=F(),c;a:{for(c=a;null!=c;){let d=c[`__lexicalKey_${b._key}`];if(void 0!==d){c=d;break a}c=Nb(c)}c=null}return null===c?(b=b.getRootElement(),a===b?I("root"):null):I(c)}function kc(a){return/[\uD800-\uDBFF][\uDC00-\uDFFF]/g.test(a)}function lc(a){let b=[];for(;null!==a;)b.push(a),a=a._parentEditor;return b}function mc(){return Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,5)}
function nc(a,b,c){b=vb(b._window);if(null!==b){var d=b.anchorNode,{anchorOffset:e,focusOffset:f}=b;if(null!==d&&(b=3===d.nodeType?d.nodeValue:null,d=ub(d),null!==b&&B(d))){if(b===bb&&c){let g=c.length;b=c;f=e=g}null!==b&&wb(d,b,e,f,a)}}}
function wb(a,b,c,d,e){let f=a;if(f.isAttached()&&(e||!f.isDirty())){let m=f.isComposing(),n=b;(m||e)&&b[b.length-1]===bb&&(n=b.slice(0,-1));b=f.getTextContent();if(e||n!==b)if(""===n)if(H(null),Ya||Za||ab)f.remove();else{let p=F();setTimeout(()=>{p.update(()=>{f.isAttached()&&f.remove()})},20)}else{e=f.getParent();b=oc();var g=f.getTextContentSize(),h=dc(),k=f.getKey();f.isToken()||null!==h&&k===h&&!m||C(b)&&(null!==e&&!e.canInsertTextBefore()&&0===b.anchor.offset||b.anchor.key===a.__key&&0===b.anchor.offset&&
!f.canInsertTextBefore()||b.focus.key===a.__key&&b.focus.offset===g&&!f.canInsertTextAfter())?f.markDirty():(a=v(),C(a)&&null!==c&&null!==d&&(a.setTextNodeRange(f,c,f,d),f.isSegmented()&&(c=f.getTextContent(),c=J(c),f.replace(c),f=c)),f.setTextContent(n))}}}
function pc(a,b){if(b.isSegmented())return!0;if(!a.isCollapsed())return!1;a=a.anchor.offset;let c=b.getParentOrThrow(),d=b.isToken();return 0===a?((a=!b.canInsertTextBefore()||!c.canInsertTextBefore()||d)||(b=b.getPreviousSibling(),a=(B(b)||D(b)&&b.isInline())&&!b.canInsertTextAfter()),a):a===b.getTextContentSize()?!b.canInsertTextAfter()||!c.canInsertTextAfter()||d:!1}
function qc(a,b){void 0===a.__lexicalClassNameCache&&(a.__lexicalClassNameCache={});let c=a.__lexicalClassNameCache,d=c[b];if(void 0!==d)return d;a=a[b];return"string"===typeof a?(a=a.split(" "),c[b]=a):a}function rc(a,b,c,d,e){0!==c.size&&(c=d.__type,d=d.__key,b=b.get(c),void 0===b&&r(33,c),c=b.klass,b=a.get(c),void 0===b&&(b=new Map,a.set(c,b)),a=b.get(d),c="destroyed"===a&&"created"===e,(void 0===a||c)&&b.set(d,c?"updated":e))}
function sc(a,b,c){let d=a.getParent(),e=c;null!==d&&(b&&0===c?(e=a.getIndexWithinParent(),a=d):b||c!==a.getChildrenSize()||(e=a.getIndexWithinParent()+1,a=d));return a.getChildAtIndex(b?e-1:e)}function tc(a,b){var c=a.offset;if("element"===a.type)return a=a.getNode(),sc(a,b,c);a=a.getNode();return b&&0===c||!b&&c===a.getTextContentSize()?(c=b?a.getPreviousSibling():a.getNextSibling(),null===c?sc(a.getParentOrThrow(),b,a.getIndexWithinParent()+(b?0:1)):c):null}
function zb(a){a=(a=Cb(a).event)&&a.inputType;return"insertFromPaste"===a||"insertFromPasteAsQuotation"===a}function uc(a){return!K(a)&&!a.isLastChild()&&!a.isInline()}function vc(a,b){a=a._keyToDOMMap.get(b);void 0===a&&r(75,b);return a}function Nb(a){a=a.assignedSlot||a.parentElement;return null!==a&&11===a.nodeType?a.host:a}function wc(a,b){for(a=a.getParent();null!==a;){if(a.is(b))return!0;a=a.getParent()}return!1}function Cb(a){a=a._window;null===a&&r(78);return a}
function xc(a){for(a=a.getParentOrThrow();null!==a&&!yc(a);)a=a.getParentOrThrow();return a}function yc(a){return K(a)||D(a)&&a.isShadowRoot()}function zc(a){a=a.constructor.clone(a);Zb(a,null);return a}function Ac(a){var b=F();let c=a.constructor.getType();b=b._nodes.get(c);void 0===b&&r(97);b=b.replace;return null!==b?(b=b(a),b instanceof a.constructor||r(98),b):a}function Bc(a,b){a=a.getParent();!K(a)||D(b)||z(b)||r(99)}function Cc(a){return(z(a)||D(a)&&!a.canBeEmpty())&&!a.isInline()}
function Dc(a,b,c){c.style.removeProperty("caret-color");b._blockCursorElement=null;b=a.parentElement;null!==b&&b.removeChild(a)}function vb(a){return Ta?(a||window).getSelection():null}function Ec(a,b){let c=a.getChildAtIndex(b);null==c&&(c=a);yc(a)&&r(102);let d=g=>{const h=g.getParentOrThrow(),k=yc(h),m=g!==c||k?zc(g):g;if(k)return g.insertAfter(m),[g,m,m];const [n,p,l]=d(h);g=g.getNextSiblings();l.append(m,...g);return[n,p,m]},[e,f]=d(c);return[e,f]}
function Fc(a,b){for(;a!==hc()&&null!=a;){if(b(a))return a;a=a.getParent()}return null}function Gc(a){let b=[],c=[a];for(;0<c.length;){let d=c.pop();void 0===d&&r(112);D(d)&&c.unshift(...d.getChildren());d!==a&&b.push(d)}return b}function Hc(a){return 1===a.nodeType}function Ic(a,b,c,d,e,f){for(a=a.getFirstChild();null!==a;){let g=a.__key;a.__parent===b&&(D(a)&&Ic(a,g,c,d,e,f),c.has(g)||f.delete(g),e.push(g));a=a.getNextSibling()}}
function Jc(a,b,c,d){a=a._nodeMap;b=b._nodeMap;let e=[];for(let [f]of d){let g=b.get(f);void 0===g||g.isAttached()||(D(g)&&Ic(g,f,a,b,e,d),a.has(f)||d.delete(f),e.push(f))}for(let f of e)b.delete(f);for(let f of c)d=b.get(f),void 0===d||d.isAttached()||(a.has(f)||c.delete(f),b.delete(f))}let L="",M="",Kc="",Lc,N,Mc,Nc=!1,Oc=!1,Pc,Qc=null,Rc,Sc,Tc,Uc,Vc,ed;
function fd(a,b){let c=Tc.get(a);if(null!==b){let d=gd(a);d.parentNode===b&&b.removeChild(d)}Uc.has(a)||N._keyToDOMMap.delete(a);D(c)&&(a=hd(c,Tc),id(a,0,a.length-1,null));void 0!==c&&rc(ed,Mc,Pc,c,"destroyed")}function id(a,b,c,d){for(;b<=c;++b){let e=a[b];void 0!==e&&fd(e,d)}}function jd(a,b){a.setProperty("text-align",b)}
function kd(a,b){var c=Lc.theme.indent;if("string"===typeof c){let d=a.classList.contains(c);0<b&&!d?a.classList.add(c):1>b&&d&&a.classList.remove(c)}c=getComputedStyle(a).getPropertyValue("--lexical-indent-base-value")||"40px";a.style.setProperty("padding-inline-start",0===b?"":`calc(${b} * ${c})`)}function ld(a,b){a=a.style;0===b?jd(a,""):1===b?jd(a,"left"):2===b?jd(a,"center"):3===b?jd(a,"right"):4===b?jd(a,"justify"):5===b?jd(a,"start"):6===b&&jd(a,"end")}
function md(a,b,c){let d=Uc.get(a);void 0===d&&r(60);let e=d.createDOM(Lc,N);var f=N._keyToDOMMap;e["__lexicalKey_"+N._key]=a;f.set(a,e);B(d)?e.setAttribute("data-lexical-text","true"):z(d)&&e.setAttribute("data-lexical-decorator","true");if(D(d)){a=d.__indent;f=d.__size;0!==a&&kd(e,a);if(0!==f){--f;a=hd(d,Uc);var g=M;M="";nd(a,d,0,f,e,null);od(d,e);M=g}a=d.__format;0!==a&&ld(e,a);d.isInline()||pd(null,d,e);uc(d)&&(L+="\n\n",Kc+="\n\n")}else f=d.getTextContent(),z(d)?(g=d.decorate(N,Lc),null!==g&&
qd(a,g),e.contentEditable="false"):B(d)&&(d.isDirectionless()||(M+=f)),L+=f,Kc+=f;null!==b&&(null!=c?b.insertBefore(e,c):(c=b.__lexicalLineBreak,null!=c?b.insertBefore(e,c):b.appendChild(e)));rc(ed,Mc,Pc,d,"created");return e}function nd(a,b,c,d,e,f){let g=L;for(L="";c<=d;++c)md(a[c],e,f);uc(b)&&(L+="\n\n");e.__lexicalTextContent=L;L=g+L}function rd(a,b){a=b.get(a);return Yb(a)||z(a)&&a.isInline()}
function pd(a,b,c){a=null!==a&&(0===a.__size||rd(a.__last,Tc));b=0===b.__size||rd(b.__last,Uc);a?b||(b=c.__lexicalLineBreak,null!=b&&c.removeChild(b),c.__lexicalLineBreak=null):b&&(b=document.createElement("br"),c.__lexicalLineBreak=b,c.appendChild(b))}
function od(a,b){var c=b.__lexicalDir;if(b.__lexicalDirTextContent!==M||c!==Qc){let f=""===M;if(f)var d=Qc;else d=M,d=db.test(d)?"rtl":eb.test(d)?"ltr":null;if(d!==c){let g=b.classList,h=Lc.theme;var e=null!==c?h[c]:void 0;let k=null!==d?h[d]:void 0;void 0!==e&&("string"===typeof e&&(e=e.split(" "),e=h[c]=e),g.remove(...e));null===d||f&&"ltr"===d?b.removeAttribute("dir"):(void 0!==k&&("string"===typeof k&&(c=k.split(" "),k=h[d]=c),void 0!==k&&g.add(...k)),b.dir=d);Oc||(a.getWritable().__dir=d)}Qc=
d;b.__lexicalDirTextContent=M;b.__lexicalDir=d}}function hd(a,b){let c=[];for(a=a.__first;null!==a;){let d=b.get(a);void 0===d&&r(101);c.push(a);a=d.__next}return c}
function sd(a,b){var c=Tc.get(a),d=Uc.get(a);void 0!==c&&void 0!==d||r(61);var e=Nc||Sc.has(a)||Rc.has(a);let f=vc(N,a);if(c===d&&!e)return D(c)?(d=f.__lexicalTextContent,void 0!==d&&(L+=d,Kc+=d),d=f.__lexicalDirTextContent,void 0!==d&&(M+=d)):(d=c.getTextContent(),B(c)&&!c.isDirectionless()&&(M+=d),Kc+=d,L+=d),f;c!==d&&e&&rc(ed,Mc,Pc,d,"updated");if(d.updateDOM(c,f,Lc))return d=md(a,null,null),null===b&&r(62),b.replaceChild(d,f),fd(a,null),d;if(D(c)&&D(d)){a=d.__indent;a!==c.__indent&&kd(f,a);a=
d.__format;a!==c.__format&&ld(f,a);if(e){a=d;e=M;M="";b=L;var g=c.__size,h=a.__size;L="";if(1===g&&1===h){var k=c.__first,m=a.__first;if(k===m)sd(k,f);else{var n=gd(k);m=md(m,null,null);f.replaceChild(m,n);fd(k,null)}}else{m=hd(c,Tc);var p=hd(a,Uc);if(0===g)0!==h&&nd(p,a,0,h-1,f,null);else if(0===h)0!==g&&(k=null==f.__lexicalLineBreak,id(m,0,g-1,k?null:f),k&&(f.textContent=""));else{var l=m;m=p;p=g-1;g=h-1;let u=f.firstChild,x=0;for(h=0;x<=p&&h<=g;){var q=l[x];let y=m[h];if(q===y)u=td(sd(y,f)),x++,
h++;else{void 0===k&&(k=new Set(l));void 0===n&&(n=new Set(m));let A=n.has(q),Z=k.has(y);A?(Z?(q=vc(N,y),q===u?u=td(sd(y,f)):(null!=u?f.insertBefore(q,u):f.appendChild(q),sd(y,f)),x++):md(y,f,u),h++):(u=td(gd(q)),fd(q,f),x++)}}k=x>p;n=h>g;k&&!n?(k=m[g+1],k=void 0===k?null:N.getElementByKey(k),nd(m,a,h,g,f,k)):n&&!k&&id(l,x,p,f)}}uc(a)&&(L+="\n\n");f.__lexicalTextContent=L;L=b+L;od(a,f);M=e;K(d)||d.isInline()||pd(c,d,f)}uc(d)&&(L+="\n\n",Kc+="\n\n")}else c=d.getTextContent(),z(d)?(e=d.decorate(N,Lc),
null!==e&&qd(a,e)):B(d)&&!d.isDirectionless()&&(M+=c),L+=c,Kc+=c;!Oc&&K(d)&&d.__cachedText!==Kc&&(d=d.getWritable(),d.__cachedText=Kc);return f}function qd(a,b){let c=N._pendingDecorators,d=N._decorators;if(null===c){if(d[a]===b)return;c=fc(N)}c[a]=b}function td(a){a=a.nextSibling;null!==a&&a===N._blockCursorElement&&(a=a.nextSibling);return a}function gd(a){let b=Vc.get(a);void 0===b&&r(75,a);return b}
let ud=Object.freeze({}),Bd=[["keydown",vd],["pointerdown",wd],["compositionstart",xd],["compositionend",yd],["input",zd],["click",Ad],["cut",ud],["copy",ud],["dragstart",ud],["dragover",ud],["dragend",ud],["paste",ud],["focus",ud],["blur",ud],["drop",ud]];Xa&&Bd.push(["beforeinput",(a,b)=>Cd(a,b)]);let Dd=0,Ed=0,Fd=0,Gd=null,Hd=0,Id=!1,Jd=!1,Kd=!1,Ld=!1,Md=[0,"",0,"root",0];
function Nd(a,b,c,d,e){let f=a.anchor,g=a.focus,h=f.getNode();var k=F();let m=vb(k._window),n=null!==m?m.anchorNode:null,p=f.key;k=k.getElementByKey(p);let l=c.length;return p!==g.key||!B(h)||(!e&&(!Xa||Fd<d+50)||h.isDirty()&&2>l||kc(c))&&f.offset!==g.offset&&!h.isComposing()||Ob(h)||h.isDirty()&&1<l||(e||!Xa)&&null!==k&&!h.isComposing()&&n!==Vb(k)||null!==m&&null!==b&&(!b.collapsed||b.startContainer!==m.anchorNode||b.startOffset!==m.anchorOffset)||h.getFormat()!==a.format||h.getStyle()!==a.style||
pc(a,h)}function Od(a,b){return null!==a&&null!==a.nodeValue&&3===a.nodeType&&0!==b&&b!==a.nodeValue.length}
function Pd(a,b,c){let {anchorNode:d,anchorOffset:e,focusNode:f,focusOffset:g}=a;if(Id&&(Id=!1,Od(d,e)&&Od(f,g)))return;w(b,()=>{if(!c)yb(null);else if(Lb(b,d,f)){var h=v();if(C(h)){var k=h.anchor,m=k.getNode();if(h.isCollapsed()){"Range"===a.type&&a.anchorNode===a.focusNode&&(h.dirty=!0);var n=Cb(b).event;n=n?n.timeStamp:performance.now();let [p,l,q,u,x]=Md;n<x+200&&k.offset===q&&k.key===u?(h.format=p,h.style=l):"text"===k.type?(h.format=m.getFormat(),h.style=m.getStyle()):"element"===k.type&&(h.format=
0,h.style="")}else{k=255;m=!1;n=h.getNodes();let p=n.length;for(let l=0;l<p;l++){let q=n[l];if(B(q)&&(m=!0,k&=q.getFormat(),0===k))break}h.format=m?k:0}}O(b,aa,void 0)}})}
function Ad(a,b){w(b,()=>{let c=v();var d=vb(b._window);let e=oc();if(d)if(C(c)){let g=c.anchor;var f=g.getNode();"element"===g.type&&0===g.offset&&c.isCollapsed()&&!K(f)&&1===hc().getChildrenSize()&&f.getTopLevelElementOrThrow().isEmpty()&&null!==e&&c.is(e)?(d.removeAllRanges(),c.dirty=!0):3!==a.detail||c.isCollapsed()||(d=c.focus.getNode(),f!==d&&(D(f)?f.select(0):f.getParentOrThrow().select(0)))}else"touch"===a.pointerType&&(f=d.anchorNode,null!==f&&(f=f.nodeType,1===f||3===f))&&(d=Qd(e,d,b),yb(d));
O(b,ba,a)})}function wd(a,b){let c=a.target;a=a.pointerType;c instanceof Node&&"touch"!==a&&w(b,()=>{z(ub(c))||(Jd=!0)})}function Rd(a){if(!a.getTargetRanges)return null;a=a.getTargetRanges();return 0===a.length?null:a[0]}function Sd(a,b){return a!==b||D(a)||D(b)||!a.isToken()||!b.isToken()}
function Cd(a,b){let c=a.inputType,d=Rd(a);"deleteCompositionText"===c||Wa&&zb(b)||"insertCompositionText"!==c&&w(b,()=>{let e=v();if("deleteContentBackward"===c){if(null===e){var f=oc();if(!C(f))return;yb(f.clone())}if(C(e)){229===Ed&&a.timeStamp<Dd+30&&b.isComposing()&&e.anchor.key===e.focus.key?(H(null),Dd=0,setTimeout(()=>{w(b,()=>{H(null)})},30),C(e)&&(f=e.anchor.getNode(),f.markDirty(),e.format=f.getFormat(),e.style=f.getStyle())):(a.preventDefault(),O(b,da,!0));return}}if(C(e)){f=a.data;null!==
Gd&&nc(!1,b,Gd);e.dirty&&null===Gd||!e.isCollapsed()||K(e.anchor.getNode())||null===d||e.applyDOMRange(d);Gd=null;var g=e.focus,h=e.anchor.getNode();g=g.getNode();if("insertText"===c||"insertTranspose"===c)"\n"===f?(a.preventDefault(),O(b,ea,!1)):"\n\n"===f?(a.preventDefault(),O(b,fa,void 0)):null==f&&a.dataTransfer?(f=a.dataTransfer.getData("text/plain"),a.preventDefault(),e.insertRawText(f)):null!=f&&Nd(e,d,f,a.timeStamp,!0)?(a.preventDefault(),O(b,ha,f)):Gd=f,Fd=a.timeStamp;else switch(a.preventDefault(),
c){case "insertFromYank":case "insertFromDrop":case "insertReplacementText":O(b,ha,a);break;case "insertFromComposition":H(null);O(b,ha,a);break;case "insertLineBreak":H(null);O(b,ea,!1);break;case "insertParagraph":H(null);Kd&&!Za?(Kd=!1,O(b,ea,!1)):O(b,fa,void 0);break;case "insertFromPaste":case "insertFromPasteAsQuotation":O(b,ka,a);break;case "deleteByComposition":Sd(h,g)&&O(b,ma,a);break;case "deleteByDrag":case "deleteByCut":O(b,ma,a);break;case "deleteContent":O(b,da,!1);break;case "deleteWordBackward":O(b,
na,!0);break;case "deleteWordForward":O(b,na,!1);break;case "deleteHardLineBackward":case "deleteSoftLineBackward":O(b,pa,!0);break;case "deleteContentForward":case "deleteHardLineForward":case "deleteSoftLineForward":O(b,pa,!1);break;case "formatStrikeThrough":O(b,qa,"strikethrough");break;case "formatBold":O(b,qa,"bold");break;case "formatItalic":O(b,qa,"italic");break;case "formatUnderline":O(b,qa,"underline");break;case "historyUndo":O(b,ra,void 0);break;case "historyRedo":O(b,sa,void 0)}}})}
function zd(a,b){a.stopPropagation();w(b,()=>{var c=v(),d=a.data,e=Rd(a);if(null!=d&&C(c)&&Nd(c,e,d,a.timeStamp,!1)){Ld&&(Td(b,d),Ld=!1);var f=c.anchor,g=f.getNode();e=vb(b._window);if(null===e)return;let h=f.offset;if(f=Xa&&!c.isCollapsed()&&B(g)&&null!==e.anchorNode)g=g.getTextContent().slice(0,h)+d+g.getTextContent().slice(h+c.focus.offset),e=e.anchorNode,f=g===(3===e.nodeType?e.nodeValue:null);f||O(b,ha,d);d=d.length;Wa&&1<d&&"insertCompositionText"===a.inputType&&!b.isComposing()&&(c.anchor.offset-=
d);Ya||Za||ab||!b.isComposing()||(Dd=0,H(null))}else nc(!1,b,null!==d?d:void 0),Ld&&(Td(b,d||void 0),Ld=!1);G();c=F();Ab(c)});Gd=null}function xd(a,b){w(b,()=>{let c=v();if(C(c)&&!b.isComposing()){let d=c.anchor,e=c.anchor.getNode();H(d.key);(a.timeStamp<Dd+30||"element"===d.type||!c.isCollapsed()||e.getFormat()!==c.format||e.getStyle()!==c.style)&&O(b,ha,cb)}})}
function Td(a,b){var c=a._compositionKey;H(null);if(null!==c&&null!=b){if(""===b){b=I(c);a=Vb(a.getElementByKey(c));null!==a&&null!==a.nodeValue&&B(b)&&wb(b,a.nodeValue,null,null,!0);return}if("\n"===b[b.length-1]&&(c=v(),C(c))){b=c.focus;c.anchor.set(b.key,b.offset,b.type);O(a,Ba,null);return}}nc(!0,a,b)}function yd(a,b){Wa?Ld=!0:w(b,()=>{Td(b,a.data)})}
function vd(a,b){Dd=a.timeStamp;Ed=a.keyCode;if(!b.isComposing()){var {keyCode:c,shiftKey:d,ctrlKey:e,metaKey:f,altKey:g}=a;if(!O(b,ta,a)){if(39!==c||e||f||g)if(39!==c||g||d||!e&&!f)if(37!==c||e||f||g)if(37!==c||g||d||!e&&!f)if(38!==c||e||f)if(40!==c||e||f)if(13===c&&d)Kd=!0,O(b,Ba,a);else if(32===c)O(b,Ca,a);else if(t&&e&&79===c)a.preventDefault(),Kd=!0,O(b,ea,!0);else if(13!==c||d){var h=t?g||f?!1:8===c||72===c&&e:e||g||f?!1:8===c;h?8===c?O(b,Fa,a):(a.preventDefault(),O(b,da,!0)):27===c?O(b,Ga,
a):(h=t?d||g||f?!1:46===c||68===c&&e:e||g||f?!1:46===c,h?46===c?O(b,Ha,a):(a.preventDefault(),O(b,da,!1)):8===c&&(t?g:e)?(a.preventDefault(),O(b,na,!0)):46===c&&(t?g:e)?(a.preventDefault(),O(b,na,!1)):t&&f&&8===c?(a.preventDefault(),O(b,pa,!0)):t&&f&&46===c?(a.preventDefault(),O(b,pa,!1)):66===c&&!g&&(t?f:e)?(a.preventDefault(),O(b,qa,"bold")):85===c&&!g&&(t?f:e)?(a.preventDefault(),O(b,qa,"underline")):73===c&&!g&&(t?f:e)?(a.preventDefault(),O(b,qa,"italic")):9!==c||g||e||f?90===c&&!d&&(t?f:e)?(a.preventDefault(),
O(b,ra,void 0)):(h=t?90===c&&f&&d:89===c&&e||90===c&&e&&d,h?(a.preventDefault(),O(b,sa,void 0)):Ud(b._editorState._selection)?(h=d?!1:67===c?t?f:e:!1,h?(a.preventDefault(),O(b,Na,a)):(h=d?!1:88===c?t?f:e:!1,h?(a.preventDefault(),O(b,Oa,a)):65===c&&(t?f:e)&&(a.preventDefault(),O(b,Pa,a)))):!Wa&&65===c&&(t?f:e)&&(a.preventDefault(),O(b,Pa,a))):O(b,Ia,a))}else Kd=!1,O(b,Ba,a);else O(b,Aa,a);else O(b,za,a);else O(b,ya,a);else O(b,xa,a);else O(b,va,a);else O(b,ua,a);(e||d||g||f)&&O(b,Sa,a)}}}
function Vd(a){let b=a.__lexicalEventHandles;void 0===b&&(b=[],a.__lexicalEventHandles=b);return b}let Wd=new Map;function Xd(a){a=a.target;let b=vb(null==a?null:9===a.nodeType?a.defaultView:a.ownerDocument.defaultView);if(null!==b){var c=Mb(b.anchorNode);if(null!==c){Jd&&(Jd=!1,w(c,()=>{var g=oc(),h=b.anchorNode;null!==h&&(h=h.nodeType,1===h||3===h)&&(g=Qd(g,b,c),yb(g))}));a=lc(c);a=a[a.length-1];var d=a._key,e=Wd.get(d),f=e||a;f!==c&&Pd(b,f,!1);Pd(b,c,!0);c!==a?Wd.set(d,c):e&&Wd.delete(d)}}}
function Yd(a,b){0===Hd&&a.ownerDocument.addEventListener("selectionchange",Xd);Hd++;a.__lexicalEditor=b;let c=Vd(a);for(let d=0;d<Bd.length;d++){let [e,f]=Bd[d],g="function"===typeof f?h=>{!0!==h._lexicalHandled&&(h._lexicalHandled=!0,b.isEditable()&&f(h,b))}:h=>{if(!0!==h._lexicalHandled&&(h._lexicalHandled=!0,b.isEditable()))switch(e){case "cut":return O(b,Oa,h);case "copy":return O(b,Na,h);case "paste":return O(b,ka,h);case "dragstart":return O(b,Ka,h);case "dragover":return O(b,La,h);case "dragend":return O(b,
Ma,h);case "focus":return O(b,Qa,h);case "blur":return O(b,Ra,h);case "drop":return O(b,Ja,h)}};a.addEventListener(e,g);c.push(()=>{a.removeEventListener(e,g)})}}
function Zd(a,b,c){G();var d=a.__key;let e=a.getParent();if(null!==e){var f=v();if(C(f)&&D(a)){var {anchor:g,focus:h}=f;var k=g.getNode();var m=h.getNode();wc(k,a)&&g.set(a.__key,0,"element");wc(m,a)&&h.set(a.__key,0,"element")}k=f;m=!1;if(C(k)&&b){f=k.anchor;let n=k.focus;f.key===d&&($d(f,a,e,a.getPreviousSibling(),a.getNextSibling()),m=!0);n.key===d&&($d(n,a,e,a.getPreviousSibling(),a.getNextSibling()),m=!0)}else Ud(k)&&b&&a.isSelected()&&a.selectPrevious();C(k)&&b&&!m?(d=a.getIndexWithinParent(),
bc(a),ae(k,e,d,-1)):bc(a);c||yc(e)||e.canBeEmpty()||!e.isEmpty()||Zd(e,b);b&&K(e)&&e.isEmpty()&&e.selectEnd()}}
class be{static getType(){r(64,this.name)}static clone(){r(65,this.name)}constructor(a){this.__type=this.constructor.getType();this.__next=this.__prev=this.__parent=null;Zb(this,a)}getType(){return this.__type}isAttached(){for(var a=this.__key;null!==a;){if("root"===a)return!0;a=I(a);if(null===a)break;a=a.__parent}return!1}isSelected(a){a=a||v();if(null==a)return!1;let b=a.getNodes().some(c=>c.__key===this.__key);return B(this)?b:C(a)&&"element"===a.anchor.type&&"element"===a.focus.type&&a.anchor.key===
a.focus.key&&a.anchor.offset===a.focus.offset?!1:b}getKey(){return this.__key}getIndexWithinParent(){var a=this.getParent();if(null===a)return-1;a=a.getFirstChild();let b=0;for(;null!==a;){if(this.is(a))return b;b++;a=a.getNextSibling()}return-1}getParent(){let a=this.getLatest().__parent;return null===a?null:I(a)}getParentOrThrow(){let a=this.getParent();null===a&&r(66,this.__key);return a}getTopLevelElement(){let a=this;for(;null!==a;){let b=a.getParent();if(yc(b))return a;a=b}return null}getTopLevelElementOrThrow(){let a=
this.getTopLevelElement();null===a&&r(67,this.__key);return a}getParents(){let a=[],b=this.getParent();for(;null!==b;)a.push(b),b=b.getParent();return a}getParentKeys(){let a=[],b=this.getParent();for(;null!==b;)a.push(b.__key),b=b.getParent();return a}getPreviousSibling(){let a=this.getLatest().__prev;return null===a?null:I(a)}getPreviousSiblings(){let a=[];var b=this.getParent();if(null===b)return a;for(b=b.getFirstChild();null!==b&&!b.is(this);)a.push(b),b=b.getNextSibling();return a}getNextSibling(){let a=
this.getLatest().__next;return null===a?null:I(a)}getNextSiblings(){let a=[],b=this.getNextSibling();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getCommonAncestor(a){let b=this.getParents();var c=a.getParents();D(this)&&b.unshift(this);D(a)&&c.unshift(a);a=b.length;var d=c.length;if(0===a||0===d||b[a-1]!==c[d-1])return null;c=new Set(c);for(d=0;d<a;d++){let e=b[d];if(c.has(e))return e}return null}is(a){return null==a?!1:this.__key===a.__key}isBefore(a){if(this===a)return!1;if(a.isParentOf(this))return!0;
if(this.isParentOf(a))return!1;var b=this.getCommonAncestor(a);let c=this;for(;;){var d=c.getParentOrThrow();if(d===b){d=c.getIndexWithinParent();break}c=d}for(c=a;;){a=c.getParentOrThrow();if(a===b){b=c.getIndexWithinParent();break}c=a}return d<b}isParentOf(a){let b=this.__key;if(b===a.__key)return!1;for(;null!==a;){if(a.__key===b)return!0;a=a.getParent()}return!1}getNodesBetween(a){let b=this.isBefore(a),c=[],d=new Set;for(var e=this;;){var f=e.__key;d.has(f)||(d.add(f),c.push(e));if(e===a)break;
f=D(e)?b?e.getFirstChild():e.getLastChild():null;if(null!==f)e=f;else if(f=b?e.getNextSibling():e.getPreviousSibling(),null!==f)e=f;else{e=e.getParentOrThrow();d.has(e.__key)||c.push(e);if(e===a)break;f=e;do null===f&&r(68),e=b?f.getNextSibling():f.getPreviousSibling(),f=f.getParent(),null!==f&&(null!==e||d.has(f.__key)||c.push(f));while(null===e)}}b||c.reverse();return c}isDirty(){let a=F()._dirtyLeaves;return null!==a&&a.has(this.__key)}getLatest(){let a=I(this.__key);null===a&&r(113);return a}getWritable(){G();
var a=ac(),b=F();a=a._nodeMap;let c=this.__key,d=this.getLatest(),e=d.__parent;b=b._cloneNotNeeded;var f=v();null!==f&&(f._cachedNodes=null);if(b.has(c))return cc(d),d;f=d.constructor.clone(d);f.__parent=e;f.__next=d.__next;f.__prev=d.__prev;D(d)&&D(f)?(f.__first=d.__first,f.__last=d.__last,f.__size=d.__size,f.__indent=d.__indent,f.__format=d.__format,f.__dir=d.__dir):B(d)&&B(f)&&(f.__format=d.__format,f.__style=d.__style,f.__mode=d.__mode,f.__detail=d.__detail);b.add(c);f.__key=c;cc(f);a.set(c,f);
return f}getTextContent(){return""}getTextContentSize(){return this.getTextContent().length}createDOM(){r(70)}updateDOM(){r(71)}exportDOM(a){return{element:this.createDOM(a._config,a)}}exportJSON(){r(72)}static importJSON(){r(18,this.name)}static transform(){return null}remove(a){Zd(this,!0,a)}replace(a,b){G();var c=v();null!==c&&(c=c.clone());Bc(this,a);let d=this.getLatest(),e=this.__key,f=a.__key,g=a.getWritable();a=this.getParentOrThrow().getWritable();let h=a.__size;bc(g);let k=d.getPreviousSibling(),
m=d.getNextSibling(),n=d.__prev,p=d.__next,l=d.__parent;Zd(d,!1,!0);null===k?a.__first=f:k.getWritable().__next=f;g.__prev=n;null===m?a.__last=f:m.getWritable().__prev=f;g.__next=p;g.__parent=l;a.__size=h;b&&this.getChildren().forEach(q=>{g.append(q)});C(c)&&(yb(c),b=c.anchor,c=c.focus,b.key===e&&ce(b,g),c.key===e&&ce(c,g));dc()===e&&H(f);return g}insertAfter(a,b=!0){G();Bc(this,a);var c=this.getWritable();let d=a.getWritable();var e=d.getParent();let f=v();var g=!1,h=!1;if(null!==e){var k=a.getIndexWithinParent();
bc(d);C(f)&&(h=e.__key,g=f.anchor,e=f.focus,g="element"===g.type&&g.key===h&&g.offset===k+1,h="element"===e.type&&e.key===h&&e.offset===k+1)}e=this.getNextSibling();k=this.getParentOrThrow().getWritable();let m=d.__key,n=c.__next;null===e?k.__last=m:e.getWritable().__prev=m;k.__size++;c.__next=m;d.__next=n;d.__prev=c.__key;d.__parent=c.__parent;b&&C(f)&&(b=this.getIndexWithinParent(),ae(f,k,b+1),c=k.__key,g&&f.anchor.set(c,b+2,"element"),h&&f.focus.set(c,b+2,"element"));return a}insertBefore(a,b=
!0){G();Bc(this,a);var c=this.getWritable();let d=a.getWritable(),e=d.__key;bc(d);let f=this.getPreviousSibling(),g=this.getParentOrThrow().getWritable(),h=c.__prev,k=this.getIndexWithinParent();null===f?g.__first=e:f.getWritable().__next=e;g.__size++;c.__prev=e;d.__prev=h;d.__next=c.__key;d.__parent=c.__parent;c=v();b&&C(c)&&(b=this.getParentOrThrow(),ae(c,b,k));return a}isParentRequired(){return!1}createParentElementNode(){return de()}selectPrevious(a,b){G();let c=this.getPreviousSibling(),d=this.getParentOrThrow();
return null===c?d.select(0,0):D(c)?c.select():B(c)?c.select(a,b):(a=c.getIndexWithinParent()+1,d.select(a,a))}selectNext(a,b){G();let c=this.getNextSibling(),d=this.getParentOrThrow();return null===c?d.select():D(c)?c.select(0,0):B(c)?c.select(a,b):(a=c.getIndexWithinParent(),d.select(a,a))}markDirty(){this.getWritable()}}
class ee extends be{static getType(){return"linebreak"}static clone(a){return new ee(a.__key)}constructor(a){super(a)}getTextContent(){return"\n"}createDOM(){return document.createElement("br")}updateDOM(){return!1}static importDOM(){return{br:a=>{let b=a.parentElement,c,d;return null!==b&&((c=b.firstChild)===a||c.nextSibling===a&&3===c.nodeType&&null!==(c.textContent||"").match(/^( |\t|\r?\n)+$/))&&((d=b.lastChild)===a||d.previousSibling===a&&3===d.nodeType&&null!==(d.textContent||"").match(/^( |\t|\r?\n)+$/))?
null:{conversion:fe,priority:0}}}}static importJSON(){return ge()}exportJSON(){return{type:"linebreak",version:1}}}function fe(){return{node:ge()}}function ge(){return Ac(new ee)}function Yb(a){return a instanceof ee}function he(a,b){return b&16?"code":b&128?"mark":b&32?"sub":b&64?"sup":null}function ie(a,b){return b&1?"strong":b&2?"em":"span"}
function je(a,b,c,d,e){a=d.classList;d=qc(e,"base");void 0!==d&&a.add(...d);d=qc(e,"underlineStrikethrough");let f=!1,g=b&8&&b&4;var h=c&8&&c&4;void 0!==d&&(h?(f=!0,g||a.add(...d)):g&&a.remove(...d));for(let k in fb)h=fb[k],d=qc(e,k),void 0!==d&&(c&h?!f||"underline"!==k&&"strikethrough"!==k?(0===(b&h)||g&&"underline"===k||"strikethrough"===k)&&a.add(...d):b&h&&a.remove(...d):b&h&&a.remove(...d))}
function ke(a,b,c){let d=b.firstChild;c=c.isComposing();a+=c?bb:"";if(null==d)b.textContent=a;else if(b=d.nodeValue,b!==a)if(c||Wa){c=b.length;let e=a.length,f=0,g=0;for(;f<c&&f<e&&b[f]===a[f];)f++;for(;g+f<c&&g+f<e&&b[c-g-1]===a[e-g-1];)g++;a=[f,c-f-g,a.slice(f,e-g)];let [h,k,m]=a;0!==k&&d.deleteData(h,k);d.insertData(h,m)}else d.nodeValue=a}function le(a,b){b=document.createElement(b);b.appendChild(a);return b}
class me extends be{static getType(){return"text"}static clone(a){return new me(a.__text,a.__key)}constructor(a,b){super(b);this.__text=a;this.__format=0;this.__style="";this.__detail=this.__mode=0}getFormat(){return this.getLatest().__format}getDetail(){return this.getLatest().__detail}getMode(){let a=this.getLatest();return kb[a.__mode]}getStyle(){return this.getLatest().__style}isToken(){return 1===this.getLatest().__mode}isComposing(){return this.__key===dc()}isSegmented(){return 2===this.getLatest().__mode}isDirectionless(){return 0!==
(this.getLatest().__detail&1)}isUnmergeable(){return 0!==(this.getLatest().__detail&2)}hasFormat(a){a=fb[a];return 0!==(this.getFormat()&a)}isSimpleText(){return"text"===this.__type&&0===this.__mode}getTextContent(){return this.getLatest().__text}getFormatFlags(a,b){let c=this.getLatest().__format;return Wb(c,a,b)}createDOM(a){var b=this.__format,c=he(this,b);let d=ie(this,b),e=document.createElement(null===c?d:c),f=e;this.hasFormat("code")&&e.setAttribute("spellcheck","false");null!==c&&(f=document.createElement(d),
e.appendChild(f));c=f;ke(this.__text,c,this);a=a.theme.text;void 0!==a&&je(d,0,b,c,a);b=this.__style;""!==b&&(e.style.cssText=b);return e}updateDOM(a,b,c){let d=this.__text;var e=a.__format,f=this.__format,g=he(this,e);let h=he(this,f);var k=ie(this,e);let m=ie(this,f);if((null===g?k:g)!==(null===h?m:h))return!0;if(g===h&&k!==m)return e=b.firstChild,null==e&&r(48),a=g=document.createElement(m),ke(d,a,this),c=c.theme.text,void 0!==c&&je(m,0,f,a,c),b.replaceChild(g,e),!1;k=b;null!==h&&null!==g&&(k=
b.firstChild,null==k&&r(49));ke(d,k,this);c=c.theme.text;void 0!==c&&e!==f&&je(m,e,f,k,c);f=this.__style;a.__style!==f&&(b.style.cssText=f);return!1}static importDOM(){return{"#text":()=>({conversion:ne,priority:0}),b:()=>({conversion:oe,priority:0}),code:()=>({conversion:pe,priority:0}),em:()=>({conversion:pe,priority:0}),i:()=>({conversion:pe,priority:0}),s:()=>({conversion:pe,priority:0}),span:()=>({conversion:qe,priority:0}),strong:()=>({conversion:pe,priority:0}),sub:()=>({conversion:pe,priority:0}),
sup:()=>({conversion:pe,priority:0}),u:()=>({conversion:pe,priority:0})}}static importJSON(a){let b=J(a.text);b.setFormat(a.format);b.setDetail(a.detail);b.setMode(a.mode);b.setStyle(a.style);return b}exportDOM(a){({element:a}=super.exportDOM(a));null!==a&&Hc(a)||r(132);a.style.whiteSpace="pre-wrap";this.hasFormat("bold")&&(a=le(a,"b"));this.hasFormat("italic")&&(a=le(a,"i"));this.hasFormat("strikethrough")&&(a=le(a,"s"));this.hasFormat("underline")&&(a=le(a,"u"));return{element:a}}exportJSON(){return{detail:this.getDetail(),
format:this.getFormat(),mode:this.getMode(),style:this.getStyle(),text:this.getTextContent(),type:"text",version:1}}selectionTransform(){}setFormat(a){let b=this.getWritable();b.__format="string"===typeof a?fb[a]:a;return b}setDetail(a){let b=this.getWritable();b.__detail="string"===typeof a?gb[a]:a;return b}setStyle(a){let b=this.getWritable();b.__style=a;return b}toggleFormat(a){a=fb[a];return this.setFormat(this.getFormat()^a)}toggleDirectionless(){let a=this.getWritable();a.__detail^=1;return a}toggleUnmergeable(){let a=
this.getWritable();a.__detail^=2;return a}setMode(a){a=jb[a];if(this.__mode===a)return this;let b=this.getWritable();b.__mode=a;return b}setTextContent(a){if(this.__text===a)return this;let b=this.getWritable();b.__text=a;return b}select(a,b){G();let c=v();var d=this.getTextContent();let e=this.__key;"string"===typeof d?(d=d.length,void 0===a&&(a=d),void 0===b&&(b=d)):b=a=0;if(C(c))d=dc(),d!==c.anchor.key&&d!==c.focus.key||H(e),c.setTextNodeRange(this,a,this,b);else return re(e,a,e,b,"text","text");
return c}spliceText(a,b,c,d){let e=this.getWritable(),f=e.__text,g=c.length,h=a;0>h&&(h=g+h,0>h&&(h=0));let k=v();d&&C(k)&&(a+=g,k.setTextNodeRange(e,a,e,a));b=f.slice(0,h)+c+f.slice(h+b);e.__text=b;return e}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}splitText(...a){G();var b=this.getLatest(),c=b.getTextContent(),d=b.__key,e=dc(),f=new Set(a);a=[];var g=c.length,h="";for(var k=0;k<g;k++)""!==h&&f.has(k)&&(a.push(h),h=""),h+=c[k];""!==h&&a.push(h);f=a.length;if(0===f)return[];if(a[0]===
c)return[b];var m=a[0];c=b.getParentOrThrow();k=b.getFormat();let n=b.getStyle(),p=b.__detail;g=!1;b.isSegmented()?(h=J(m),h.__format=k,h.__style=n,h.__detail=p,g=!0):(h=b.getWritable(),h.__text=m);b=v();h=[h];m=m.length;for(let u=1;u<f;u++){var l=a[u],q=l.length;l=J(l).getWritable();l.__format=k;l.__style=n;l.__detail=p;let x=l.__key;q=m+q;if(C(b)){let y=b.anchor,A=b.focus;y.key===d&&"text"===y.type&&y.offset>m&&y.offset<=q&&(y.key=x,y.offset-=m,b.dirty=!0);A.key===d&&"text"===A.type&&A.offset>m&&
A.offset<=q&&(A.key=x,A.offset-=m,b.dirty=!0)}e===d&&H(x);m=q;h.push(l)}d=this.getPreviousSibling();e=this.getNextSibling();null!==d&&cc(d);null!==e&&cc(e);d=c.getWritable();e=this.getIndexWithinParent();g?(d.splice(e,0,h),this.remove()):d.splice(e,1,h);C(b)&&ae(b,c,e,f-1);return h}mergeWithSibling(a){var b=a===this.getPreviousSibling();b||a===this.getNextSibling()||r(50);var c=this.__key;let d=a.__key,e=this.__text,f=e.length;dc()===d&&H(c);let g=v();if(C(g)){let h=g.anchor,k=g.focus;null!==h&&h.key===
d&&(se(h,b,c,a,f),g.dirty=!0);null!==k&&k.key===d&&(se(k,b,c,a,f),g.dirty=!0)}c=a.__text;this.setTextContent(b?c+e:e+c);b=this.getWritable();a.remove();return b}isTextEntity(){return!1}}
function qe(a){let b="700"===a.style.fontWeight,c="line-through"===a.style.textDecoration,d="italic"===a.style.fontStyle,e="underline"===a.style.textDecoration,f=a.style.verticalAlign;return{forChild:g=>{if(!B(g))return g;b&&g.toggleFormat("bold");c&&g.toggleFormat("strikethrough");d&&g.toggleFormat("italic");e&&g.toggleFormat("underline");"sub"===f&&g.toggleFormat("subscript");"super"===f&&g.toggleFormat("superscript");return g},node:null}}
function oe(a){let b="normal"===a.style.fontWeight;return{forChild:c=>{B(c)&&!b&&c.toggleFormat("bold");return c},node:null}}let te=new WeakMap;
function ne(a){null===a.parentElement&&r(129);for(var b=a.textContent||"",c,d=a.parentNode,e=[a];null!==d&&void 0===(c=te.get(d))&&!("PRE"===d.nodeName||1===d.nodeType&&d.style.whiteSpace.startsWith("pre"));)e.push(d),d=d.parentNode;c=void 0===c?d:c;for(d=0;d<e.length;d++)te.set(e[d],c);if(null!==c){b=b.split(/(\r?\n|\t)/);a=[];e=b.length;for(c=0;c<e;c++)d=b[c],"\n"===d||"\r\n"===d?a.push(ge()):"\t"===d?a.push(ue()):""!==d&&a.push(J(d));return{node:a}}b=b.replace(/\r/g,"").replace(/[ \t\n]+/g," ");
if(""===b)return{node:null};if(" "===b[0]){e=a;for(c=!0;null!==e&&null!==(e=ve(e,!1));)if(d=e.textContent||"",0<d.length){/[ \t\n]$/.test(d)&&(b=b.slice(1));c=!1;break}c&&(b=b.slice(1))}if(" "===b[b.length-1]){for(e=!0;null!==a&&null!==(a=ve(a,!0));)if(0<(a.textContent||"").replace(/^( |\t|\r?\n)+/,"").length){e=!1;break}e&&(b=b.slice(0,b.length-1))}return""===b?{node:null}:{node:J(b)}}
let we=new RegExp(/^(a|abbr|acronym|b|cite|code|del|em|i|ins|kbd|label|output|q|ruby|s|samp|span|strong|sub|sup|time|u|tt|var)$/,"i");function ve(a,b){for(;;){for(var c=void 0;null===(c=b?a.nextSibling:a.previousSibling);)if(a=a.parentElement,null===a)return null;a=c;if(1===a.nodeType&&(c=a.style.display,""===c&&null===a.nodeName.match(we)||""!==c&&!c.startsWith("inline")))return null;for(;null!==(c=b?a.firstChild:a.lastChild);)a=c;if(3===a.nodeType)return a;if("BR"===a.nodeName)return null}}
let xe={code:"code",em:"italic",i:"italic",s:"strikethrough",strong:"bold",sub:"subscript",sup:"superscript",u:"underline"};function pe(a){let b=xe[a.nodeName.toLowerCase()];return void 0===b?{node:null}:{forChild:c=>{B(c)&&!c.hasFormat(b)&&c.toggleFormat(b);return c},node:null}}function J(a=""){return Ac(new me(a))}function B(a){return a instanceof me}
class ye extends me{static getType(){return"tab"}static clone(a){let b=new ye(a.__key);b.__text=a.__text;b.__format=a.__format;b.__style=a.__style;return b}constructor(a){super("\t",a);this.__detail=2}static importDOM(){return null}static importJSON(a){let b=ue();b.setFormat(a.format);b.setStyle(a.style);return b}exportJSON(){return{...super.exportJSON(),type:"tab",version:1}}setTextContent(){r(126)}setDetail(){r(127)}setMode(){r(128)}canInsertTextBefore(){return!1}canInsertTextAfter(){return!1}}
function ue(){return Ac(new ye)}
class ze{constructor(a,b,c){this._selection=null;this.key=a;this.offset=b;this.type=c}is(a){return this.key===a.key&&this.offset===a.offset&&this.type===a.type}isBefore(a){let b=this.getNode(),c=a.getNode(),d=this.offset;a=a.offset;if(D(b)){var e=b.getDescendantByIndex(d);b=null!=e?e:b}D(c)&&(e=c.getDescendantByIndex(a),c=null!=e?e:c);return b===c?d<a:b.isBefore(c)}getNode(){let a=I(this.key);null===a&&r(20);return a}set(a,b,c){let d=this._selection,e=this.key;this.key=a;this.offset=b;this.type=c;
ec()||(dc()===e&&H(a),null!==d&&(d._cachedNodes=null,d.dirty=!0))}}function Ae(a,b){let c=b.__key,d=a.offset,e="element";if(B(b))e="text",b=b.getTextContentSize(),d>b&&(d=b);else if(!D(b)){var f=b.getNextSibling();if(B(f))c=f.__key,d=0,e="text";else if(f=b.getParent())c=f.__key,d=b.getIndexWithinParent()+1}a.set(c,d,e)}function ce(a,b){if(D(b)){let c=b.getLastDescendant();D(c)||B(c)?Ae(a,c):Ae(a,b)}else Ae(a,b)}
function Be(a,b,c,d){let e=a.getNode(),f=e.getChildAtIndex(a.offset),g=J(),h=K(e)?de().append(g):g;g.setFormat(c);g.setStyle(d);null===f?e.append(h):(f.insertBefore(h),"element"===b.type&&b.key===a.key&&b.offset!==a.offset&&b.set(b.key,b.offset+1,"element"));a.is(b)&&b.set(g.__key,0,"text");a.set(g.__key,0,"text")}function Ce(a,b,c,d){a.key=b;a.offset=c;a.type=d}
class De{constructor(a){this.dirty=!1;this._nodes=a;this._cachedNodes=null}is(a){if(!Ud(a))return!1;let b=this._nodes,c=a._nodes;return b.size===c.size&&Array.from(b).every(d=>c.has(d))}add(a){this.dirty=!0;this._nodes.add(a);this._cachedNodes=null}delete(a){this.dirty=!0;this._nodes.delete(a);this._cachedNodes=null}clear(){this.dirty=!0;this._nodes.clear();this._cachedNodes=null}has(a){return this._nodes.has(a)}clone(){return new De(new Set(this._nodes))}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a,
b){let c=this.getNodes(),d=c.length;var e=c[d-1];if(B(e))e=e.select();else{let f=e.getIndexWithinParent()+1;e=e.getParentOrThrow().select(f,f)}e.insertNodes(a,b);for(a=0;a<d;a++)c[a].remove();return!0}getNodes(){var a=this._cachedNodes;if(null!==a)return a;var b=this._nodes;a=[];for(let c of b)b=I(c),null!==b&&a.push(b);ec()||(this._cachedNodes=a);return a}getTextContent(){let a=this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}
function C(a){return a instanceof Ne}function Oe(a){let [b,,c]=Pe(a);a=c.getChildren();let d=a.length;var e=a[0].getChildren().length;let f=Array(d);for(var g=0;g<d;g++)f[g]=Array(e);for(e=0;e<d;e++){g=a[e].getChildren();let h=0;for(let k=0;k<g.length;k++){for(;f[e][h];)h++;let m=g[k],n=m.__rowSpan||1,p=m.__colSpan||1;for(let l=0;l<n;l++)for(let q=0;q<p;q++)f[e+l][h+q]=m;if(b===m)return{colSpan:p,columnIndex:h,rowIndex:e,rowSpan:n};h+=p}}return null}
class Qe{constructor(a,b,c){this.gridKey=a;this.anchor=b;this.focus=c;this.dirty=!1;this._cachedNodes=null;b._selection=this;c._selection=this}is(a){return Re(a)?this.gridKey===a.gridKey&&this.anchor.is(a.anchor)&&this.focus.is(a.focus):!1}set(a,b,c){this.dirty=!0;this.gridKey=a;this.anchor.key=b;this.focus.key=c;this._cachedNodes=null}clone(){return new Qe(this.gridKey,this.anchor,this.focus)}isCollapsed(){return!1}isBackward(){return this.focus.isBefore(this.anchor)}getCharacterOffsets(){return Se(this)}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a,
b){let c=this.focus.getNode();return Gb(c.select(0,c.getChildrenSize())).insertNodes(a,b)}getShape(){var a=I(this.anchor.key);P(a)||r(103);a=Oe(a);if(null===a)throw Error("getCellRect: expected to find AnchorNode");var b=I(this.focus.key);P(b)||r(104);let c=Oe(b);if(null===c)throw Error("getCellRect: expected to find focusCellNode");b=Math.min(a.columnIndex,c.columnIndex);let d=Math.max(a.columnIndex,c.columnIndex),e=Math.min(a.rowIndex,c.rowIndex);a=Math.max(a.rowIndex,c.rowIndex);return{fromX:Math.min(b,
d),fromY:Math.min(e,a),toX:Math.max(b,d),toY:Math.max(e,a)}}getNodes(){function a(x){let {cell:y,startColumn:A,startRow:Z}=x;h=Math.min(h,A);k=Math.min(k,Z);m=Math.max(m,A+y.__colSpan-1);n=Math.max(n,Z+y.__rowSpan-1)}var b=this._cachedNodes;if(null!==b)return b;var c=this.anchor.getNode();b=this.focus.getNode();c=Fc(c,P);var d=Fc(b,P);P(c)||r(103);P(d)||r(104);b=c.getParent();Te(b)||r(105);b=b.getParent();Ue(b)||r(106);let [e,f,g]=Ve(b,c,d),h=Math.min(f.startColumn,g.startColumn),k=Math.min(f.startRow,
g.startRow),m=Math.max(f.startColumn+f.cell.__colSpan-1,g.startColumn+g.cell.__colSpan-1),n=Math.max(f.startRow+f.cell.__rowSpan-1,g.startRow+g.cell.__rowSpan-1);c=h;d=k;for(var p=h,l=k;h<c||k<d||m>p||n>l;){if(h<c){var q=l-d;--c;for(var u=0;u<=q;u++)a(e[d+u][c])}if(k<d)for(q=p-c,--d,u=0;u<=q;u++)a(e[d][c+u]);if(m>p)for(q=l-d,p+=1,u=0;u<=q;u++)a(e[d+u][p]);if(n>l)for(q=p-c,l+=1,u=0;u<=q;u++)a(e[l][c+u])}b=[b];c=null;for(d=k;d<=n;d++)for(p=h;p<=m;p++)({cell:l}=e[d][p]),q=l.getParent(),Te(q)||r(107),
q!==c&&b.push(q),b.push(l,...Gc(l)),c=q;ec()||(this._cachedNodes=b);return b}getTextContent(){let a=this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}function Re(a){return a instanceof Qe}
class Ne{constructor(a,b,c,d){this.anchor=a;this.focus=b;this.dirty=!1;this.format=c;this.style=d;this._cachedNodes=null;a._selection=this;b._selection=this}is(a){return C(a)?this.anchor.is(a.anchor)&&this.focus.is(a.focus)&&this.format===a.format&&this.style===a.style:!1}isBackward(){return this.focus.isBefore(this.anchor)}isCollapsed(){return this.anchor.is(this.focus)}getNodes(){var a=this._cachedNodes;if(null!==a)return a;a=this.anchor;var b=this.focus,c=a.isBefore(b),d=c?a:b;c=c?b:a;a=d.getNode();
b=c.getNode();let e=d.offset;d=c.offset;D(a)&&(c=a.getDescendantByIndex(e),a=null!=c?c:a);D(b)&&(c=b.getDescendantByIndex(d),null!==c&&c!==a&&b.getChildAtIndex(d)===c&&(c=c.getPreviousSibling()),b=null!=c?c:b);a=a.is(b)?D(a)&&0<a.getChildrenSize()?[]:[a]:a.getNodesBetween(b);ec()||(this._cachedNodes=a);return a}setTextNodeRange(a,b,c,d){Ce(this.anchor,a.__key,b,"text");Ce(this.focus,c.__key,d,"text");this._cachedNodes=null;this.dirty=!0}getTextContent(){let a=this.getNodes();if(0===a.length)return"";
let b=a[0],c=a[a.length-1],d=this.anchor,e=this.focus,f=d.isBefore(e),[g,h]=Se(this),k="",m=!0;for(let n=0;n<a.length;n++){let p=a[n];if(D(p)&&!p.isInline())m||(k+="\n"),m=p.isEmpty()?!1:!0;else if(m=!1,B(p)){let l=p.getTextContent();if(p===b)if(p===c){if("element"!==d.type||"element"!==e.type||e.offset===d.offset)l=g<h?l.slice(g,h):l.slice(h,g)}else l=f?l.slice(g):l.slice(h);else p===c&&(l=f?l.slice(0,h):l.slice(0,g));k+=l}else!z(p)&&!Yb(p)||p===c&&this.isCollapsed()||(k+=p.getTextContent())}return k}applyDOMRange(a){let b=
F(),c=b.getEditorState()._selection;a=We(a.startContainer,a.startOffset,a.endContainer,a.endOffset,b,c);if(null!==a){var [d,e]=a;Ce(this.anchor,d.key,d.offset,d.type);Ce(this.focus,e.key,e.offset,e.type);this._cachedNodes=null}}clone(){let a=this.anchor,b=this.focus;return new Ne(new ze(a.key,a.offset,a.type),new ze(b.key,b.offset,b.type),this.format,this.style)}toggleFormat(a){this.format=Wb(this.format,a,null);this.dirty=!0}setStyle(a){this.style=a;this.dirty=!0}hasFormat(a){return 0!==(this.format&
fb[a])}insertRawText(a){a=a.split(/(\r?\n|\t)/);let b=[],c=a.length;for(let d=0;d<c;d++){let e=a[d];"\n"===e||"\r\n"===e?b.push(ge()):"\t"===e?b.push(ue()):b.push(J(e))}this.insertNodes(b)}insertText(a){var b=this.anchor,c=this.focus,d=this.isCollapsed()||b.isBefore(c),e=this.format,f=this.style;d&&"element"===b.type?Be(b,c,e,f):d||"element"!==c.type||Be(c,b,e,f);var g=this.getNodes(),h=g.length,k=d?c:b;c=(d?b:c).offset;var m=k.offset;b=g[0];B(b)||r(26);d=b.getTextContent().length;var n=b.getParentOrThrow(),
p=g[h-1];if(this.isCollapsed()&&c===d&&(b.isSegmented()||b.isToken()||!b.canInsertTextAfter()||!n.canInsertTextAfter()&&null===b.getNextSibling())){var l=b.getNextSibling();B(l)&&l.canInsertTextBefore()&&!Ob(l)||(l=J(),l.setFormat(e),n.canInsertTextAfter()?b.insertAfter(l):n.insertAfter(l));l.select(0,0);b=l;if(""!==a){this.insertText(a);return}}else if(this.isCollapsed()&&0===c&&(b.isSegmented()||b.isToken()||!b.canInsertTextBefore()||!n.canInsertTextBefore()&&null===b.getPreviousSibling())){l=b.getPreviousSibling();
if(!B(l)||Ob(l))l=J(),l.setFormat(e),n.canInsertTextBefore()?b.insertBefore(l):n.insertBefore(l);l.select();b=l;if(""!==a){this.insertText(a);return}}else if(b.isSegmented()&&c!==d)n=J(b.getTextContent()),n.setFormat(e),b.replace(n),b=n;else if(!(this.isCollapsed()||""===a||(l=p.getParent(),n.canInsertTextBefore()&&n.canInsertTextAfter()&&(!D(l)||l.canInsertTextBefore()&&l.canInsertTextAfter())))){this.insertText("");Xe(this.anchor,this.focus,null);this.insertText(a);return}if(1===h)if(b.isToken())a=
J(a),a.select(),b.replace(a);else{g=b.getFormat();h=b.getStyle();if(c===m&&(g!==e||h!==f))if(""===b.getTextContent())b.setFormat(e),b.setStyle(f);else{g=J(a);g.setFormat(e);g.setStyle(f);g.select();0===c?b.insertBefore(g,!1):([h]=b.splitText(c),h.insertAfter(g,!1));g.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length);return}b=b.spliceText(c,m-c,a,!0);""===b.getTextContent()?b.remove():"text"===this.anchor.type&&(b.isComposing()?this.anchor.offset-=a.length:(this.format=g,this.style=
h))}else{e=new Set([...b.getParentKeys(),...p.getParentKeys()]);l=D(b)?b:b.getParentOrThrow();f=D(p)?p:p.getParentOrThrow();n=p;if(!l.is(f)&&f.isInline()){do n=f,f=f.getParentOrThrow();while(f.isInline())}if("text"===k.type&&(0!==m||""===p.getTextContent())||"element"===k.type&&p.getIndexWithinParent()<m)if(B(p)&&!p.isToken()&&m!==p.getTextContentSize()){if(p.isSegmented()){var q=J(p.getTextContent());p.replace(q);p=q}K(k.getNode())||(p=p.spliceText(0,m,""));e.add(p.__key)}else k=p.getParentOrThrow(),
k.canBeEmpty()||1!==k.getChildrenSize()?p.remove():k.remove();else e.add(p.__key);k=f.getChildren();m=new Set(g);p=l.is(f);l=l.isInline()&&null===b.getNextSibling()?l:b;for(q=k.length-1;0<=q;q--){let u=k[q];if(u.is(b)||D(u)&&u.isParentOf(b))break;u.isAttached()&&(!m.has(u)||u.is(n)?p||l.insertAfter(u,!1):u.remove())}if(!p)for(k=f,m=null;null!==k;){f=k.getChildren();p=f.length;if(0===p||f[p-1].is(m))e.delete(k.__key),m=k;k=k.getParent()}b.isToken()?c===d?b.select():(a=J(a),a.select(),b.replace(a)):
(b=b.spliceText(c,d-c,a,!0),""===b.getTextContent()?b.remove():b.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length));for(a=1;a<h;a++)b=g[a],e.has(b.__key)||b.remove()}}removeText(){this.insertText("")}formatText(a){if(this.isCollapsed())this.toggleFormat(a),H(null);else{var b=this.getNodes(),c=[];for(var d of b)B(d)&&c.push(d);var e=c.length;if(0===e)this.toggleFormat(a),H(null);else{d=this.anchor;var f=this.focus,g=this.isBackward();b=g?f:d;d=g?d:f;var h=0,k=c[0];f="element"===
b.type?0:b.offset;"text"===b.type&&f===k.getTextContentSize()&&(h=1,k=c[1],f=0);if(null!=k){g=k.getFormatFlags(a,null);var m=e-1,n=c[m];e="text"===d.type?d.offset:n.getTextContentSize();if(k.is(n))f!==e&&(0===f&&e===k.getTextContentSize()?k.setFormat(g):(a=k.splitText(f,e),a=0===f?a[0]:a[1],a.setFormat(g),"text"===b.type&&b.set(a.__key,0,"text"),"text"===d.type&&d.set(a.__key,e-f,"text")),this.format=g);else{0!==f&&([,k]=k.splitText(f),f=0);k.setFormat(g);var p=n.getFormatFlags(a,g);0<e&&(e!==n.getTextContentSize()&&
([n]=n.splitText(e)),n.setFormat(p));for(h+=1;h<m;h++){let l=c[h];if(!l.isToken()){let q=l.getFormatFlags(a,p);l.setFormat(q)}}"text"===b.type&&b.set(k.__key,f,"text");"text"===d.type&&d.set(n.__key,e,"text");this.format=g|p}}}}}insertNodes(a,b){if(!this.isCollapsed()){var c=this.isBackward()?this.anchor:this.focus,d=c.getNode().getNextSibling();d=d?d.getKey():null;c=(c=c.getNode().getPreviousSibling())?c.getKey():null;this.removeText();if(this.isCollapsed()&&"element"===this.focus.type){if(this.focus.key===
d&&0===this.focus.offset){var e=J();this.focus.getNode().insertBefore(e)}else this.focus.key===c&&this.focus.offset===this.focus.getNode().getChildrenSize()&&(e=J(),this.focus.getNode().insertAfter(e));e&&(this.focus.set(e.__key,0,"text"),this.anchor.set(e.__key,0,"text"))}}e=this.anchor;c=e.offset;var f=e.getNode();d=f;"element"===e.type&&(e=e.getNode(),d=e.getChildAtIndex(c-1),d=null===d?e:d);e=[];var g=f.getNextSiblings(),h=yc(f)?null:f.getTopLevelElementOrThrow();if(B(f))if(d=f.getTextContent().length,
0===c&&0!==d)d=f.getPreviousSibling(),d=null!==d?d:f.getParentOrThrow(),e.push(f);else if(c===d)d=f;else{if(f.isToken())return!1;[d,f]=f.splitText(c);e.push(f)}f=d;e.push(...g);g=a[0];var k=!1,m=null;for(let q=0;q<a.length;q++){var n=a[q];if(yc(d)||z(d)||!D(n)||n.isInline())k&&!D(n)&&!z(n)&&yc(d.getParent())&&r(28);else{if(n.is(g)){if(D(d)&&d.isEmpty()&&d.canReplaceWith(n)){d.replace(n);d=n;k=!0;continue}k=n.getFirstDescendant();if(Xb(k)){for(var p=k.getParentOrThrow();p.isInline();)p=p.getParentOrThrow();
m=p.getChildren();k=m.length;if(D(d)){var l=d.getFirstChild();for(let u=0;u<k;u++){let x=m[u];null===l?d.append(x):l.insertAfter(x);l=x}}else{for(l=k-1;0<=l;l--)d.insertAfter(m[l]);d=d.getParentOrThrow()}m=m[k-1];p.remove();k=!0;if(p.is(n))continue}}B(d)&&(null===h&&r(27),d=h)}k=!1;if(D(d)&&!d.isInline())if(m=n,z(n)&&!n.isInline())d=1===a.length&&d.canBeEmpty()&&d.isEmpty()?d.insertBefore(n,!1):d.insertAfter(n,!1);else if(D(n)){if(n.canBeEmpty()||!n.isEmpty())K(d)?(p=d.getChildAtIndex(c),null!==p?
p.insertBefore(n):d.append(n),d=n):n.isInline()?(d.append(n),d=n):d=d.insertAfter(n,!1)}else p=d.getFirstChild(),null!==p?p.insertBefore(n):d.append(n),d=n;else!D(n)||D(n)&&n.isInline()||z(d)&&!d.isInline()?(m=n,C(this)&&z(n)&&(D(d)||B(d))&&!n.isInline()?(B(d)?(p=d.getParentOrThrow(),[d]=d.splitText(c),d=d.getIndexWithinParent()+1):(p=d,d=c),[,d]=Ec(p,d),d=d.insertBefore(n)):d=d.insertAfter(n,!1)):(n=d.getParentOrThrow(),Yb(d)&&d.remove(),d=n,q--)}b&&(B(f)?f.select():(a=d.getPreviousSibling(),B(a)?
a.select():(a=d.getIndexWithinParent(),d.getParentOrThrow().select(a,a))));if(D(d)){if(a=B(m)?m:D(m)&&m.isInline()?m.getLastDescendant():d.getLastDescendant(),b||(null===a?d.select():B(a)?""===a.getTextContent()?a.selectPrevious():a.select():a.selectNext()),0!==e.length)for(b=d,a=e.length-1;0<=a;a--)c=e[a],h=c.getParentOrThrow(),!D(d)||Ye(c)||z(c)&&(!c.isInline()||c.isIsolated())?D(d)||Ye(c)?D(c)&&!c.canInsertAfter(d)?(f=h.constructor.clone(h),D(f)||r(29),f.append(c),d.insertAfter(f)):d.insertAfter(c):
(d.insertBefore(c),d=c):(b===d?d.append(c):d.insertBefore(c),d=c),h.isEmpty()&&!h.canBeEmpty()&&h.remove()}else b||(B(d)?d.select():(b=d.getParentOrThrow(),a=d.getIndexWithinParent()+1,b.select(a,a)));return!0}insertParagraph(){this.isCollapsed()||this.removeText();var a=this.anchor,b=a.offset,c=[];if("text"===a.type){var d=a.getNode();var e=d.getNextSiblings().reverse();var f=d.getParentOrThrow();var g=f.isInline(),h=g?f.getTextContentSize():d.getTextContentSize();0===b?e.push(d):(g&&(c=f.getNextSiblings()),
b===h||g&&b===d.getTextContentSize()||([,d]=d.splitText(b),e.push(d)))}else{f=a.getNode();if(yc(f)){e=de();c=f.getChildAtIndex(b);e.select();null!==c?c.insertBefore(e,!1):f.append(e);return}e=f.getChildren().slice(b).reverse()}d=e.length;if(0===b&&0<d&&f.isInline()){if(c=f.getParentOrThrow(),e=c.insertNewAfter(this,!1),D(e))for(c=c.getChildren(),f=0;f<c.length;f++)e.append(c[f])}else if(g=f.insertNewAfter(this,!1),null===g)this.insertLineBreak();else if(D(g))if(h=f.getFirstChild(),0===b&&(f.is(a.getNode())||
h&&h.is(a.getNode()))&&0<d)f.insertBefore(g);else{f=null;b=c.length;a=g.getParentOrThrow();if(0<b)for(h=0;h<b;h++)a.append(c[h]);if(0!==d)for(c=0;c<d;c++)b=e[c],null===f?g.append(b):f.insertBefore(b),f=b;g.canBeEmpty()||0!==g.getChildrenSize()?g.selectStart():(g.selectPrevious(),g.remove())}}insertLineBreak(a){let b=ge();var c=this.anchor;"element"===c.type&&(c=c.getNode(),K(c)&&this.insertParagraph());a?this.insertNodes([b],!0):this.insertNodes([b])&&b.selectNext(0,0)}getCharacterOffsets(){return Se(this)}extract(){var a=
this.getNodes(),b=a.length,c=b-1,d=this.anchor;let e=this.focus;var f=a[0];let g=a[c],[h,k]=Se(this);if(0===b)return[];if(1===b)return B(f)&&!this.isCollapsed()?(a=h>k?k:h,c=f.splitText(a,h>k?h:k),a=0===a?c[0]:c[1],null!=a?[a]:[]):[f];b=d.isBefore(e);B(f)&&(d=b?h:k,d===f.getTextContentSize()?a.shift():0!==d&&([,f]=f.splitText(d),a[0]=f));B(g)&&(f=g.getTextContent().length,b=b?k:h,0===b?a.pop():b!==f&&([g]=g.splitText(b),a[c]=g));return a}modify(a,b,c){var d=this.focus,e=this.anchor,f="move"===a,g=
tc(d,b);if(z(g)&&!g.isIsolated())f&&g.isKeyboardSelectable()?(b=Ze(),b.add(g.__key),yb(b)):(a=b?g.getPreviousSibling():g.getNextSibling(),B(a)?(g=a.__key,b=b?a.getTextContent().length:0,d.set(g,b,"text"),f&&e.set(g,b,"text")):(c=g.getParentOrThrow(),D(a)?(c=a.__key,g=b?a.getChildrenSize():0):(g=g.getIndexWithinParent(),c=c.__key,b||g++),d.set(c,g,"element"),f&&e.set(c,g,"element")));else if(e=F(),d=vb(e._window)){var h=e._blockCursorElement,k=e._rootElement;null===k||null===h||!D(g)||g.isInline()||
g.canBeEmpty()||Dc(h,e,k);d.modify(a,b?"backward":"forward",c);if(0<d.rangeCount&&(g=d.getRangeAt(0),e=this.anchor.getNode(),e=K(e)?e:xc(e),this.applyDOMRange(g),this.dirty=!0,!f)){f=this.getNodes();a=[];c=!1;for(h=0;h<f.length;h++)k=f[h],wc(k,e)?a.push(k):c=!0;c&&0<a.length&&(b?(b=a[0],D(b)?b.selectStart():b.getParentOrThrow().selectStart()):(b=a[a.length-1],D(b)?b.selectEnd():b.getParentOrThrow().selectEnd()));if(d.anchorNode!==g.startContainer||d.anchorOffset!==g.startOffset)b=this.focus,f=this.anchor,
d=f.key,g=f.offset,e=f.type,Ce(f,b.key,b.offset,b.type),Ce(b,d,g,e),this._cachedNodes=null}}}deleteCharacter(a){let b=this.isCollapsed();if(this.isCollapsed()){var c=this.anchor,d=this.focus,e=c.getNode();if(!a&&("element"===c.type&&D(e)&&c.offset===e.getChildrenSize()||"text"===c.type&&c.offset===e.getTextContentSize())){var f=e.getParent();f=e.getNextSibling()||(null===f?null:f.getNextSibling());if(D(f)&&f.isShadowRoot())return}f=tc(d,a);if(z(f)&&!f.isIsolated()){f.isKeyboardSelectable()&&D(e)&&
0===e.getChildrenSize()?(e.remove(),a=Ze(),a.add(f.__key),yb(a)):(f.remove(),F().dispatchCommand(aa,void 0));return}if(!a&&D(f)&&D(e)&&e.isEmpty()){e.remove();f.selectStart();return}this.modify("extend",a,"character");if(!this.isCollapsed()){f="text"===d.type?d.getNode():null;e="text"===c.type?c.getNode():null;if(null!==f&&f.isSegmented()){if(c=d.offset,d=f.getTextContentSize(),f.is(e)||a&&c!==d||!a&&0!==c){$e(f,a,c);return}}else if(null!==e&&e.isSegmented()&&(c=c.offset,d=e.getTextContentSize(),
e.is(f)||a&&0!==c||!a&&c!==d)){$e(e,a,c);return}e=this.anchor;f=this.focus;c=e.getNode();d=f.getNode();if(c===d&&"text"===e.type&&"text"===f.type){var g=e.offset,h=f.offset;let k=g<h;d=k?g:h;h=k?h:g;g=h-1;d!==g&&(c=c.getTextContent().slice(d,h),kc(c)||(a?f.offset=g:e.offset=g))}}else if(a&&0===c.offset&&("element"===c.type?c.getNode():c.getNode().getParentOrThrow()).collapseAtStart(this))return}this.removeText();a&&!b&&this.isCollapsed()&&"element"===this.anchor.type&&0===this.anchor.offset&&(a=this.anchor.getNode(),
a.isEmpty()&&K(a.getParent())&&0===a.getIndexWithinParent()&&a.collapseAtStart(this))}deleteLine(a){this.isCollapsed()&&("text"===this.anchor.type&&this.modify("extend",a,"lineboundary"),0===(a?this.focus:this.anchor).offset&&this.modify("extend",a,"character"));this.removeText()}deleteWord(a){this.isCollapsed()&&this.modify("extend",a,"word");this.removeText()}}function Ud(a){return a instanceof De}
function af(a){let b=a.offset;if("text"===a.type)return b;a=a.getNode();return b===a.getChildrenSize()?a.getTextContent().length:0}function Se(a){let b=a.anchor;a=a.focus;return"element"===b.type&&"element"===a.type&&b.key===a.key&&b.offset===a.offset?[0,0]:[af(b),af(a)]}
function $e(a,b,c){let d=a.getTextContent().split(/(?=\s)/g),e=d.length,f=0,g=0;for(let h=0;h<e;h++){let k=d[h],m=h===e-1;g=f;f+=k.length;if(b&&f===c||f>c||m){d.splice(h,1);m&&(g=void 0);break}}b=d.join("").trim();""===b?a.remove():(a.setTextContent(b),a.select(g,g))}
function bf(a,b,c,d){var e=b;if(1===a.nodeType){let h=!1;var f=a.childNodes,g=f.length;e===g&&(h=!0,e=g-1);let k=f[e];g=!1;k===d._blockCursorElement?(k=f[e+1],g=!0):null!==d._blockCursorElement&&e--;d=jc(k);if(B(d))e=h?d.getTextContentSize():0;else{f=jc(a);if(null===f)return null;if(D(f)){a=f.getChildAtIndex(e);if(b=D(a))b=a.getParent(),b=null===c||null===b||!b.canBeEmpty()||b!==c.getNode();b&&(c=h?a.getLastDescendant():a.getFirstDescendant(),null===c?(f=a,e=0):(a=c,f=D(a)?a:a.getParentOrThrow()));
B(a)?(d=a,f=null,e=h?a.getTextContentSize():0):a!==f&&h&&!g&&e++}else e=f.getIndexWithinParent(),e=0===b&&z(f)&&jc(a)===f?e:e+1,f=f.getParentOrThrow();if(D(f))return new ze(f.__key,e,"element")}}else d=jc(a);return B(d)?new ze(d.__key,e,"text"):null}
function cf(a,b,c){var d=a.offset,e=a.getNode();0===d?(d=e.getPreviousSibling(),e=e.getParent(),b)?(c||!b)&&null===d&&D(e)&&e.isInline()&&(b=e.getPreviousSibling(),B(b)&&(a.key=b.__key,a.offset=b.getTextContent().length)):D(d)&&!c&&d.isInline()?(a.key=d.__key,a.offset=d.getChildrenSize(),a.type="element"):B(d)&&(a.key=d.__key,a.offset=d.getTextContent().length):d===e.getTextContent().length&&(d=e.getNextSibling(),e=e.getParent(),b&&D(d)&&d.isInline()?(a.key=d.__key,a.offset=0,a.type="element"):(c||
b)&&null===d&&D(e)&&e.isInline()&&!e.canInsertTextAfter()&&(b=e.getNextSibling(),B(b)&&(a.key=b.__key,a.offset=0)))}function Xe(a,b,c){if("text"===a.type&&"text"===b.type){var d=a.isBefore(b);let e=a.is(b);cf(a,d,e);cf(b,!d,e);e&&(b.key=a.key,b.offset=a.offset,b.type=a.type);d=F();d.isComposing()&&d._compositionKey!==a.key&&C(c)&&(d=c.anchor,c=c.focus,Ce(a,d.key,d.offset,d.type),Ce(b,c.key,c.offset,c.type))}}
function We(a,b,c,d,e,f){if(null===a||null===c||!Lb(e,a,c))return null;b=bf(a,b,C(f)?f.anchor:null,e);if(null===b)return null;d=bf(c,d,C(f)?f.focus:null,e);if(null===d||"element"===b.type&&"element"===d.type&&(a=jc(a),c=jc(c),z(a)&&z(c)))return null;Xe(b,d,f);return[b,d]}function Ye(a){return D(a)&&!a.isInline()}function re(a,b,c,d,e,f){let g=ac();a=new Ne(new ze(a,b,e),new ze(c,d,f),0,"");a.dirty=!0;return g._selection=a}function Ze(){return new De(new Set)}
function df(a){let b=a.getEditorState()._selection,c=vb(a._window);return Ud(b)||Re(b)?b.clone():Qd(b,c,a)}
function Qd(a,b,c){var d=c._window;if(null===d)return null;var e=d.event,f=e?e.type:void 0;d="selectionchange"===f;e=!ob&&(d||"beforeinput"===f||"compositionstart"===f||"compositionend"===f||"click"===f&&e&&3===e.detail||"drop"===f||void 0===f);let g;if(!C(a)||e){if(null===b)return null;e=b.anchorNode;f=b.focusNode;g=b.anchorOffset;b=b.focusOffset;if(d&&C(a)&&!Lb(c,e,f))return a.clone()}else return a.clone();c=We(e,g,f,b,c,a);if(null===c)return null;let [h,k]=c;return new Ne(h,k,C(a)?a.format:0,C(a)?
a.style:"")}function v(){return ac()._selection}function oc(){return F()._editorState._selection}
function ae(a,b,c,d=1){var e=a.anchor,f=a.focus,g=e.getNode(),h=f.getNode();if(b.is(g)||b.is(h)){g=b.__key;if(a.isCollapsed()){if(b=e.offset,c<=b&&0<d||c<b&&0>d)c=Math.max(0,b+d),e.set(g,c,"element"),f.set(g,c,"element"),ef(a)}else{let m=a.isBackward();h=m?f:e;var k=h.getNode();e=m?e:f;f=e.getNode();b.is(k)&&(k=h.offset,(c<=k&&0<d||c<k&&0>d)&&h.set(g,Math.max(0,k+d),"element"));b.is(f)&&(b=e.offset,(c<=b&&0<d||c<b&&0>d)&&e.set(g,Math.max(0,b+d),"element"))}ef(a)}}
function ef(a){var b=a.anchor,c=b.offset;let d=a.focus;var e=d.offset,f=b.getNode(),g=d.getNode();if(a.isCollapsed())D(f)&&(g=f.getChildrenSize(),g=(e=c>=g)?f.getChildAtIndex(g-1):f.getChildAtIndex(c),B(g)&&(c=0,e&&(c=g.getTextContentSize()),b.set(g.__key,c,"text"),d.set(g.__key,c,"text")));else{if(D(f)){let h=f.getChildrenSize();c=(a=c>=h)?f.getChildAtIndex(h-1):f.getChildAtIndex(c);B(c)&&(f=0,a&&(f=c.getTextContentSize()),b.set(c.__key,f,"text"))}D(g)&&(c=g.getChildrenSize(),e=(b=e>=c)?g.getChildAtIndex(c-
1):g.getChildAtIndex(e),B(e)&&(g=0,b&&(g=e.getTextContentSize()),d.set(e.__key,g,"text")))}}function ff(a,b){b=b.getEditorState()._selection;a=a._selection;if(C(a)){var c=a.anchor;let d=a.focus,e;"text"===c.type&&(e=c.getNode(),e.selectionTransform(b,a));"text"===d.type&&(c=d.getNode(),e!==c&&c.selectionTransform(b,a))}}
function $d(a,b,c,d,e){let f=null,g=0,h=null;null!==d?(f=d.__key,B(d)?(g=d.getTextContentSize(),h="text"):D(d)&&(g=d.getChildrenSize(),h="element")):null!==e&&(f=e.__key,B(e)?h="text":D(e)&&(h="element"));null!==f&&null!==h?a.set(f,g,h):(g=b.getIndexWithinParent(),-1===g&&(g=c.getChildrenSize()),a.set(c.__key,g,"element"))}function se(a,b,c,d,e){"text"===a.type?(a.key=c,b||(a.offset+=e)):a.offset>d.getIndexWithinParent()&&--a.offset}
function Ve(a,b,c){let d=[],e=null,f=null;a=a.getChildren();for(let n=0;n<a.length;n++){var g=a[n];Te(g)||r(108);var h=g.getChildren();g=0;for(let p of h){for(P(p)||r(109);void 0!==d[n]&&void 0!==d[n][g];)g++;h=n;var k=g,m=p;let l={cell:m,startColumn:k,startRow:h},q=m.__rowSpan,u=m.__colSpan;for(let x=0;x<q;x++){void 0===d[h+x]&&(d[h+x]=[]);for(let y=0;y<u;y++)d[h+x][k+y]=l}b.is(m)&&(e=l);c.is(m)&&(f=l);g+=p.__colSpan}}null===e&&r(110);null===f&&r(111);return[d,e,f]}
function Pe(a){a instanceof gf||(a instanceof be?(a=Fc(a,P),P(a)||r(114)):(a=Fc(a.getNode(),P),P(a)||r(114)));let b=a.getParent();Te(b)||r(115);let c=b.getParent();Ue(c)||r(116);return[a,b,c]}let S=null,T=null,V=!1,hf=!1,$b=0,jf={characterData:!0,childList:!0,subtree:!0};function ec(){return V||null!==S&&S._readOnly}function G(){V&&r(13)}function ac(){null===S&&r(15);return S}function F(){null===T&&r(16);return T}
function kf(a,b,c){var d=b.__type;let e=a._nodes.get(d);void 0===e&&r(30,d);a=c.get(d);void 0===a&&(a=Array.from(e.transforms),c.set(d,a));c=a.length;for(d=0;d<c&&(a[d](b),b.isAttached());d++);}function lf(a,b){b=b._dirtyLeaves;a=a._nodeMap;for(let c of b)b=a.get(c),B(b)&&b.isAttached()&&b.isSimpleText()&&!b.isUnmergeable()&&Fb(b)}
function mf(a,b){let c=b._dirtyLeaves,d=b._dirtyElements;a=a._nodeMap;let e=dc(),f=new Map;var g=c;let h=g.size;for(var k=d,m=k.size;0<h||0<m;){if(0<h){b._dirtyLeaves=new Set;for(let n of g)g=a.get(n),B(g)&&g.isAttached()&&g.isSimpleText()&&!g.isUnmergeable()&&Fb(g),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&kf(b,g,f),c.add(n);g=b._dirtyLeaves;h=g.size;if(0<h){$b++;continue}}b._dirtyLeaves=new Set;b._dirtyElements=new Map;for(let n of k)if(k=n[0],m=n[1],"root"===k||m)g=a.get(k),void 0!==
g&&void 0!==g&&g.__key!==e&&g.isAttached()&&kf(b,g,f),d.set(k,m);g=b._dirtyLeaves;h=g.size;k=b._dirtyElements;m=k.size;$b++}b._dirtyLeaves=c;b._dirtyElements=d}function nf(a,b){var c=a.type,d=b.get(c);void 0===d&&r(17,c);c=d.klass;a.type!==c.getType()&&r(18,c.name);c=c.importJSON(a);a=a.children;if(D(c)&&Array.isArray(a))for(d=0;d<a.length;d++){let e=nf(a[d],b);c.append(e)}return c}function of(a,b){let c=S,d=V,e=T;S=a;V=!0;T=null;try{return b()}finally{S=c,V=d,T=e}}
function pf(a,b){let c=a._pendingEditorState,d=a._rootElement,e=a._headless||null===d;if(null!==c){var f=a._editorState,g=f._selection,h=c._selection,k=0!==a._dirtyType,m=S,n=V,p=T,l=a._updating,q=a._observer,u=null;a._pendingEditorState=null;a._editorState=c;if(!e&&k&&null!==q){T=a;S=c;V=!1;a._updating=!0;try{let E=a._dirtyType,Q=a._dirtyElements,R=a._dirtyLeaves;q.disconnect();var x=E,y=Q,A=R;M=Kc=L="";Nc=2===x;Qc=null;N=a;Lc=a._config;Mc=a._nodes;Pc=N._listeners.mutation;Rc=y;Sc=A;Tc=f._nodeMap;
Uc=c._nodeMap;Oc=c._readOnly;Vc=new Map(a._keyToDOMMap);let ia=new Map;ed=ia;sd("root",null);ed=Vc=Lc=Uc=Tc=Sc=Rc=Mc=N=void 0;u=ia}catch(E){E instanceof Error&&a._onError(E);if(hf)throw E;qf(a,null,d,c);Bb(a);a._dirtyType=2;hf=!0;pf(a,f);hf=!1;return}finally{q.observe(d,jf),a._updating=l,S=m,V=n,T=p}}c._readOnly||(c._readOnly=!0);var Z=a._dirtyLeaves,ca=a._dirtyElements,Va=a._normalizedNodes,la=a._updateTags,Wc=a._deferred;k&&(a._dirtyType=0,a._cloneNotNeeded.clear(),a._dirtyLeaves=new Set,a._dirtyElements=
new Map,a._normalizedNodes=new Set,a._updateTags=new Set);var Ee=a._decorators,Pb=a._pendingDecorators||Ee,Ef=c._nodeMap,Xc;for(Xc in Pb)Ef.has(Xc)||(Pb===Ee&&(Pb=fc(a)),delete Pb[Xc]);var ja=e?null:vb(a._window);if(a._editable&&null!==ja&&(k||null===h||h.dirty)){T=a;S=c;try{null!==q&&q.disconnect();if(k||null===h||h.dirty){let E=a._blockCursorElement;null!==E&&Dc(E,a,d);a:{let Q=ja.anchorNode,R=ja.focusNode,ia=ja.anchorOffset,lb=ja.focusOffset,W=document.activeElement;if(!(la.has("collaboration")&&
W!==d||null!==W&&Kb(W)))if(C(h)){var mb=h.anchor,Yc=h.focus,Fe=mb.key,Ff=Yc.key,Ge=vc(a,Fe),He=vc(a,Ff),Qb=mb.offset,Ie=Yc.offset,Zc=h.format,$c=h.style,Je=h.isCollapsed(),nb=Ge,Rb=He,ad=!1;if("text"===mb.type){nb=Vb(Ge);let X=mb.getNode();ad=X.getFormat()!==Zc||X.getStyle()!==$c}else C(g)&&"text"===g.anchor.type&&(ad=!0);"text"===Yc.type&&(Rb=Vb(He));if(null!==nb&&null!==Rb){if(Je&&(null===g||ad||C(g)&&(g.format!==Zc||g.style!==$c))){var Gf=performance.now();Md=[Zc,$c,Qb,Fe,Gf]}if(ia===Qb&&lb===
Ie&&Q===nb&&R===Rb&&("Range"!==ja.type||!Je)&&(null!==W&&d.contains(W)||d.focus({preventScroll:!0}),"element"!==mb.type))break a;try{ja.setBaseAndExtent(nb,Qb,Rb,Ie)}catch(X){}if(!la.has("skip-scroll-into-view")&&h.isCollapsed()&&null!==d&&d===document.activeElement){let X=h instanceof Ne&&"element"===h.anchor.type?nb.childNodes[Qb]||null:0<ja.rangeCount?ja.getRangeAt(0):null;if(null!==X){let Y;if(X instanceof Text){let U=document.createRange();U.selectNode(X);Y=U.getBoundingClientRect()}else Y=X.getBoundingClientRect();
let wa=d.ownerDocument,Da=wa.defaultView;if(null!==Da)for(var {top:bd,bottom:cd}=Y,Sb,Tb,oa=d;null!==oa;){let U=oa===wa.body;if(U)Sb=0,Tb=Cb(a).innerHeight;else{let Ub=oa.getBoundingClientRect();Sb=Ub.top;Tb=Ub.bottom}let Ea=0;bd<Sb?Ea=-(Sb-bd):cd>Tb&&(Ea=cd-Tb);if(0!==Ea)if(U)Da.scrollBy(0,Ea);else{let Ub=oa.scrollTop;oa.scrollTop+=Ea;let Ke=oa.scrollTop-Ub;bd-=Ke;cd-=Ke}if(U)break;oa=Nb(oa)}}}Id=!0}}else null!==g&&Lb(a,Q,R)&&ja.removeAllRanges()}}a:{let E=a._blockCursorElement;if(C(h)&&h.isCollapsed()&&
"element"===h.anchor.type&&d.contains(document.activeElement)){let Q=h.anchor,R=Q.getNode(),ia=Q.offset,lb=R.getChildrenSize(),W=!1,X=null;if(ia===lb){let Y=R.getChildAtIndex(ia-1);Cc(Y)&&(W=!0)}else{let Y=R.getChildAtIndex(ia);if(Cc(Y)){let wa=Y.getPreviousSibling();if(null===wa||Cc(wa))W=!0,X=a.getElementByKey(Y.__key)}}if(W){let Y=a.getElementByKey(R.__key);if(null===E){let wa=a._config.theme,Da=document.createElement("div");Da.contentEditable="false";Da.setAttribute("data-lexical-cursor","true");
let U=wa.blockCursor;if(void 0!==U){if("string"===typeof U){let Ea=U.split(" ");U=wa.blockCursor=Ea}void 0!==U&&Da.classList.add(...U)}a._blockCursorElement=E=Da}d.style.caretColor="transparent";null===X?Y.appendChild(E):Y.insertBefore(E,X);break a}}null!==E&&Dc(E,a,d)}null!==q&&q.observe(d,jf)}finally{T=p,S=m}}if(null!==u){var Hf=u;let E=Array.from(a._listeners.mutation),Q=E.length;for(let R=0;R<Q;R++){let [ia,lb]=E[R],W=Hf.get(lb);void 0!==W&&ia(W,{dirtyLeaves:Z,prevEditorState:f,updateTags:la})}}C(h)||
null===h||null!==g&&g.is(h)||a.dispatchCommand(aa,void 0);var dd=a._pendingDecorators;null!==dd&&(a._decorators=dd,a._pendingDecorators=null,rf("decorator",a,!0,dd));var If=gc(b||f),Le=gc(c);If!==Le&&rf("textcontent",a,!0,Le);rf("update",a,!0,{dirtyElements:ca,dirtyLeaves:Z,editorState:c,normalizedNodes:Va,prevEditorState:b||f,tags:la});a._deferred=[];if(0!==Wc.length){let E=a._updating;a._updating=!0;try{for(let Q=0;Q<Wc.length;Q++)Wc[Q]()}finally{a._updating=E}}var Me=a._updates;if(0!==Me.length){let E=
Me.shift();if(E){let [Q,R]=E;sf(a,Q,R)}}}}function rf(a,b,c,...d){let e=b._updating;b._updating=c;try{let f=Array.from(b._listeners[a]);for(a=0;a<f.length;a++)f[a].apply(null,d)}finally{b._updating=e}}
function O(a,b,c){if(!1===a._updating||T!==a){let f=!1;a.update(()=>{f=O(a,b,c)});return f}let d=lc(a);for(let f=4;0<=f;f--)for(let g=0;g<d.length;g++){var e=d[g]._commands.get(b);if(void 0!==e&&(e=e[f],void 0!==e)){e=Array.from(e);let h=e.length;for(let k=0;k<h;k++)if(!0===e[k](c,a))return!0}}return!1}
function tf(a,b){let c=a._updates;for(b=b||!1;0!==c.length;){var d=c.shift();if(d){let [e,f]=d,g;void 0!==f&&(d=f.onUpdate,g=f.tag,f.skipTransforms&&(b=!0),d&&a._deferred.push(d),g&&a._updateTags.add(g));e()}}return b}
function sf(a,b,c){let d=a._updateTags;var e,f=e=!1;if(void 0!==c){var g=c.onUpdate;e=c.tag;null!=e&&d.add(e);e=c.skipTransforms||!1;f=c.discrete||!1}g&&a._deferred.push(g);c=a._editorState;g=a._pendingEditorState;let h=!1;if(null===g||g._readOnly)g=a._pendingEditorState=new uf(new Map((g||c)._nodeMap)),h=!0;g._flushSync=f;f=S;let k=V,m=T,n=a._updating;S=g;V=!1;a._updating=!0;T=a;try{h&&(a._headless?null!=c._selection&&(g._selection=c._selection.clone()):g._selection=df(a));let p=a._compositionKey;
b();e=tf(a,e);ff(g,a);0!==a._dirtyType&&(e?lf(g,a):mf(g,a),tf(a),Jc(c,g,a._dirtyLeaves,a._dirtyElements));p!==a._compositionKey&&(g._flushSync=!0);let l=g._selection;if(C(l)){let q=g._nodeMap,u=l.focus.key;void 0!==q.get(l.anchor.key)&&void 0!==q.get(u)||r(19)}else Ud(l)&&0===l._nodes.size&&(g._selection=null)}catch(p){p instanceof Error&&a._onError(p);a._pendingEditorState=c;a._dirtyType=2;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();pf(a);return}finally{S=f,V=k,T=m,
a._updating=n,$b=0}0!==a._dirtyType||vf(g,a)?g._flushSync?(g._flushSync=!1,pf(a)):h&&Jb(()=>{pf(a)}):(g._flushSync=!1,h&&(d.clear(),a._deferred=[],a._pendingEditorState=null))}function w(a,b,c){a._updating?a._updates.push([b,c]):sf(a,b,c)}class wf extends be{constructor(a){super(a)}decorate(){r(47)}isIsolated(){return!1}isInline(){return!0}isKeyboardSelectable(){return!0}}function z(a){return a instanceof wf}
class xf extends be{constructor(a){super(a);this.__last=this.__first=null;this.__indent=this.__format=this.__size=0;this.__dir=null}getFormat(){return this.getLatest().__format}getFormatType(){let a=this.getFormat();return ib[a]||""}getIndent(){return this.getLatest().__indent}getChildren(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getChildrenKeys(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b.__key),b=b.getNextSibling();return a}getChildrenSize(){return this.getLatest().__size}isEmpty(){return 0===
this.getChildrenSize()}isDirty(){let a=F()._dirtyElements;return null!==a&&a.has(this.__key)}isLastChild(){let a=this.getLatest(),b=this.getParentOrThrow().getLastChild();return null!==b&&b.is(a)}getAllTextNodes(){let a=[],b=this.getFirstChild();for(;null!==b;){B(b)&&a.push(b);if(D(b)){let c=b.getAllTextNodes();a.push(...c)}b=b.getNextSibling()}return a}getFirstDescendant(){let a=this.getFirstChild();for(;null!==a;){if(D(a)){let b=a.getFirstChild();if(null!==b){a=b;continue}}break}return a}getLastDescendant(){let a=
this.getLastChild();for(;null!==a;){if(D(a)){let b=a.getLastChild();if(null!==b){a=b;continue}}break}return a}getDescendantByIndex(a){let b=this.getChildren(),c=b.length;if(a>=c)return a=b[c-1],D(a)&&a.getLastDescendant()||a||null;a=b[a];return D(a)&&a.getFirstDescendant()||a||null}getFirstChild(){let a=this.getLatest().__first;return null===a?null:I(a)}getFirstChildOrThrow(){let a=this.getFirstChild();null===a&&r(45,this.__key);return a}getLastChild(){let a=this.getLatest().__last;return null===
a?null:I(a)}getLastChildOrThrow(){let a=this.getLastChild();null===a&&r(96,this.__key);return a}getChildAtIndex(a){var b=this.getChildrenSize();let c;if(a<b/2){c=this.getFirstChild();for(b=0;null!==c&&b<=a;){if(b===a)return c;c=c.getNextSibling();b++}return null}c=this.getLastChild();for(--b;null!==c&&b>=a;){if(b===a)return c;c=c.getPreviousSibling();b--}return null}getTextContent(){let a="",b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContent();D(e)&&d!==c-1&&!e.isInline()&&
(a+="\n\n")}return a}getTextContentSize(){let a=0,b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContentSize();D(e)&&d!==c-1&&!e.isInline()&&(a+=2)}return a}getDirection(){return this.getLatest().__dir}hasFormat(a){return""!==a?(a=hb[a],0!==(this.getFormat()&a)):!1}select(a,b){G();let c=v(),d=a,e=b;var f=this.getChildrenSize();if(!this.canBeEmpty())if(0===a&&0===b){if(a=this.getFirstChild(),B(a)||D(a))return a.select(0,0)}else if(!(void 0!==a&&a!==f||void 0!==b&&b!==f)&&
(a=this.getLastChild(),B(a)||D(a)))return a.select();void 0===d&&(d=f);void 0===e&&(e=f);f=this.__key;if(C(c))c.anchor.set(f,d,"element"),c.focus.set(f,e,"element"),c.dirty=!0;else return re(f,d,f,e,"element","element");return c}selectStart(){let a=this.getFirstDescendant();return D(a)||B(a)?a.select(0,0):null!==a?a.selectPrevious():this.select(0,0)}selectEnd(){let a=this.getLastDescendant();return D(a)||B(a)?a.select():null!==a?a.selectNext():this.select()}clear(){let a=this.getWritable();this.getChildren().forEach(b=>
b.remove());return a}append(...a){return this.splice(this.getChildrenSize(),0,a)}setDirection(a){let b=this.getWritable();b.__dir=a;return b}setFormat(a){this.getWritable().__format=""!==a?hb[a]:0;return this}setIndent(a){this.getWritable().__indent=a;return this}splice(a,b,c){let d=c.length,e=this.getChildrenSize(),f=this.getWritable(),g=f.__key;var h=[],k=[];let m=this.getChildAtIndex(a+b),n=null,p=e-b+d;if(0!==a)if(a===e)n=this.getLastChild();else{var l=this.getChildAtIndex(a);null!==l&&(n=l.getPreviousSibling())}if(0<
b){var q=null===n?this.getFirstChild():n.getNextSibling();for(l=0;l<b;l++){null===q&&r(100);var u=q.getNextSibling(),x=q.__key;q=q.getWritable();bc(q);k.push(x);q=u}}l=n;for(u=0;u<d;u++){x=c[u];null!==l&&x.is(l)&&(n=l=l.getPreviousSibling());q=x.getWritable();q.__parent===g&&p--;bc(q);let y=x.__key;null===l?(f.__first=y,q.__prev=null):(l=l.getWritable(),l.__next=y,q.__prev=l.__key);x.__key===g&&r(76);q.__parent=g;h.push(y);l=x}a+b===e?null!==l&&(l.getWritable().__next=null,f.__last=l.__key):null!==
m&&(a=m.getWritable(),null!==l?(b=l.getWritable(),a.__prev=l.__key,b.__next=m.__key):a.__prev=null);f.__size=p;if(k.length&&(a=v(),C(a))){k=new Set(k);h=new Set(h);let {anchor:y,focus:A}=a;yf(y,k,h)&&$d(y,y.getNode(),this,n,m);yf(A,k,h)&&$d(A,A.getNode(),this,n,m);0!==p||this.canBeEmpty()||yc(this)||this.remove()}return f}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"element",version:1}}insertNewAfter(){return null}canIndent(){return!0}collapseAtStart(){return!1}excludeFromCopy(){return!1}canExtractContents(){return!0}canReplaceWith(){return!0}canInsertAfter(){return!0}canBeEmpty(){return!0}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}isInline(){return!1}isShadowRoot(){return!1}canMergeWith(){return!1}extractWithChild(){return!1}}
function D(a){return a instanceof xf}function yf(a,b,c){for(a=a.getNode();a;){let d=a.__key;if(b.has(d)&&!c.has(d))return!0;a=a.getParent()}return!1}
class zf extends xf{static getType(){return"root"}static clone(){return new zf}constructor(){super("root");this.__cachedText=null}getTopLevelElementOrThrow(){r(51)}getTextContent(){let a=this.__cachedText;return!ec()&&0!==F()._dirtyType||null===a?super.getTextContent():a}remove(){r(52)}replace(){r(53)}insertBefore(){r(54)}insertAfter(){r(55)}updateDOM(){return!1}append(...a){for(let b=0;b<a.length;b++){let c=a[b];D(c)||z(c)||r(56)}return super.append(...a)}static importJSON(a){let b=hc();b.setFormat(a.format);
b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"root",version:1}}collapseAtStart(){return!0}}function K(a){return a instanceof zf}function vf(a,b){b=b.getEditorState()._selection;a=a._selection;if(null!==a){if(a.dirty||!a.is(b))return!0}else if(null!==b)return!0;return!1}function Af(){return new uf(new Map([["root",new zf]]))}
function Bf(a,b){let c=a.exportJSON();if(b)for(var d in c)b.includes(d)||delete c[d];var e=a.constructor;c.type!==e.getType()&&r(130,e.name);d=c.children;if(D(a))for(Array.isArray(d)||r(59,e.name),a=a.getChildren(),e=0;e<a.length;e++){let f=Bf(a[e],b);d.push(f)}return c}
class uf{constructor(a,b){this._nodeMap=a;this._selection=b||null;this._readOnly=this._flushSync=!1}isEmpty(){return 1===this._nodeMap.size&&null===this._selection}read(a){return of(this,a)}clone(a){a=new uf(this._nodeMap,void 0===a?this._selection:a);a._readOnly=!0;return a}toJSON(){return of(this,()=>({root:Bf(hc())}))}}
class Cf extends xf{static getType(){return"paragraph"}static clone(a){return new Cf(a.__key)}createDOM(a){let b=document.createElement("p");a=qc(a.theme,"paragraph");void 0!==a&&b.classList.add(...a);return b}updateDOM(){return!1}static importDOM(){return{p:()=>({conversion:Df,priority:0})}}exportDOM(a){({element:a}=super.exportDOM(a));if(a&&Hc(a)){this.isEmpty()&&a.append(document.createElement("br"));var b=this.getFormatType();a.style.textAlign=b;if(b=this.getDirection())a.dir=b;b=this.getIndent();
0<b&&(a.style.textIndent=`${20*b}px`)}return{element:a}}static importJSON(a){let b=de();b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{...super.exportJSON(),type:"paragraph",version:1}}insertNewAfter(a,b){a=de();let c=this.getDirection();a.setDirection(c);this.insertAfter(a,b);return a}collapseAtStart(){let a=this.getChildren();if(0===a.length||B(a[0])&&""===a[0].getTextContent().trim()){if(null!==this.getNextSibling())return this.selectNext(),
this.remove(),!0;if(null!==this.getPreviousSibling())return this.selectPrevious(),this.remove(),!0}return!1}}function Df(a){let b=de();a.style&&(b.setFormat(a.style.textAlign),a=parseInt(a.style.textIndent,10)/20,0<a&&b.setIndent(a));return{node:b}}function de(){return Ac(new Cf)}
function qf(a,b,c,d){let e=a._keyToDOMMap;e.clear();a._editorState=Af();a._pendingEditorState=d;a._compositionKey=null;a._dirtyType=0;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();a._normalizedNodes=new Set;a._updateTags=new Set;a._updates=[];a._blockCursorElement=null;d=a._observer;null!==d&&(d.disconnect(),a._observer=null);null!==b&&(b.textContent="");null!==c&&(c.textContent="",e.set("root",c))}
function Jf(a){let b=new Map,c=new Set;a.forEach(d=>{d=null!=d.klass.importDOM?d.klass.importDOM.bind(d.klass):null;if(null!=d&&!c.has(d)){c.add(d);var e=d();null!==e&&Object.keys(e).forEach(f=>{let g=b.get(f);void 0===g&&(g=[],b.set(f,g));g.push(e[f])})}});return b}
class Kf{constructor(a,b,c,d,e,f,g){this._parentEditor=b;this._rootElement=null;this._editorState=a;this._compositionKey=this._pendingEditorState=null;this._deferred=[];this._keyToDOMMap=new Map;this._updates=[];this._updating=!1;this._listeners={decorator:new Set,editable:new Set,mutation:new Map,root:new Set,textcontent:new Set,update:new Set};this._commands=new Map;this._config=d;this._nodes=c;this._decorators={};this._pendingDecorators=null;this._dirtyType=0;this._cloneNotNeeded=new Set;this._dirtyLeaves=
new Set;this._dirtyElements=new Map;this._normalizedNodes=new Set;this._updateTags=new Set;this._observer=null;this._key=mc();this._onError=e;this._htmlConversions=f;this._editable=g;this._headless=null!==b&&b._headless;this._blockCursorElement=this._window=null}isComposing(){return null!=this._compositionKey}registerUpdateListener(a){let b=this._listeners.update;b.add(a);return()=>{b.delete(a)}}registerEditableListener(a){let b=this._listeners.editable;b.add(a);return()=>{b.delete(a)}}registerDecoratorListener(a){let b=
this._listeners.decorator;b.add(a);return()=>{b.delete(a)}}registerTextContentListener(a){let b=this._listeners.textcontent;b.add(a);return()=>{b.delete(a)}}registerRootListener(a){let b=this._listeners.root;a(this._rootElement,null);b.add(a);return()=>{a(null,this._rootElement);b.delete(a)}}registerCommand(a,b,c){void 0===c&&r(35);let d=this._commands;d.has(a)||d.set(a,[new Set,new Set,new Set,new Set,new Set]);let e=d.get(a);void 0===e&&r(36,String(a));let f=e[c];f.add(b);return()=>{f.delete(b);
e.every(g=>0===g.size)&&d.delete(a)}}registerMutationListener(a,b){void 0===this._nodes.get(a.getType())&&r(37,a.name);let c=this._listeners.mutation;c.set(b,a);return()=>{c.delete(b)}}registerNodeTransformToKlass(a,b){var c=a.getType();c=this._nodes.get(c);void 0===c&&r(37,a.name);c.transforms.add(b);return c}registerNodeTransform(a,b){var c=this.registerNodeTransformToKlass(a,b);let d=[c];c=c.replaceWithKlass;null!=c&&(c=this.registerNodeTransformToKlass(c,b),d.push(c));ic(this,a.getType());return()=>
{d.forEach(e=>e.transforms.delete(b))}}hasNode(a){return this._nodes.has(a.getType())}hasNodes(a){return a.every(this.hasNode.bind(this))}dispatchCommand(a,b){return O(this,a,b)}getDecorators(){return this._decorators}getRootElement(){return this._rootElement}getKey(){return this._key}setRootElement(a){let b=this._rootElement;if(a!==b){let f=qc(this._config.theme,"root");var c=this._pendingEditorState||this._editorState;this._rootElement=a;qf(this,b,a,c);if(null!==b){if(!this._config.disableEvents){0!==
Hd&&(Hd--,0===Hd&&b.ownerDocument.removeEventListener("selectionchange",Xd));var d=b.__lexicalEditor;if(null!==d&&void 0!==d){if(null!==d._parentEditor){var e=lc(d);e=e[e.length-1]._key;Wd.get(e)===d&&Wd.delete(e)}else Wd.delete(d._key);b.__lexicalEditor=null}d=Vd(b);for(e=0;e<d.length;e++)d[e]();b.__lexicalEventHandles=[]}null!=f&&b.classList.remove(...f)}null!==a?(c=(c=a.ownerDocument)&&c.defaultView||null,d=a.style,d.userSelect="text",d.whiteSpace="pre-wrap",d.wordBreak="break-word",a.setAttribute("data-lexical-editor",
"true"),this._window=c,this._dirtyType=2,Bb(this),this._updateTags.add("history-merge"),pf(this),this._config.disableEvents||Yd(a,this),null!=f&&a.classList.add(...f)):(this._editorState=c,this._window=this._pendingEditorState=null);rf("root",this,!1,a,b)}}getElementByKey(a){return this._keyToDOMMap.get(a)||null}getEditorState(){return this._editorState}setEditorState(a,b){a.isEmpty()&&r(38);Ab(this);let c=this._pendingEditorState,d=this._updateTags;b=void 0!==b?b.tag:null;null===c||c.isEmpty()||
(null!=b&&d.add(b),pf(this));this._pendingEditorState=a;this._dirtyType=2;this._dirtyElements.set("root",!1);this._compositionKey=null;null!=b&&d.add(b);pf(this)}parseEditorState(a,b){a="string"===typeof a?JSON.parse(a):a;let c=Af(),d=S,e=V,f=T,g=this._dirtyElements,h=this._dirtyLeaves,k=this._cloneNotNeeded,m=this._dirtyType;this._dirtyElements=new Map;this._dirtyLeaves=new Set;this._cloneNotNeeded=new Set;this._dirtyType=0;S=c;V=!1;T=this;try{nf(a.root,this._nodes),b&&b(),c._readOnly=!0}catch(n){n instanceof
Error&&this._onError(n)}finally{this._dirtyElements=g,this._dirtyLeaves=h,this._cloneNotNeeded=k,this._dirtyType=m,S=d,V=e,T=f}return c}update(a,b){w(this,a,b)}focus(a,b={}){let c=this._rootElement;null!==c&&(c.setAttribute("autocapitalize","off"),w(this,()=>{let d=v(),e=hc();null!==d?d.dirty=!0:0!==e.getChildrenSize()&&("rootStart"===b.defaultSelection?e.selectStart():e.selectEnd())},{onUpdate:()=>{c.removeAttribute("autocapitalize");a&&a()},tag:"focus"}),null===this._pendingEditorState&&c.removeAttribute("autocapitalize"))}blur(){var a=
this._rootElement;null!==a&&a.blur();a=vb(this._window);null!==a&&a.removeAllRanges()}isEditable(){return this._editable}setEditable(a){this._editable!==a&&(this._editable=a,rf("editable",this,!0,a))}toJSON(){return{editorState:this._editorState.toJSON()}}}
class gf extends xf{constructor(a,b){super(b);this.__colSpan=a;this.__rowSpan=1}exportJSON(){return{...super.exportJSON(),colSpan:this.__colSpan,rowSpan:this.__rowSpan}}getColSpan(){return this.__colSpan}setColSpan(a){this.getWritable().__colSpan=a;return this}getRowSpan(){return this.__rowSpan}setRowSpan(a){this.getWritable().__rowSpan=a;return this}}function P(a){return a instanceof gf}class Lf extends xf{}function Ue(a){return a instanceof Lf}class Mf extends xf{}
function Te(a){return a instanceof Mf}exports.$addUpdateTag=function(a){G();F()._updateTags.add(a)};exports.$applyNodeReplacement=Ac;exports.$copyNode=zc;exports.$createLineBreakNode=ge;exports.$createNodeSelection=Ze;exports.$createParagraphNode=de;exports.$createRangeSelection=function(){let a=new ze("root",0,"element"),b=new ze("root",0,"element");return new Ne(a,b,0,"")};exports.$createTabNode=ue;exports.$createTextNode=J;exports.$getAdjacentNode=tc;exports.$getNearestNodeFromDOMNode=ub;
exports.$getNearestRootOrShadowRoot=xc;exports.$getNodeByKey=I;exports.$getPreviousSelection=oc;exports.$getRoot=hc;exports.$getSelection=v;exports.$getTextContent=function(){let a=v();return null===a?"":a.getTextContent()};exports.$hasAncestor=wc;exports.$hasUpdateTag=function(a){return F()._updateTags.has(a)};exports.$insertNodes=function(a,b){let c=v()||oc();null===c&&(c=hc().selectEnd());return c.insertNodes(a,b)};exports.$isBlockElementNode=Ye;exports.$isDecoratorNode=z;
exports.$isElementNode=D;exports.$isInlineElementOrDecoratorNode=function(a){return D(a)&&a.isInline()||z(a)&&a.isInline()};exports.$isLeafNode=Xb;exports.$isLineBreakNode=Yb;exports.$isNodeSelection=Ud;exports.$isParagraphNode=function(a){return a instanceof Cf};exports.$isRangeSelection=C;exports.$isRootNode=K;exports.$isRootOrShadowRoot=yc;exports.$isTabNode=function(a){return a instanceof ye};exports.$isTextNode=B;
exports.$nodesOfType=function(a){var b=ac();let c=b._readOnly,d=a.getType();b=b._nodeMap;let e=[];for(let [,f]of b)f instanceof a&&f.__type===d&&(c||f.isAttached())&&e.push(f);return e};exports.$normalizeSelection__EXPERIMENTAL=Gb;exports.$parseSerializedNode=function(a){return nf(a,F()._nodes)};exports.$selectAll=function(){var a=hc();a=a.select(0,a.getChildrenSize());yb(Gb(a))};exports.$setCompositionKey=H;exports.$setSelection=yb;exports.$splitNode=Ec;exports.BLUR_COMMAND=Ra;
exports.CAN_REDO_COMMAND={};exports.CAN_UNDO_COMMAND={};exports.CLEAR_EDITOR_COMMAND={};exports.CLEAR_HISTORY_COMMAND={};exports.CLICK_COMMAND=ba;exports.COMMAND_PRIORITY_CRITICAL=4;exports.COMMAND_PRIORITY_EDITOR=0;exports.COMMAND_PRIORITY_HIGH=3;exports.COMMAND_PRIORITY_LOW=1;exports.COMMAND_PRIORITY_NORMAL=2;exports.CONTROLLED_TEXT_INSERTION_COMMAND=ha;exports.COPY_COMMAND=Na;exports.CUT_COMMAND=Oa;exports.DELETE_CHARACTER_COMMAND=da;exports.DELETE_LINE_COMMAND=pa;exports.DELETE_WORD_COMMAND=na;
exports.DEPRECATED_$computeGridMap=Ve;exports.DEPRECATED_$createGridSelection=function(){let a=new ze("root",0,"element"),b=new ze("root",0,"element");return new Qe("root",a,b)};exports.DEPRECATED_$getGridCellNodeRect=Oe;exports.DEPRECATED_$getNodeTriplet=Pe;exports.DEPRECATED_$isGridCellNode=P;exports.DEPRECATED_$isGridNode=Ue;exports.DEPRECATED_$isGridRowNode=Te;exports.DEPRECATED_$isGridSelection=Re;exports.DEPRECATED_GridCellNode=gf;exports.DEPRECATED_GridNode=Lf;
exports.DEPRECATED_GridRowNode=Mf;exports.DRAGEND_COMMAND=Ma;exports.DRAGOVER_COMMAND=La;exports.DRAGSTART_COMMAND=Ka;exports.DROP_COMMAND=Ja;exports.DecoratorNode=wf;exports.ElementNode=xf;exports.FOCUS_COMMAND=Qa;exports.FORMAT_ELEMENT_COMMAND={};exports.FORMAT_TEXT_COMMAND=qa;exports.INDENT_CONTENT_COMMAND={};exports.INSERT_LINE_BREAK_COMMAND=ea;exports.INSERT_PARAGRAPH_COMMAND=fa;exports.INSERT_TAB_COMMAND={};exports.KEY_ARROW_DOWN_COMMAND=Aa;exports.KEY_ARROW_LEFT_COMMAND=xa;
exports.KEY_ARROW_RIGHT_COMMAND=ua;exports.KEY_ARROW_UP_COMMAND=za;exports.KEY_BACKSPACE_COMMAND=Fa;exports.KEY_DELETE_COMMAND=Ha;exports.KEY_DOWN_COMMAND=ta;exports.KEY_ENTER_COMMAND=Ba;exports.KEY_ESCAPE_COMMAND=Ga;exports.KEY_MODIFIER_COMMAND=Sa;exports.KEY_SPACE_COMMAND=Ca;exports.KEY_TAB_COMMAND=Ia;exports.LineBreakNode=ee;exports.MOVE_TO_END=va;exports.MOVE_TO_START=ya;exports.OUTDENT_CONTENT_COMMAND={};exports.PASTE_COMMAND=ka;exports.ParagraphNode=Cf;exports.REDO_COMMAND=sa;
exports.REMOVE_TEXT_COMMAND=ma;exports.RootNode=zf;exports.SELECTION_CHANGE_COMMAND=aa;exports.SELECT_ALL_COMMAND=Pa;exports.TabNode=ye;exports.TextNode=me;exports.UNDO_COMMAND=ra;exports.createCommand=function(){return{}};
exports.createEditor=function(a){var b=a||{},c=T,d=b.theme||{};let e=void 0===a?c:b.parentEditor||null,f=b.disableEvents||!1,g=Af(),h=b.namespace||(null!==e?e._config.namespace:mc()),k=b.editorState,m=[zf,me,ee,ye,Cf,...(b.nodes||[])],n=b.onError;b=void 0!==b.editable?b.editable:!0;if(void 0===a&&null!==c)a=c._nodes;else for(a=new Map,c=0;c<m.length;c++){let l=m[c],q=null;var p=null;"function"!==typeof l&&(p=l,l=p.replace,q=p.with,p=p.withKlass?p.withKlass:null);let u=l.getType(),x=l.transform(),
y=new Set;null!==x&&y.add(x);a.set(u,{klass:l,replace:q,replaceWithKlass:p,transforms:y})}d=new Kf(g,e,a,{disableEvents:f,namespace:h,theme:d},n?n:console.error,Jf(a),b);void 0!==k&&(d._pendingEditorState=k,d._dirtyType=2);return d};exports.getNearestEditorFromDOMNode=Mb;exports.isHTMLAnchorElement=function(a){return Hc(a)&&"A"===a.tagName};exports.isHTMLElement=Hc;exports.isSelectionCapturedInDecoratorInput=Kb;exports.isSelectionWithinEditor=Lb
