/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var aa=require("@lexical/utils");let ca={},da={},ea={},fa={},ha={},ka={},ma={},na={},pa={},qa={},ra={},sa={},ta={},ua={},va={},xa={},ya={},za={},Aa={},Ba={},Ca={},Fa={},Ga={},Ha={},Ia={},Ja={},Ka={},La={},Ma={},Na={},Oa={},Pa={},Qa={},Ra={},Sa={},Ta={};
function q(a){let b=new URLSearchParams;b.append("code",a);for(let c=1;c<arguments.length;c++)b.append("v",arguments[c]);throw Error(`Minified Lexical error #${a}; visit https://lexical.dev/docs/error?${b} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}
let Ua="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,Wa=Ua&&"documentMode"in document?document.documentMode:null,t=Ua&&/Mac|iPod|iPhone|iPad/.test(navigator.platform),Xa=Ua&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent),Ya=Ua&&"InputEvent"in window&&!Wa?"getTargetRanges"in new window.InputEvent("input"):!1,Za=Ua&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),$a=Ua&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&
!window.MSStream,ab=Ua&&/^(?=.*Chrome).*/i.test(navigator.userAgent),bb=Ua&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!ab,cb=Za||$a||bb?"\u00a0":"\u200b",db=Xa?"\u00a0":cb,eb=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]/,fb=/^[^\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,
gb={bold:1,code:16,highlight:128,italic:2,strikethrough:4,subscript:32,superscript:64,underline:8},hb={directionless:1,unmergeable:2},ib={center:2,end:6,justify:4,left:1,right:3,start:5},jb={2:"center",6:"end",4:"justify",1:"left",3:"right",5:"start"},kb={normal:0,segmented:2,token:1},ob={0:"normal",2:"segmented",1:"token"},pb=!1,qb=0;function rb(a){qb=a.timeStamp}function sb(a,b,c){return b.__lexicalLineBreak===a||void 0!==a[`__lexicalKey_${c._key}`]}
function tb(a){return a.getEditorState().read(()=>{let b=v();return null!==b?b.clone():null})}
function ub(a,b,c){pb=!0;let d=100<performance.now()-qb;try{w(a,()=>{let e=v()||tb(a);var f=new Map,g=a.getRootElement(),h=a._editorState,k=a._blockCursorElement;let n=!1,m="";for(var p=0;p<b.length;p++){var l=b[p],r=l.type,u=l.target,x=vb(u,h);if(!(null===x&&u!==g||z(x)))if("characterData"===r){if(l=d&&B(x))a:{l=e;r=u;var y=x;if(C(l)){var A=l.anchor.getNode();if(A.is(y)&&l.format!==A.getFormat()){l=!1;break a}}l=3===r.nodeType&&y.isAttached()}l&&(y=wb(a._window),r=l=null,null!==y&&y.anchorNode===
u&&(l=y.anchorOffset,r=y.focusOffset),u=u.nodeValue,null!==u&&xb(x,u,l,r,!1))}else if("childList"===r){n=!0;r=l.addedNodes;for(y=0;y<r.length;y++){A=r[y];var Y=yb(A),ba=A.parentNode;null==ba||A===k||null!==Y||"BR"===A.nodeName&&sb(A,ba,a)||(Xa&&(Y=A.innerText||A.nodeValue)&&(m+=Y),ba.removeChild(A))}l=l.removedNodes;r=l.length;if(0<r){y=0;for(A=0;A<r;A++)if(ba=l[A],"BR"===ba.nodeName&&sb(ba,u,a)||k===ba)u.appendChild(ba),y++;r!==y&&(u===g&&(x=h._nodeMap.get("root")),f.set(u,x))}}}if(0<f.size)for(let [Va,
la]of f)if(D(la))for(f=la.getChildrenKeys(),g=Va.firstChild,h=0;h<f.length;h++)k=a.getElementByKey(f[h]),null!==k&&(null==g?(Va.appendChild(k),g=k):g!==k&&Va.replaceChild(k,g),g=g.nextSibling);else B(la)&&la.markDirty();f=c.takeRecords();if(0<f.length){for(g=0;g<f.length;g++)for(k=f[g],h=k.addedNodes,k=k.target,p=0;p<h.length;p++)x=h[p],u=x.parentNode,null==u||"BR"!==x.nodeName||sb(x,k,a)||u.removeChild(x);c.takeRecords()}null!==e&&(n&&(e.dirty=!0,zb(e)),Xa&&Ab(a)&&e.insertRawText(m))})}finally{pb=
!1}}function Bb(a){let b=a._observer;if(null!==b){let c=b.takeRecords();ub(a,c,b)}}function Cb(a){0===qb&&Db(a).addEventListener("textInput",rb,!0);a._observer=new MutationObserver((b,c)=>{ub(a,b,c)})}function Eb(a,b){let c=a.__mode,d=a.__format;a=a.__style;let e=b.__mode,f=b.__format;b=b.__style;return(null===c||c===e)&&(null===d||d===f)&&(null===a||a===b)}function Fb(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}
function Gb(a){if(""===a.__text&&a.isSimpleText()&&!a.isUnmergeable())a.remove();else{for(var b;null!==(b=a.getPreviousSibling())&&B(b)&&b.isSimpleText()&&!b.isUnmergeable();)if(""===b.__text)b.remove();else{Eb(b,a)&&(a=Fb(b,a));break}for(var c;null!==(c=a.getNextSibling())&&B(c)&&c.isSimpleText()&&!c.isUnmergeable();)if(""===c.__text)c.remove();else{Eb(a,c)&&Fb(a,c);break}}}function Hb(a){Ib(a.anchor);Ib(a.focus);return a}
function Ib(a){for(;"element"===a.type;){var b=a.getNode(),c=a.offset;c===b.getChildrenSize()?(b=b.getChildAtIndex(c-1),c=!0):(b=b.getChildAtIndex(c),c=!1);if(B(b)){a.set(b.__key,c?b.getTextContentSize():0,"text");break}else if(!D(b))break;a.set(b.__key,c?b.getChildrenSize():0,"element")}}let Jb=1,Kb="function"===typeof queueMicrotask?queueMicrotask:a=>{Promise.resolve().then(a)};
function Lb(a){let b=document.activeElement;if(null===b)return!1;let c=b.nodeName;return z(vb(a))&&("INPUT"===c||"TEXTAREA"===c||"true"===b.contentEditable&&null==b.__lexicalEditor)}function Mb(a,b,c){let d=a.getRootElement();try{return null!==d&&d.contains(b)&&d.contains(c)&&null!==b&&!Lb(b)&&Nb(b)===a}catch(e){return!1}}function Nb(a){for(;null!=a;){let b=a.__lexicalEditor;if(null!=b)return b;a=Ub(a)}return null}function Vb(a){return a.isToken()||a.isSegmented()}
function Wb(a){for(;null!=a;){if(3===a.nodeType)return a;a=a.firstChild}return null}function Xb(a,b,c){b=gb[b];return a&b&&(null===c||0===(c&b))?a^b:null===c||c&b?a|b:a}function Yb(a){return B(a)||Zb(a)||z(a)}function $b(a,b){if(null!=b)a.__key=b;else{G();99<ac&&q(14);b=F();var c=bc(),d=""+Jb++;c._nodeMap.set(d,a);D(a)?b._dirtyElements.set(d,!0):b._dirtyLeaves.add(d);b._cloneNotNeeded.add(d);b._dirtyType=1;a.__key=d}}
function cc(a){var b=a.getParent();if(null!==b){let e=a.getWritable();b=b.getWritable();var c=a.getPreviousSibling();a=a.getNextSibling();if(null===c)if(null!==a){var d=a.getWritable();b.__first=a.__key;d.__prev=null}else b.__first=null;else{d=c.getWritable();if(null!==a){let f=a.getWritable();f.__prev=d.__key;d.__next=f.__key}else d.__next=null;e.__prev=null}null===a?null!==c?(a=c.getWritable(),b.__last=c.__key,a.__next=null):b.__last=null:(a=a.getWritable(),null!==c?(c=c.getWritable(),c.__next=
a.__key,a.__prev=c.__key):a.__prev=null,e.__next=null);b.__size--;e.__parent=null}}function dc(a){99<ac&&q(14);var b=a.getLatest(),c=b.__parent,d=bc();let e=F(),f=d._nodeMap;d=e._dirtyElements;if(null!==c)a:for(;null!==c;){if(d.has(c))break a;let g=f.get(c);if(void 0===g)break;d.set(c,!1);c=g.__parent}b=b.__key;e._dirtyType=1;D(a)?d.set(b,!0):e._dirtyLeaves.add(b)}
function H(a){G();var b=F();let c=b._compositionKey;a!==c&&(b._compositionKey=a,null!==c&&(b=I(c),null!==b&&b.getWritable()),null!==a&&(a=I(a),null!==a&&a.getWritable()))}function ec(){return fc()?null:F()._compositionKey}function I(a,b){a=(b||bc())._nodeMap.get(a);return void 0===a?null:a}function yb(a,b){let c=F();a=a[`__lexicalKey_${c._key}`];return void 0!==a?I(a,b):null}function vb(a,b){for(;null!=a;){let c=yb(a,b);if(null!==c)return c;a=Ub(a)}return null}
function gc(a){let b=Object.assign({},a._decorators);return a._pendingDecorators=b}function hc(a){return a.read(()=>ic().getTextContent())}function jc(a,b){w(a,()=>{var c=bc();if(!c.isEmpty())if("root"===b)ic().markDirty();else{c=c._nodeMap;for(let [,d]of c)d.markDirty()}},null===a._pendingEditorState?{tag:"history-merge"}:void 0)}function ic(){return bc()._nodeMap.get("root")}function zb(a){G();let b=bc();null!==a&&(a.dirty=!0,a._cachedNodes=null);b._selection=a}
function kc(a){var b=F(),c;a:{for(c=a;null!=c;){let d=c[`__lexicalKey_${b._key}`];if(void 0!==d){c=d;break a}c=Ub(c)}c=null}return null===c?(b=b.getRootElement(),a===b?I("root"):null):I(c)}function lc(a){return/[\uD800-\uDBFF][\uDC00-\uDFFF]/g.test(a)}function mc(a){let b=[];for(;null!==a;)b.push(a),a=a._parentEditor;return b}function nc(){return Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,5)}
function oc(a,b,c){b=wb(b._window);if(null!==b){var d=b.anchorNode,{anchorOffset:e,focusOffset:f}=b;if(null!==d&&(b=3===d.nodeType?d.nodeValue:null,d=vb(d),null!==b&&B(d))){if(b===cb&&c){let g=c.length;b=c;f=e=g}null!==b&&xb(d,b,e,f,a)}}}
function xb(a,b,c,d,e){let f=a;if(f.isAttached()&&(e||!f.isDirty())){let n=f.isComposing(),m=b;(n||e)&&b[b.length-1]===cb&&(m=b.slice(0,-1));b=f.getTextContent();if(e||m!==b)if(""===m)if(H(null),Za||$a||bb)f.remove();else{let p=F();setTimeout(()=>{p.update(()=>{f.isAttached()&&f.remove()})},20)}else{e=f.getParent();b=pc();var g=f.getTextContentSize(),h=ec(),k=f.getKey();f.isToken()||null!==h&&k===h&&!n||C(b)&&(null!==e&&!e.canInsertTextBefore()&&0===b.anchor.offset||b.anchor.key===a.__key&&0===b.anchor.offset&&
!f.canInsertTextBefore()||b.focus.key===a.__key&&b.focus.offset===g&&!f.canInsertTextAfter())?f.markDirty():(a=v(),C(a)&&null!==c&&null!==d&&(a.setTextNodeRange(f,c,f,d),f.isSegmented()&&(c=f.getTextContent(),c=J(c),f.replace(c),f=c)),f.setTextContent(m))}}}
function qc(a,b){if(b.isSegmented())return!0;if(!a.isCollapsed())return!1;a=a.anchor.offset;let c=b.getParentOrThrow(),d=b.isToken();return 0===a?((a=!b.canInsertTextBefore()||!c.canInsertTextBefore()||d)||(b=b.getPreviousSibling(),a=(B(b)||D(b)&&b.isInline())&&!b.canInsertTextAfter()),a):a===b.getTextContentSize()?!b.canInsertTextAfter()||!c.canInsertTextAfter()||d:!1}
function rc(a,b){void 0===a.__lexicalClassNameCache&&(a.__lexicalClassNameCache={});let c=a.__lexicalClassNameCache,d=c[b];if(void 0!==d)return d;a=a[b];return"string"===typeof a?(a=a.split(" "),c[b]=a):a}function sc(a,b,c,d,e){0!==c.size&&(c=d.__type,d=d.__key,b=b.get(c),void 0===b&&q(33,c),c=b.klass,b=a.get(c),void 0===b&&(b=new Map,a.set(c,b)),a=b.get(d),c="destroyed"===a&&"created"===e,(void 0===a||c)&&b.set(d,c?"updated":e))}
function tc(a,b,c){let d=a.getParent(),e=c;null!==d&&(b&&0===c?(e=a.getIndexWithinParent(),a=d):b||c!==a.getChildrenSize()||(e=a.getIndexWithinParent()+1,a=d));return a.getChildAtIndex(b?e-1:e)}function uc(a,b){var c=a.offset;if("element"===a.type)return a=a.getNode(),tc(a,b,c);a=a.getNode();return b&&0===c||!b&&c===a.getTextContentSize()?(c=b?a.getPreviousSibling():a.getNextSibling(),null===c?tc(a.getParentOrThrow(),b,a.getIndexWithinParent()+(b?0:1)):c):null}
function Ab(a){a=(a=Db(a).event)&&a.inputType;return"insertFromPaste"===a||"insertFromPasteAsQuotation"===a}function vc(a){return!K(a)&&!a.isLastChild()&&!a.isInline()}function wc(a,b){a=a._keyToDOMMap.get(b);void 0===a&&q(75,b);return a}function Ub(a){a=a.assignedSlot||a.parentElement;return null!==a&&11===a.nodeType?a.host:a}function xc(a,b){for(a=a.getParent();null!==a;){if(a.is(b))return!0;a=a.getParent()}return!1}function Db(a){a=a._window;null===a&&q(78);return a}
function yc(a){for(a=a.getParentOrThrow();null!==a&&!L(a);)a=a.getParentOrThrow();return a}function L(a){return K(a)||D(a)&&a.isShadowRoot()}function zc(a){a=a.constructor.clone(a);$b(a,null);return a}function Ac(a){var b=F();let c=a.constructor.getType();b=b._nodes.get(c);void 0===b&&q(97);b=b.replace;return null!==b?(b=b(a),b instanceof a.constructor||q(98),b):a}function Bc(a,b){a=a.getParent();!K(a)||D(b)||z(b)||q(99)}function Cc(a){return(z(a)||D(a)&&!a.canBeEmpty())&&!a.isInline()}
function Dc(a,b,c){c.style.removeProperty("caret-color");b._blockCursorElement=null;b=a.parentElement;null!==b&&b.removeChild(a)}function wb(a){return Ua?(a||window).getSelection():null}function Ec(a,b){let c=a.getChildAtIndex(b);null==c&&(c=a);L(a)&&q(102);let d=g=>{const h=g.getParentOrThrow(),k=L(h),n=g!==c||k?zc(g):g;if(k)return g.insertAfter(n),[g,n,n];const [m,p,l]=d(h);g=g.getNextSiblings();l.append(n,...g);return[m,p,n]},[e,f]=d(c);return[e,f]}
function Fc(a,b){for(;a!==ic()&&null!=a;){if(b(a))return a;a=a.getParent()}return null}function Gc(a){let b=[],c=[a];for(;0<c.length;){let d=c.pop();void 0===d&&q(112);D(d)&&c.unshift(...d.getChildren());d!==a&&b.push(d)}return b}function Hc(a,b,c,d,e,f){for(a=a.getFirstChild();null!==a;){let g=a.__key;a.__parent===b&&(D(a)&&Hc(a,g,c,d,e,f),c.has(g)||f.delete(g),e.push(g));a=a.getNextSibling()}}
function Ic(a,b,c,d){a=a._nodeMap;b=b._nodeMap;let e=[];for(let [f]of d){let g=b.get(f);void 0===g||g.isAttached()||(D(g)&&Hc(g,f,a,b,e,d),a.has(f)||d.delete(f),e.push(f))}for(let f of e)b.delete(f);for(let f of c)d=b.get(f),void 0===d||d.isAttached()||(a.has(f)||c.delete(f),b.delete(f))}let M="",N="",Jc="",Kc,O,Lc,Mc=!1,Nc=!1,Oc,Pc=null,Qc,Rc,Sc,bd,cd,dd;
function ed(a,b){let c=Sc.get(a);if(null!==b){let d=fd(a);d.parentNode===b&&b.removeChild(d)}bd.has(a)||O._keyToDOMMap.delete(a);D(c)&&(a=gd(c,Sc),hd(a,0,a.length-1,null));void 0!==c&&sc(dd,Lc,Oc,c,"destroyed")}function hd(a,b,c,d){for(;b<=c;++b){let e=a[b];void 0!==e&&ed(e,d)}}function id(a,b){a.setProperty("text-align",b)}
function jd(a,b){var c=Kc.theme.indent;if("string"===typeof c){let d=a.classList.contains(c);0<b&&!d?a.classList.add(c):1>b&&d&&a.classList.remove(c)}c=getComputedStyle(a).getPropertyValue("--lexical-indent-base-value")||"40px";a.style.setProperty("padding-inline-start",0===b?"":`calc(${b} * ${c})`)}function kd(a,b){a=a.style;0===b?id(a,""):1===b?id(a,"left"):2===b?id(a,"center"):3===b?id(a,"right"):4===b?id(a,"justify"):5===b?id(a,"start"):6===b&&id(a,"end")}
function ld(a,b,c){let d=bd.get(a);void 0===d&&q(60);let e=d.createDOM(Kc,O);var f=O._keyToDOMMap;e["__lexicalKey_"+O._key]=a;f.set(a,e);B(d)?e.setAttribute("data-lexical-text","true"):z(d)&&e.setAttribute("data-lexical-decorator","true");if(D(d)){a=d.__indent;f=d.__size;0!==a&&jd(e,a);if(0!==f){--f;a=gd(d,bd);var g=N;N="";md(a,d,0,f,e,null);nd(d,e);N=g}a=d.__format;0!==a&&kd(e,a);d.isInline()||od(null,d,e);vc(d)&&(M+="\n\n",Jc+="\n\n")}else f=d.getTextContent(),z(d)?(g=d.decorate(O,Kc),null!==g&&
pd(a,g),e.contentEditable="false"):B(d)&&(d.isDirectionless()||(N+=f)),M+=f,Jc+=f;null!==b&&(null!=c?b.insertBefore(e,c):(c=b.__lexicalLineBreak,null!=c?b.insertBefore(e,c):b.appendChild(e)));sc(dd,Lc,Oc,d,"created");return e}function md(a,b,c,d,e,f){let g=M;for(M="";c<=d;++c)ld(a[c],e,f);vc(b)&&(M+="\n\n");e.__lexicalTextContent=M;M=g+M}function qd(a,b){a=b.get(a);return Zb(a)||z(a)&&a.isInline()}
function od(a,b,c){a=null!==a&&(0===a.__size||qd(a.__last,Sc));b=0===b.__size||qd(b.__last,bd);a?b||(b=c.__lexicalLineBreak,null!=b&&c.removeChild(b),c.__lexicalLineBreak=null):b&&(b=document.createElement("br"),c.__lexicalLineBreak=b,c.appendChild(b))}
function nd(a,b){var c=b.__lexicalDir;if(b.__lexicalDirTextContent!==N||c!==Pc){let f=""===N;if(f)var d=Pc;else d=N,d=eb.test(d)?"rtl":fb.test(d)?"ltr":null;if(d!==c){let g=b.classList,h=Kc.theme;var e=null!==c?h[c]:void 0;let k=null!==d?h[d]:void 0;void 0!==e&&("string"===typeof e&&(e=e.split(" "),e=h[c]=e),g.remove(...e));null===d||f&&"ltr"===d?b.removeAttribute("dir"):(void 0!==k&&("string"===typeof k&&(c=k.split(" "),k=h[d]=c),void 0!==k&&g.add(...k)),b.dir=d);Nc||(a.getWritable().__dir=d)}Pc=
d;b.__lexicalDirTextContent=N;b.__lexicalDir=d}}function gd(a,b){let c=[];for(a=a.__first;null!==a;){let d=b.get(a);void 0===d&&q(101);c.push(a);a=d.__next}return c}
function rd(a,b){var c=Sc.get(a),d=bd.get(a);void 0!==c&&void 0!==d||q(61);var e=Mc||Rc.has(a)||Qc.has(a);let f=wc(O,a);if(c===d&&!e)return D(c)?(d=f.__lexicalTextContent,void 0!==d&&(M+=d,Jc+=d),d=f.__lexicalDirTextContent,void 0!==d&&(N+=d)):(d=c.getTextContent(),B(c)&&!c.isDirectionless()&&(N+=d),Jc+=d,M+=d),f;c!==d&&e&&sc(dd,Lc,Oc,d,"updated");if(d.updateDOM(c,f,Kc))return d=ld(a,null,null),null===b&&q(62),b.replaceChild(d,f),ed(a,null),d;if(D(c)&&D(d)){a=d.__indent;a!==c.__indent&&jd(f,a);a=
d.__format;a!==c.__format&&kd(f,a);if(e){a=d;e=N;N="";b=M;var g=c.__size,h=a.__size;M="";if(1===g&&1===h){var k=c.__first,n=a.__first;if(k===n)rd(k,f);else{var m=fd(k);n=ld(n,null,null);f.replaceChild(n,m);ed(k,null)}}else{n=gd(c,Sc);var p=gd(a,bd);if(0===g)0!==h&&md(p,a,0,h-1,f,null);else if(0===h)0!==g&&(k=null==f.__lexicalLineBreak,hd(n,0,g-1,k?null:f),k&&(f.textContent=""));else{var l=n;n=p;p=g-1;g=h-1;let u=f.firstChild,x=0;for(h=0;x<=p&&h<=g;){var r=l[x];let y=n[h];if(r===y)u=sd(rd(y,f)),x++,
h++;else{void 0===k&&(k=new Set(l));void 0===m&&(m=new Set(n));let A=m.has(r),Y=k.has(y);A?(Y?(r=wc(O,y),r===u?u=sd(rd(y,f)):(null!=u?f.insertBefore(r,u):f.appendChild(r),rd(y,f)),x++):ld(y,f,u),h++):(u=sd(fd(r)),ed(r,f),x++)}}k=x>p;m=h>g;k&&!m?(k=n[g+1],k=void 0===k?null:O.getElementByKey(k),md(n,a,h,g,f,k)):m&&!k&&hd(l,x,p,f)}}vc(a)&&(M+="\n\n");f.__lexicalTextContent=M;M=b+M;nd(a,f);N=e;K(d)||d.isInline()||od(c,d,f)}vc(d)&&(M+="\n\n",Jc+="\n\n")}else c=d.getTextContent(),z(d)?(e=d.decorate(O,Kc),
null!==e&&pd(a,e)):B(d)&&!d.isDirectionless()&&(N+=c),M+=c,Jc+=c;!Nc&&K(d)&&d.__cachedText!==Jc&&(d=d.getWritable(),d.__cachedText=Jc);return f}function pd(a,b){let c=O._pendingDecorators,d=O._decorators;if(null===c){if(d[a]===b)return;c=gc(O)}c[a]=b}function sd(a){a=a.nextSibling;null!==a&&a===O._blockCursorElement&&(a=a.nextSibling);return a}function fd(a){let b=cd.get(a);void 0===b&&q(75,a);return b}
let td=Object.freeze({}),Ad=[["keydown",ud],["pointerdown",vd],["compositionstart",wd],["compositionend",xd],["input",yd],["click",zd],["cut",td],["copy",td],["dragstart",td],["dragover",td],["dragend",td],["paste",td],["focus",td],["blur",td],["drop",td]];Ya&&Ad.push(["beforeinput",(a,b)=>Bd(a,b)]);let Cd=0,Dd=0,Ed=0,Fd=null,Gd=0,Hd=!1,Id=!1,Jd=!1,Kd=!1,Ld=[0,"",0,"root",0];
function Md(a,b,c,d,e){let f=a.anchor,g=a.focus,h=f.getNode();var k=F();let n=wb(k._window),m=null!==n?n.anchorNode:null,p=f.key;k=k.getElementByKey(p);let l=c.length;return p!==g.key||!B(h)||(!e&&(!Ya||Ed<d+50)||h.isDirty()&&2>l||lc(c))&&f.offset!==g.offset&&!h.isComposing()||Vb(h)||h.isDirty()&&1<l||(e||!Ya)&&null!==k&&!h.isComposing()&&m!==Wb(k)||null!==n&&null!==b&&(!b.collapsed||b.startContainer!==n.anchorNode||b.startOffset!==n.anchorOffset)||h.getFormat()!==a.format||h.getStyle()!==a.style||
qc(a,h)}function Nd(a,b){return null!==a&&null!==a.nodeValue&&3===a.nodeType&&0!==b&&b!==a.nodeValue.length}
function Od(a,b,c){let {anchorNode:d,anchorOffset:e,focusNode:f,focusOffset:g}=a;if(Hd&&(Hd=!1,Nd(d,e)&&Nd(f,g)))return;w(b,()=>{if(!c)zb(null);else if(Mb(b,d,f)){var h=v();if(C(h)){var k=h.anchor,n=k.getNode();if(h.isCollapsed()){"Range"===a.type&&a.anchorNode===a.focusNode&&(h.dirty=!0);var m=Db(b).event;m=m?m.timeStamp:performance.now();let [p,l,r,u,x]=Ld;m<x+200&&k.offset===r&&k.key===u?(h.format=p,h.style=l):"text"===k.type?(h.format=n.getFormat(),h.style=n.getStyle()):"element"===k.type&&(h.format=
0,h.style="")}else{k=255;n=!1;m=h.getNodes();let p=m.length;for(let l=0;l<p;l++){let r=m[l];if(B(r)&&(n=!0,k&=r.getFormat(),0===k))break}h.format=n?k:0}}P(b,ca,void 0)}})}
function zd(a,b){w(b,()=>{let c=v();var d=wb(b._window);let e=pc();if(d)if(C(c)){let g=c.anchor;var f=g.getNode();"element"===g.type&&0===g.offset&&c.isCollapsed()&&!K(f)&&1===ic().getChildrenSize()&&f.getTopLevelElementOrThrow().isEmpty()&&null!==e&&c.is(e)?(d.removeAllRanges(),c.dirty=!0):3!==a.detail||c.isCollapsed()||(d=c.focus.getNode(),f!==d&&(D(f)?f.select(0):f.getParentOrThrow().select(0)))}else"touch"===a.pointerType&&(f=d.anchorNode,null!==f&&(f=f.nodeType,1===f||3===f))&&(d=Pd(e,d,b),zb(d));
P(b,da,a)})}function vd(a,b){let c=a.target;a=a.pointerType;c instanceof Node&&"touch"!==a&&w(b,()=>{z(vb(c))||(Id=!0)})}function Qd(a){if(!a.getTargetRanges)return null;a=a.getTargetRanges();return 0===a.length?null:a[0]}function Rd(a,b){return a!==b||D(a)||D(b)||!a.isToken()||!b.isToken()}
function Bd(a,b){let c=a.inputType,d=Qd(a);"deleteCompositionText"===c||Xa&&Ab(b)||"insertCompositionText"!==c&&w(b,()=>{let e=v();if("deleteContentBackward"===c){if(null===e){var f=pc();if(!C(f))return;zb(f.clone())}if(C(e)){229===Dd&&a.timeStamp<Cd+30&&b.isComposing()&&e.anchor.key===e.focus.key?(H(null),Cd=0,setTimeout(()=>{w(b,()=>{H(null)})},30),C(e)&&(f=e.anchor.getNode(),f.markDirty(),e.format=f.getFormat(),e.style=f.getStyle())):(a.preventDefault(),P(b,ea,!0));return}}if(C(e)){f=a.data;null!==
Fd&&oc(!1,b,Fd);e.dirty&&null===Fd||!e.isCollapsed()||K(e.anchor.getNode())||null===d||e.applyDOMRange(d);Fd=null;var g=e.focus,h=e.anchor.getNode();g=g.getNode();if("insertText"===c||"insertTranspose"===c)"\n"===f?(a.preventDefault(),P(b,fa,!1)):"\n\n"===f?(a.preventDefault(),P(b,ha,void 0)):null==f&&a.dataTransfer?(f=a.dataTransfer.getData("text/plain"),a.preventDefault(),e.insertRawText(f)):null!=f&&Md(e,d,f,a.timeStamp,!0)?(a.preventDefault(),P(b,ka,f)):Fd=f,Ed=a.timeStamp;else switch(a.preventDefault(),
c){case "insertFromYank":case "insertFromDrop":case "insertReplacementText":P(b,ka,a);break;case "insertFromComposition":H(null);P(b,ka,a);break;case "insertLineBreak":H(null);P(b,fa,!1);break;case "insertParagraph":H(null);Jd&&!$a?(Jd=!1,P(b,fa,!1)):P(b,ha,void 0);break;case "insertFromPaste":case "insertFromPasteAsQuotation":P(b,ma,a);break;case "deleteByComposition":Rd(h,g)&&P(b,na,a);break;case "deleteByDrag":case "deleteByCut":P(b,na,a);break;case "deleteContent":P(b,ea,!1);break;case "deleteWordBackward":P(b,
pa,!0);break;case "deleteWordForward":P(b,pa,!1);break;case "deleteHardLineBackward":case "deleteSoftLineBackward":P(b,qa,!0);break;case "deleteContentForward":case "deleteHardLineForward":case "deleteSoftLineForward":P(b,qa,!1);break;case "formatStrikeThrough":P(b,ra,"strikethrough");break;case "formatBold":P(b,ra,"bold");break;case "formatItalic":P(b,ra,"italic");break;case "formatUnderline":P(b,ra,"underline");break;case "historyUndo":P(b,sa,void 0);break;case "historyRedo":P(b,ta,void 0)}}})}
function yd(a,b){a.stopPropagation();w(b,()=>{var c=v(),d=a.data,e=Qd(a);if(null!=d&&C(c)&&Md(c,e,d,a.timeStamp,!1)){Kd&&(Sd(b,d),Kd=!1);var f=c.anchor,g=f.getNode();e=wb(b._window);if(null===e)return;let h=f.offset;if(f=Ya&&!c.isCollapsed()&&B(g)&&null!==e.anchorNode)g=g.getTextContent().slice(0,h)+d+g.getTextContent().slice(h+c.focus.offset),e=e.anchorNode,f=g===(3===e.nodeType?e.nodeValue:null);f||P(b,ka,d);d=d.length;Xa&&1<d&&"insertCompositionText"===a.inputType&&!b.isComposing()&&(c.anchor.offset-=
d);Za||$a||bb||!b.isComposing()||(Cd=0,H(null))}else oc(!1,b,null!==d?d:void 0),Kd&&(Sd(b,d||void 0),Kd=!1);G();c=F();Bb(c)});Fd=null}function wd(a,b){w(b,()=>{let c=v();if(C(c)&&!b.isComposing()){let d=c.anchor,e=c.anchor.getNode();H(d.key);(a.timeStamp<Cd+30||"element"===d.type||!c.isCollapsed()||e.getFormat()!==c.format||e.getStyle()!==c.style)&&P(b,ka,db)}})}
function Sd(a,b){var c=a._compositionKey;H(null);if(null!==c&&null!=b){if(""===b){b=I(c);a=Wb(a.getElementByKey(c));null!==a&&null!==a.nodeValue&&B(b)&&xb(b,a.nodeValue,null,null,!0);return}if("\n"===b[b.length-1]&&(c=v(),C(c))){b=c.focus;c.anchor.set(b.key,b.offset,b.type);P(a,Ca,null);return}}oc(!0,a,b)}function xd(a,b){Xa?Kd=!0:w(b,()=>{Sd(b,a.data)})}
function ud(a,b){Cd=a.timeStamp;Dd=a.keyCode;if(!b.isComposing()){var {keyCode:c,shiftKey:d,ctrlKey:e,metaKey:f,altKey:g}=a;if(!P(b,ua,a)){if(39!==c||e||f||g)if(39!==c||g||d||!e&&!f)if(37!==c||e||f||g)if(37!==c||g||d||!e&&!f)if(38!==c||e||f)if(40!==c||e||f)if(13===c&&d)Jd=!0,P(b,Ca,a);else if(32===c)P(b,Fa,a);else if(t&&e&&79===c)a.preventDefault(),Jd=!0,P(b,fa,!0);else if(13!==c||d){var h=t?g||f?!1:8===c||72===c&&e:e||g||f?!1:8===c;h?8===c?P(b,Ga,a):(a.preventDefault(),P(b,ea,!0)):27===c?P(b,Ha,
a):(h=t?d||g||f?!1:46===c||68===c&&e:e||g||f?!1:46===c,h?46===c?P(b,Ia,a):(a.preventDefault(),P(b,ea,!1)):8===c&&(t?g:e)?(a.preventDefault(),P(b,pa,!0)):46===c&&(t?g:e)?(a.preventDefault(),P(b,pa,!1)):t&&f&&8===c?(a.preventDefault(),P(b,qa,!0)):t&&f&&46===c?(a.preventDefault(),P(b,qa,!1)):66===c&&!g&&(t?f:e)?(a.preventDefault(),P(b,ra,"bold")):85===c&&!g&&(t?f:e)?(a.preventDefault(),P(b,ra,"underline")):73===c&&!g&&(t?f:e)?(a.preventDefault(),P(b,ra,"italic")):9!==c||g||e||f?90===c&&!d&&(t?f:e)?(a.preventDefault(),
P(b,sa,void 0)):(h=t?90===c&&f&&d:89===c&&e||90===c&&e&&d,h?(a.preventDefault(),P(b,ta,void 0)):Td(b._editorState._selection)?(h=d?!1:67===c?t?f:e:!1,h?(a.preventDefault(),P(b,Oa,a)):(h=d?!1:88===c?t?f:e:!1,h?(a.preventDefault(),P(b,Pa,a)):65===c&&(t?f:e)&&(a.preventDefault(),P(b,Qa,a)))):!Xa&&65===c&&(t?f:e)&&(a.preventDefault(),P(b,Qa,a))):P(b,Ja,a))}else Jd=!1,P(b,Ca,a);else P(b,Ba,a);else P(b,Aa,a);else P(b,za,a);else P(b,ya,a);else P(b,xa,a);else P(b,va,a);(e||d||g||f)&&P(b,Ta,a)}}}
function Ud(a){let b=a.__lexicalEventHandles;void 0===b&&(b=[],a.__lexicalEventHandles=b);return b}let Vd=new Map;function Wd(a){a=a.target;let b=wb(null==a?null:9===a.nodeType?a.defaultView:a.ownerDocument.defaultView);if(null!==b){var c=Nb(b.anchorNode);if(null!==c){Id&&(Id=!1,w(c,()=>{var g=pc(),h=b.anchorNode;null!==h&&(h=h.nodeType,1===h||3===h)&&(g=Pd(g,b,c),zb(g))}));a=mc(c);a=a[a.length-1];var d=a._key,e=Vd.get(d),f=e||a;f!==c&&Od(b,f,!1);Od(b,c,!0);c!==a?Vd.set(d,c):e&&Vd.delete(d)}}}
function Xd(a,b){0===Gd&&a.ownerDocument.addEventListener("selectionchange",Wd);Gd++;a.__lexicalEditor=b;let c=Ud(a);for(let d=0;d<Ad.length;d++){let [e,f]=Ad[d],g="function"===typeof f?h=>{!0!==h._lexicalHandled&&(h._lexicalHandled=!0,b.isEditable()&&f(h,b))}:h=>{if(!0!==h._lexicalHandled&&(h._lexicalHandled=!0,b.isEditable()))switch(e){case "cut":return P(b,Pa,h);case "copy":return P(b,Oa,h);case "paste":return P(b,ma,h);case "dragstart":return P(b,La,h);case "dragover":return P(b,Ma,h);case "dragend":return P(b,
Na,h);case "focus":return P(b,Ra,h);case "blur":return P(b,Sa,h);case "drop":return P(b,Ka,h)}};a.addEventListener(e,g);c.push(()=>{a.removeEventListener(e,g)})}}
function Yd(a,b,c){G();var d=a.__key;let e=a.getParent();if(null!==e){var f=v();if(C(f)&&D(a)){var {anchor:g,focus:h}=f;var k=g.getNode();var n=h.getNode();xc(k,a)&&g.set(a.__key,0,"element");xc(n,a)&&h.set(a.__key,0,"element")}k=f;n=!1;if(C(k)&&b){f=k.anchor;let m=k.focus;f.key===d&&(Zd(f,a,e,a.getPreviousSibling(),a.getNextSibling()),n=!0);m.key===d&&(Zd(m,a,e,a.getPreviousSibling(),a.getNextSibling()),n=!0)}else Td(k)&&b&&a.isSelected()&&a.selectPrevious();C(k)&&b&&!n?(d=a.getIndexWithinParent(),
cc(a),$d(k,e,d,-1)):cc(a);c||L(e)||e.canBeEmpty()||!e.isEmpty()||Yd(e,b);b&&K(e)&&e.isEmpty()&&e.selectEnd()}}
class ae{static getType(){q(64,this.name)}static clone(){q(65,this.name)}constructor(a){this.__type=this.constructor.getType();this.__next=this.__prev=this.__parent=null;$b(this,a)}getType(){return this.__type}isAttached(){for(var a=this.__key;null!==a;){if("root"===a)return!0;a=I(a);if(null===a)break;a=a.__parent}return!1}isSelected(a){a=a||v();if(null==a)return!1;let b=a.getNodes().some(c=>c.__key===this.__key);return B(this)?b:C(a)&&"element"===a.anchor.type&&"element"===a.focus.type&&a.anchor.key===
a.focus.key&&a.anchor.offset===a.focus.offset?!1:b}getKey(){return this.__key}getIndexWithinParent(){var a=this.getParent();if(null===a)return-1;a=a.getFirstChild();let b=0;for(;null!==a;){if(this.is(a))return b;b++;a=a.getNextSibling()}return-1}getParent(){let a=this.getLatest().__parent;return null===a?null:I(a)}getParentOrThrow(){let a=this.getParent();null===a&&q(66,this.__key);return a}getTopLevelElement(){let a=this;for(;null!==a;){let b=a.getParent();if(L(b))return a;a=b}return null}getTopLevelElementOrThrow(){let a=
this.getTopLevelElement();null===a&&q(67,this.__key);return a}getParents(){let a=[],b=this.getParent();for(;null!==b;)a.push(b),b=b.getParent();return a}getParentKeys(){let a=[],b=this.getParent();for(;null!==b;)a.push(b.__key),b=b.getParent();return a}getPreviousSibling(){let a=this.getLatest().__prev;return null===a?null:I(a)}getPreviousSiblings(){let a=[];var b=this.getParent();if(null===b)return a;for(b=b.getFirstChild();null!==b&&!b.is(this);)a.push(b),b=b.getNextSibling();return a}getNextSibling(){let a=
this.getLatest().__next;return null===a?null:I(a)}getNextSiblings(){let a=[],b=this.getNextSibling();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getCommonAncestor(a){let b=this.getParents();var c=a.getParents();D(this)&&b.unshift(this);D(a)&&c.unshift(a);a=b.length;var d=c.length;if(0===a||0===d||b[a-1]!==c[d-1])return null;c=new Set(c);for(d=0;d<a;d++){let e=b[d];if(c.has(e))return e}return null}is(a){return null==a?!1:this.__key===a.__key}isBefore(a){if(this===a)return!1;if(a.isParentOf(this))return!0;
if(this.isParentOf(a))return!1;var b=this.getCommonAncestor(a);let c=this;for(;;){var d=c.getParentOrThrow();if(d===b){d=c.getIndexWithinParent();break}c=d}for(c=a;;){a=c.getParentOrThrow();if(a===b){b=c.getIndexWithinParent();break}c=a}return d<b}isParentOf(a){let b=this.__key;if(b===a.__key)return!1;for(;null!==a;){if(a.__key===b)return!0;a=a.getParent()}return!1}getNodesBetween(a){let b=this.isBefore(a),c=[],d=new Set;for(var e=this;;){var f=e.__key;d.has(f)||(d.add(f),c.push(e));if(e===a)break;
f=D(e)?b?e.getFirstChild():e.getLastChild():null;if(null!==f)e=f;else if(f=b?e.getNextSibling():e.getPreviousSibling(),null!==f)e=f;else{e=e.getParentOrThrow();d.has(e.__key)||c.push(e);if(e===a)break;f=e;do null===f&&q(68),e=b?f.getNextSibling():f.getPreviousSibling(),f=f.getParent(),null!==f&&(null!==e||d.has(f.__key)||c.push(f));while(null===e)}}b||c.reverse();return c}isDirty(){let a=F()._dirtyLeaves;return null!==a&&a.has(this.__key)}getLatest(){let a=I(this.__key);null===a&&q(113);return a}getWritable(){G();
var a=bc(),b=F();a=a._nodeMap;let c=this.__key,d=this.getLatest(),e=d.__parent;b=b._cloneNotNeeded;var f=v();null!==f&&(f._cachedNodes=null);if(b.has(c))return dc(d),d;f=d.constructor.clone(d);f.__parent=e;f.__next=d.__next;f.__prev=d.__prev;D(d)&&D(f)?(f.__first=d.__first,f.__last=d.__last,f.__size=d.__size,f.__indent=d.__indent,f.__format=d.__format,f.__dir=d.__dir):B(d)&&B(f)&&(f.__format=d.__format,f.__style=d.__style,f.__mode=d.__mode,f.__detail=d.__detail);b.add(c);f.__key=c;dc(f);a.set(c,f);
return f}getTextContent(){return""}getTextContentSize(){return this.getTextContent().length}createDOM(){q(70)}updateDOM(){q(71)}exportDOM(a){return{element:this.createDOM(a._config,a)}}exportJSON(){q(72)}static importJSON(){q(18,this.name)}static transform(){return null}remove(a){Yd(this,!0,a)}replace(a,b){G();var c=v();null!==c&&(c=c.clone());Bc(this,a);let d=this.getLatest(),e=this.__key,f=a.__key,g=a.getWritable();a=this.getParentOrThrow().getWritable();let h=a.__size;cc(g);let k=d.getPreviousSibling(),
n=d.getNextSibling(),m=d.__prev,p=d.__next,l=d.__parent;Yd(d,!1,!0);null===k?a.__first=f:k.getWritable().__next=f;g.__prev=m;null===n?a.__last=f:n.getWritable().__prev=f;g.__next=p;g.__parent=l;a.__size=h;b&&this.getChildren().forEach(r=>{g.append(r)});C(c)&&(zb(c),b=c.anchor,c=c.focus,b.key===e&&be(b,g),c.key===e&&be(c,g));ec()===e&&H(f);return g}insertAfter(a,b=!0){G();Bc(this,a);var c=this.getWritable();let d=a.getWritable();var e=d.getParent();let f=v();var g=!1,h=!1;if(null!==e){var k=a.getIndexWithinParent();
cc(d);C(f)&&(h=e.__key,g=f.anchor,e=f.focus,g="element"===g.type&&g.key===h&&g.offset===k+1,h="element"===e.type&&e.key===h&&e.offset===k+1)}e=this.getNextSibling();k=this.getParentOrThrow().getWritable();let n=d.__key,m=c.__next;null===e?k.__last=n:e.getWritable().__prev=n;k.__size++;c.__next=n;d.__next=m;d.__prev=c.__key;d.__parent=c.__parent;b&&C(f)&&(b=this.getIndexWithinParent(),$d(f,k,b+1),c=k.__key,g&&f.anchor.set(c,b+2,"element"),h&&f.focus.set(c,b+2,"element"));return a}insertBefore(a,b=
!0){G();Bc(this,a);var c=this.getWritable();let d=a.getWritable(),e=d.__key;cc(d);let f=this.getPreviousSibling(),g=this.getParentOrThrow().getWritable(),h=c.__prev,k=this.getIndexWithinParent();null===f?g.__first=e:f.getWritable().__next=e;g.__size++;c.__prev=e;d.__prev=h;d.__next=c.__key;d.__parent=c.__parent;c=v();b&&C(c)&&(b=this.getParentOrThrow(),$d(c,b,k));return a}isParentRequired(){return!1}createParentElementNode(){return ce()}selectPrevious(a,b){G();let c=this.getPreviousSibling(),d=this.getParentOrThrow();
return null===c?d.select(0,0):D(c)?c.select():B(c)?c.select(a,b):(a=c.getIndexWithinParent()+1,d.select(a,a))}selectNext(a,b){G();let c=this.getNextSibling(),d=this.getParentOrThrow();return null===c?d.select():D(c)?c.select(0,0):B(c)?c.select(a,b):(a=c.getIndexWithinParent(),d.select(a,a))}markDirty(){this.getWritable()}}
class de extends ae{static getType(){return"linebreak"}static clone(a){return new de(a.__key)}constructor(a){super(a)}getTextContent(){return"\n"}createDOM(){return document.createElement("br")}updateDOM(){return!1}static importDOM(){return{br:a=>{let b=a.parentElement,c,d;return null!==b&&((c=b.firstChild)===a||c.nextSibling===a&&3===c.nodeType&&null!==(c.textContent||"").match(/^( |\t|\r?\n)+$/))&&((d=b.lastChild)===a||d.previousSibling===a&&3===d.nodeType&&null!==(d.textContent||"").match(/^( |\t|\r?\n)+$/))?
null:{conversion:ee,priority:0}}}}static importJSON(){return fe()}exportJSON(){return{type:"linebreak",version:1}}}function ee(){return{node:fe()}}function fe(){return Ac(new de)}function Zb(a){return a instanceof de}function ge(a,b){return b&16?"code":b&128?"mark":b&32?"sub":b&64?"sup":null}function he(a,b){return b&1?"strong":b&2?"em":"span"}
function ie(a,b,c,d,e){a=d.classList;d=rc(e,"base");void 0!==d&&a.add(...d);d=rc(e,"underlineStrikethrough");let f=!1,g=b&8&&b&4;var h=c&8&&c&4;void 0!==d&&(h?(f=!0,g||a.add(...d)):g&&a.remove(...d));for(let k in gb)h=gb[k],d=rc(e,k),void 0!==d&&(c&h?!f||"underline"!==k&&"strikethrough"!==k?(0===(b&h)||g&&"underline"===k||"strikethrough"===k)&&a.add(...d):b&h&&a.remove(...d):b&h&&a.remove(...d))}
function je(a,b,c){let d=b.firstChild;c=c.isComposing();a+=c?cb:"";if(null==d)b.textContent=a;else if(b=d.nodeValue,b!==a)if(c||Xa){c=b.length;let e=a.length,f=0,g=0;for(;f<c&&f<e&&b[f]===a[f];)f++;for(;g+f<c&&g+f<e&&b[c-g-1]===a[e-g-1];)g++;a=[f,c-f-g,a.slice(f,e-g)];let [h,k,n]=a;0!==k&&d.deleteData(h,k);d.insertData(h,n)}else d.nodeValue=a}function ke(a,b){b=document.createElement(b);b.appendChild(a);return b}
class le extends ae{static getType(){return"text"}static clone(a){return new le(a.__text,a.__key)}constructor(a,b){super(b);this.__text=a;this.__format=0;this.__style="";this.__detail=this.__mode=0}getFormat(){return this.getLatest().__format}getDetail(){return this.getLatest().__detail}getMode(){let a=this.getLatest();return ob[a.__mode]}getStyle(){return this.getLatest().__style}isToken(){return 1===this.getLatest().__mode}isComposing(){return this.__key===ec()}isSegmented(){return 2===this.getLatest().__mode}isDirectionless(){return 0!==
(this.getLatest().__detail&1)}isUnmergeable(){return 0!==(this.getLatest().__detail&2)}hasFormat(a){a=gb[a];return 0!==(this.getFormat()&a)}isSimpleText(){return"text"===this.__type&&0===this.__mode}getTextContent(){return this.getLatest().__text}getFormatFlags(a,b){let c=this.getLatest().__format;return Xb(c,a,b)}createDOM(a){var b=this.__format,c=ge(this,b);let d=he(this,b),e=document.createElement(null===c?d:c),f=e;this.hasFormat("code")&&e.setAttribute("spellcheck","false");null!==c&&(f=document.createElement(d),
e.appendChild(f));c=f;je(this.__text,c,this);a=a.theme.text;void 0!==a&&ie(d,0,b,c,a);b=this.__style;""!==b&&(e.style.cssText=b);return e}updateDOM(a,b,c){let d=this.__text;var e=a.__format,f=this.__format,g=ge(this,e);let h=ge(this,f);var k=he(this,e);let n=he(this,f);if((null===g?k:g)!==(null===h?n:h))return!0;if(g===h&&k!==n)return e=b.firstChild,null==e&&q(48),a=g=document.createElement(n),je(d,a,this),c=c.theme.text,void 0!==c&&ie(n,0,f,a,c),b.replaceChild(g,e),!1;k=b;null!==h&&null!==g&&(k=
b.firstChild,null==k&&q(49));je(d,k,this);c=c.theme.text;void 0!==c&&e!==f&&ie(n,e,f,k,c);f=this.__style;a.__style!==f&&(b.style.cssText=f);return!1}static importDOM(){return{"#text":()=>({conversion:me,priority:0}),b:()=>({conversion:ne,priority:0}),code:()=>({conversion:oe,priority:0}),em:()=>({conversion:oe,priority:0}),i:()=>({conversion:oe,priority:0}),s:()=>({conversion:oe,priority:0}),span:()=>({conversion:pe,priority:0}),strong:()=>({conversion:oe,priority:0}),sub:()=>({conversion:oe,priority:0}),
sup:()=>({conversion:oe,priority:0}),u:()=>({conversion:oe,priority:0})}}static importJSON(a){let b=J(a.text);b.setFormat(a.format);b.setDetail(a.detail);b.setMode(a.mode);b.setStyle(a.style);return b}exportDOM(a){({element:a}=super.exportDOM(a));null!==a&&(this.hasFormat("bold")&&(a=ke(a,"b")),this.hasFormat("italic")&&(a=ke(a,"i")),this.hasFormat("strikethrough")&&(a=ke(a,"s")),this.hasFormat("underline")&&(a=ke(a,"u")));return{element:a}}exportJSON(){return{detail:this.getDetail(),format:this.getFormat(),
mode:this.getMode(),style:this.getStyle(),text:this.getTextContent(),type:"text",version:1}}selectionTransform(){}setFormat(a){let b=this.getWritable();b.__format="string"===typeof a?gb[a]:a;return b}setDetail(a){let b=this.getWritable();b.__detail="string"===typeof a?hb[a]:a;return b}setStyle(a){let b=this.getWritable();b.__style=a;return b}toggleFormat(a){a=gb[a];return this.setFormat(this.getFormat()^a)}toggleDirectionless(){let a=this.getWritable();a.__detail^=1;return a}toggleUnmergeable(){let a=
this.getWritable();a.__detail^=2;return a}setMode(a){a=kb[a];if(this.__mode===a)return this;let b=this.getWritable();b.__mode=a;return b}setTextContent(a){if(this.__text===a)return this;let b=this.getWritable();b.__text=a;return b}select(a,b){G();let c=v();var d=this.getTextContent();let e=this.__key;"string"===typeof d?(d=d.length,void 0===a&&(a=d),void 0===b&&(b=d)):b=a=0;if(C(c))d=ec(),d!==c.anchor.key&&d!==c.focus.key||H(e),c.setTextNodeRange(this,a,this,b);else return qe(e,a,e,b,"text","text");
return c}spliceText(a,b,c,d){let e=this.getWritable(),f=e.__text,g=c.length,h=a;0>h&&(h=g+h,0>h&&(h=0));let k=v();d&&C(k)&&(a+=g,k.setTextNodeRange(e,a,e,a));b=f.slice(0,h)+c+f.slice(h+b);e.__text=b;return e}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}splitText(...a){G();var b=this.getLatest(),c=b.getTextContent(),d=b.__key,e=ec(),f=new Set(a);a=[];var g=c.length,h="";for(var k=0;k<g;k++)""!==h&&f.has(k)&&(a.push(h),h=""),h+=c[k];""!==h&&a.push(h);f=a.length;if(0===f)return[];if(a[0]===
c)return[b];var n=a[0];c=b.getParentOrThrow();k=b.getFormat();let m=b.getStyle(),p=b.__detail;g=!1;b.isSegmented()?(h=J(n),h.__format=k,h.__style=m,h.__detail=p,g=!0):(h=b.getWritable(),h.__text=n);b=v();h=[h];n=n.length;for(let u=1;u<f;u++){var l=a[u],r=l.length;l=J(l).getWritable();l.__format=k;l.__style=m;l.__detail=p;let x=l.__key;r=n+r;if(C(b)){let y=b.anchor,A=b.focus;y.key===d&&"text"===y.type&&y.offset>n&&y.offset<=r&&(y.key=x,y.offset-=n,b.dirty=!0);A.key===d&&"text"===A.type&&A.offset>n&&
A.offset<=r&&(A.key=x,A.offset-=n,b.dirty=!0)}e===d&&H(x);n=r;h.push(l)}d=this.getPreviousSibling();e=this.getNextSibling();null!==d&&dc(d);null!==e&&dc(e);d=c.getWritable();e=this.getIndexWithinParent();g?(d.splice(e,0,h),this.remove()):d.splice(e,1,h);C(b)&&$d(b,c,e,f-1);return h}mergeWithSibling(a){var b=a===this.getPreviousSibling();b||a===this.getNextSibling()||q(50);var c=this.__key;let d=a.__key,e=this.__text,f=e.length;ec()===d&&H(c);let g=v();if(C(g)){let h=g.anchor,k=g.focus;null!==h&&h.key===
d&&(re(h,b,c,a,f),g.dirty=!0);null!==k&&k.key===d&&(re(k,b,c,a,f),g.dirty=!0)}c=a.__text;this.setTextContent(b?c+e:e+c);b=this.getWritable();a.remove();return b}isTextEntity(){return!1}}
function pe(a){let b="700"===a.style.fontWeight,c="line-through"===a.style.textDecoration,d="italic"===a.style.fontStyle,e="underline"===a.style.textDecoration,f=a.style.verticalAlign;return{forChild:g=>{if(!B(g))return g;b&&g.toggleFormat("bold");c&&g.toggleFormat("strikethrough");d&&g.toggleFormat("italic");e&&g.toggleFormat("underline");"sub"===f&&g.toggleFormat("subscript");"super"===f&&g.toggleFormat("superscript");return g},node:null}}
function ne(a){let b="normal"===a.style.fontWeight;return{forChild:c=>{B(c)&&!b&&c.toggleFormat("bold");return c},node:null}}let se=new WeakMap;
function me(a){null===a.parentElement&&q(129);for(var b=a.textContent||"",c,d=a.parentNode,e=[a];null!==d&&void 0===(c=se.get(d))&&!("PRE"===d.nodeName||1===d.nodeType&&d.style.whiteSpace.startsWith("pre"));)e.push(d),d=d.parentNode;c=void 0===c?d:c;for(d=0;d<e.length;d++)se.set(e[d],c);if(null!==c){b=b.split(/(\r?\n|\t)/);a=[];e=b.length;for(c=0;c<e;c++)d=b[c],"\n"===d||"\r\n"===d?a.push(fe()):"\t"===d?a.push(te()):""!==d&&a.push(J(d));return{node:a}}b=b.replace(/\r/g,"").replace(/[ \t\n]+/g," ");
if(""===b)return{node:null};if(" "===b[0]){e=a;for(c=!0;null!==e&&null!==(e=ue(e,!1));)if(d=e.textContent||"",0<d.length){/[ \t\n]$/.test(d)&&(b=b.slice(1));c=!1;break}c&&(b=b.slice(1))}if(" "===b[b.length-1]){for(e=!0;null!==a&&null!==(a=ue(a,!0));)if(0<(a.textContent||"").replace(/^( |\t|\r?\n)+/,"").length){e=!1;break}e&&(b=b.slice(0,b.length-1))}return""===b?{node:null}:{node:J(b)}}
let ve=new RegExp(/^(a|abbr|acronym|b|cite|code|del|em|i|ins|kbd|label|output|q|ruby|s|samp|span|strong|sub|sup|time|u|tt|var)$/,"i");function ue(a,b){for(;;){for(var c=void 0;null===(c=b?a.nextSibling:a.previousSibling);)if(a=a.parentElement,null===a)return null;a=c;if(1===a.nodeType&&(c=a.style.display,""===c&&null===a.nodeName.match(ve)||""!==c&&!c.startsWith("inline")))return null;for(;null!==(c=b?a.firstChild:a.lastChild);)a=c;if(3===a.nodeType)return a;if("BR"===a.nodeName)return null}}
let we={code:"code",em:"italic",i:"italic",s:"strikethrough",strong:"bold",sub:"subscript",sup:"superscript",u:"underline"};function oe(a){let b=we[a.nodeName.toLowerCase()];return void 0===b?{node:null}:{forChild:c=>{B(c)&&!c.hasFormat(b)&&c.toggleFormat(b);return c},node:null}}function J(a=""){return Ac(new le(a))}function B(a){return a instanceof le}
class xe extends le{static getType(){return"tab"}static clone(a){let b=new xe(a.__key);b.__text=a.__text;b.__format=a.__format;b.__style=a.__style;return b}constructor(a){super("\t",a);this.__detail=2}static importDOM(){return null}static importJSON(a){let b=te();b.setFormat(a.format);b.setStyle(a.style);return b}exportJSON(){return{...super.exportJSON(),type:"tab",version:1}}setTextContent(){q(126)}setDetail(){q(127)}setMode(){q(128)}canInsertTextBefore(){return!1}canInsertTextAfter(){return!1}}
function te(){return Ac(new xe)}
class ye{constructor(a,b,c){this._selection=null;this.key=a;this.offset=b;this.type=c}is(a){return this.key===a.key&&this.offset===a.offset&&this.type===a.type}isBefore(a){let b=this.getNode(),c=a.getNode(),d=this.offset;a=a.offset;if(D(b)){var e=b.getDescendantByIndex(d);b=null!=e?e:b}D(c)&&(e=c.getDescendantByIndex(a),c=null!=e?e:c);return b===c?d<a:b.isBefore(c)}getNode(){let a=I(this.key);null===a&&q(20);return a}set(a,b,c){let d=this._selection,e=this.key;this.key=a;this.offset=b;this.type=c;
fc()||(ec()===e&&H(a),null!==d&&(d._cachedNodes=null,d.dirty=!0))}}function ze(a,b){let c=b.__key,d=a.offset,e="element";if(B(b))e="text",b=b.getTextContentSize(),d>b&&(d=b);else if(!D(b)){var f=b.getNextSibling();if(B(f))c=f.__key,d=0,e="text";else if(f=b.getParent())c=f.__key,d=b.getIndexWithinParent()+1}a.set(c,d,e)}function be(a,b){if(D(b)){let c=b.getLastDescendant();D(c)||B(c)?ze(a,c):ze(a,b)}else ze(a,b)}
function Ae(a,b,c,d){let e=a.getNode(),f=e.getChildAtIndex(a.offset),g=J(),h=K(e)?ce().append(g):g;g.setFormat(c);g.setStyle(d);null===f?e.append(h):(f.insertBefore(h),"element"===b.type&&b.key===a.key&&b.offset!==a.offset&&b.set(b.key,b.offset+1,"element"));a.is(b)&&b.set(g.__key,0,"text");a.set(g.__key,0,"text")}function Ke(a,b,c,d){a.key=b;a.offset=c;a.type=d}
class Le{constructor(a){this.dirty=!1;this._nodes=a;this._cachedNodes=null}is(a){if(!Td(a))return!1;let b=this._nodes,c=a._nodes;return b.size===c.size&&Array.from(b).every(d=>c.has(d))}add(a){this.dirty=!0;this._nodes.add(a);this._cachedNodes=null}delete(a){this.dirty=!0;this._nodes.delete(a);this._cachedNodes=null}clear(){this.dirty=!0;this._nodes.clear();this._cachedNodes=null}has(a){return this._nodes.has(a)}clone(){return new Le(new Set(this._nodes))}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a,
b){let c=this.getNodes(),d=c.length;var e=c[d-1];if(B(e))e=e.select();else{let f=e.getIndexWithinParent()+1;e=e.getParentOrThrow().select(f,f)}e.insertNodes(a,b);for(a=0;a<d;a++)c[a].remove();return!0}getNodes(){var a=this._cachedNodes;if(null!==a)return a;var b=this._nodes;a=[];for(let c of b)b=I(c),null!==b&&a.push(b);fc()||(this._cachedNodes=a);return a}getTextContent(){let a=this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}
function C(a){return a instanceof Me}
class Ne{constructor(a,b,c){this.gridKey=a;this.anchor=b;this.focus=c;this.dirty=!1;this._cachedNodes=null;b._selection=this;c._selection=this}is(a){return Oe(a)?this.gridKey===a.gridKey&&this.anchor.is(a.anchor)&&this.focus.is(a.focus):!1}set(a,b,c){this.dirty=!0;this.gridKey=a;this.anchor.key=b;this.focus.key=c;this._cachedNodes=null}clone(){return new Ne(this.gridKey,this.anchor,this.focus)}isCollapsed(){return!1}isBackward(){return this.focus.isBefore(this.anchor)}getCharacterOffsets(){return Pe(this)}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a,b){let c=
this.focus.getNode();return Hb(c.select(0,c.getChildrenSize())).insertNodes(a,b)}getShape(){var a=I(this.anchor.key);null===a&&q(21);var b=a.getIndexWithinParent();a=a.getParentOrThrow().getIndexWithinParent();var c=I(this.focus.key);null===c&&q(22);var d=c.getIndexWithinParent();let e=c.getParentOrThrow().getIndexWithinParent();c=Math.min(b,d);b=Math.max(b,d);d=Math.min(a,e);a=Math.max(a,e);return{fromX:Math.min(c,b),fromY:Math.min(d,a),toX:Math.max(c,b),toY:Math.max(d,a)}}getNodes(){function a(x){let {cell:y,
startColumn:A,startRow:Y}=x;h=Math.min(h,A);k=Math.min(k,Y);n=Math.max(n,A+y.__colSpan-1);m=Math.max(m,Y+y.__rowSpan-1)}var b=this._cachedNodes;if(null!==b)return b;var c=this.anchor.getNode();b=this.focus.getNode();c=Fc(c,Qe);var d=Fc(b,Qe);Qe(c)||q(103);Qe(d)||q(104);b=c.getParent();Re(b)||q(105);b=b.getParent();Se(b)||q(106);let [e,f,g]=Te(b,c,d),h=Math.min(f.startColumn,g.startColumn),k=Math.min(f.startRow,g.startRow),n=Math.max(f.startColumn+f.cell.__colSpan-1,g.startColumn+g.cell.__colSpan-
1),m=Math.max(f.startRow+f.cell.__rowSpan-1,g.startRow+g.cell.__rowSpan-1);c=h;d=k;for(var p=h,l=k;h<c||k<d||n>p||m>l;){if(h<c){var r=l-d;--c;for(var u=0;u<=r;u++)a(e[d+u][c])}if(k<d)for(r=p-c,--d,u=0;u<=r;u++)a(e[d][c+u]);if(n>p)for(r=l-d,p+=1,u=0;u<=r;u++)a(e[d+u][p]);if(m>l)for(r=p-c,l+=1,u=0;u<=r;u++)a(e[l][c+u])}b=[b];c=null;for(d=k;d<=m;d++)for(p=h;p<=n;p++)({cell:l}=e[d][p]),r=l.getParent(),Re(r)||q(107),r!==c&&b.push(r),b.push(l,...Gc(l)),c=r;fc()||(this._cachedNodes=b);return b}getTextContent(){let a=
this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}function Oe(a){return a instanceof Ne}
class Me{constructor(a,b,c,d){this.anchor=a;this.focus=b;this.dirty=!1;this.format=c;this.style=d;this._cachedNodes=null;a._selection=this;b._selection=this}is(a){return C(a)?this.anchor.is(a.anchor)&&this.focus.is(a.focus)&&this.format===a.format&&this.style===a.style:!1}isBackward(){return this.focus.isBefore(this.anchor)}isCollapsed(){return this.anchor.is(this.focus)}getNodes(){var a=this._cachedNodes;if(null!==a)return a;a=this.anchor;var b=this.focus,c=a.isBefore(b),d=c?a:b;c=c?b:a;a=d.getNode();
b=c.getNode();let e=d.offset;d=c.offset;D(a)&&(c=a.getDescendantByIndex(e),a=null!=c?c:a);D(b)&&(c=b.getDescendantByIndex(d),null!==c&&c!==a&&b.getChildAtIndex(d)===c&&(c=c.getPreviousSibling()),b=null!=c?c:b);a=a.is(b)?D(a)&&0<a.getChildrenSize()?[]:[a]:a.getNodesBetween(b);fc()||(this._cachedNodes=a);return a}setTextNodeRange(a,b,c,d){Ke(this.anchor,a.__key,b,"text");Ke(this.focus,c.__key,d,"text");this._cachedNodes=null;this.dirty=!0}getTextContent(){let a=this.getNodes();if(0===a.length)return"";
let b=a[0],c=a[a.length-1],d=this.anchor,e=this.focus,f=d.isBefore(e),[g,h]=Pe(this),k="",n=!0;for(let m=0;m<a.length;m++){let p=a[m];if(D(p)&&!p.isInline())n||(k+="\n"),n=p.isEmpty()?!1:!0;else if(n=!1,B(p)){let l=p.getTextContent();if(p===b)if(p===c){if("element"!==d.type||"element"!==e.type||e.offset===d.offset)l=g<h?l.slice(g,h):l.slice(h,g)}else l=f?l.slice(g):l.slice(h);else p===c&&(l=f?l.slice(0,h):l.slice(0,g));k+=l}else!z(p)&&!Zb(p)||p===c&&this.isCollapsed()||(k+=p.getTextContent())}return k}applyDOMRange(a){let b=
F(),c=b.getEditorState()._selection;a=Ue(a.startContainer,a.startOffset,a.endContainer,a.endOffset,b,c);if(null!==a){var [d,e]=a;Ke(this.anchor,d.key,d.offset,d.type);Ke(this.focus,e.key,e.offset,e.type);this._cachedNodes=null}}clone(){let a=this.anchor,b=this.focus;return new Me(new ye(a.key,a.offset,a.type),new ye(b.key,b.offset,b.type),this.format,this.style)}toggleFormat(a){this.format=Xb(this.format,a,null);this.dirty=!0}setStyle(a){this.style=a;this.dirty=!0}hasFormat(a){return 0!==(this.format&
gb[a])}insertRawText(a){a=a.split(/(\r?\n|\t)/);let b=[],c=a.length;for(let d=0;d<c;d++){let e=a[d];"\n"===e||"\r\n"===e?b.push(fe()):"\t"===e?b.push(te()):b.push(J(e))}this.insertNodes(b)}insertText(a){var b=this.anchor,c=this.focus,d=this.isCollapsed()||b.isBefore(c),e=this.format,f=this.style;d&&"element"===b.type?Ae(b,c,e,f):d||"element"!==c.type||Ae(c,b,e,f);var g=this.getNodes(),h=g.length,k=d?c:b;c=(d?b:c).offset;var n=k.offset;b=g[0];B(b)||q(26);d=b.getTextContent().length;var m=b.getParentOrThrow(),
p=g[h-1];if(this.isCollapsed()&&c===d&&(b.isSegmented()||b.isToken()||!b.canInsertTextAfter()||!m.canInsertTextAfter()&&null===b.getNextSibling())){var l=b.getNextSibling();B(l)&&l.canInsertTextBefore()&&!Vb(l)||(l=J(),l.setFormat(e),m.canInsertTextAfter()?b.insertAfter(l):m.insertAfter(l));l.select(0,0);b=l;if(""!==a){this.insertText(a);return}}else if(this.isCollapsed()&&0===c&&(b.isSegmented()||b.isToken()||!b.canInsertTextBefore()||!m.canInsertTextBefore()&&null===b.getPreviousSibling())){l=b.getPreviousSibling();
if(!B(l)||Vb(l))l=J(),l.setFormat(e),m.canInsertTextBefore()?b.insertBefore(l):m.insertBefore(l);l.select();b=l;if(""!==a){this.insertText(a);return}}else if(b.isSegmented()&&c!==d)m=J(b.getTextContent()),m.setFormat(e),b.replace(m),b=m;else if(!(this.isCollapsed()||""===a||(l=p.getParent(),m.canInsertTextBefore()&&m.canInsertTextAfter()&&(!D(l)||l.canInsertTextBefore()&&l.canInsertTextAfter())))){this.insertText("");Ve(this.anchor,this.focus,null);this.insertText(a);return}if(1===h)if(b.isToken())a=
J(a),a.select(),b.replace(a);else{g=b.getFormat();h=b.getStyle();if(c===n&&(g!==e||h!==f))if(""===b.getTextContent())b.setFormat(e),b.setStyle(f);else{g=J(a);g.setFormat(e);g.setStyle(f);g.select();0===c?b.insertBefore(g,!1):([h]=b.splitText(c),h.insertAfter(g,!1));g.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length);return}b=b.spliceText(c,n-c,a,!0);""===b.getTextContent()?b.remove():"text"===this.anchor.type&&(b.isComposing()?this.anchor.offset-=a.length:(this.format=g,this.style=
h))}else{e=new Set([...b.getParentKeys(),...p.getParentKeys()]);l=D(b)?b:b.getParentOrThrow();f=D(p)?p:p.getParentOrThrow();m=p;if(!l.is(f)&&f.isInline()){do m=f,f=f.getParentOrThrow();while(f.isInline())}if("text"===k.type&&(0!==n||""===p.getTextContent())||"element"===k.type&&p.getIndexWithinParent()<n)if(B(p)&&!p.isToken()&&n!==p.getTextContentSize()){if(p.isSegmented()){var r=J(p.getTextContent());p.replace(r);p=r}K(k.getNode())||(p=p.spliceText(0,n,""));e.add(p.__key)}else k=p.getParentOrThrow(),
k.canBeEmpty()||1!==k.getChildrenSize()?p.remove():k.remove();else e.add(p.__key);k=f.getChildren();n=new Set(g);p=l.is(f);l=l.isInline()&&null===b.getNextSibling()?l:b;for(r=k.length-1;0<=r;r--){let u=k[r];if(u.is(b)||D(u)&&u.isParentOf(b))break;u.isAttached()&&(!n.has(u)||u.is(m)?p||l.insertAfter(u,!1):u.remove())}if(!p)for(k=f,n=null;null!==k;){f=k.getChildren();p=f.length;if(0===p||f[p-1].is(n))e.delete(k.__key),n=k;k=k.getParent()}b.isToken()?c===d?b.select():(a=J(a),a.select(),b.replace(a)):
(b=b.spliceText(c,d-c,a,!0),""===b.getTextContent()?b.remove():b.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length));for(a=1;a<h;a++)b=g[a],e.has(b.__key)||b.remove()}}removeText(){this.insertText("")}formatText(a){if(this.isCollapsed())this.toggleFormat(a),H(null);else{var b=this.getNodes(),c=[];for(var d of b)B(d)&&c.push(d);var e=c.length;if(0===e)this.toggleFormat(a),H(null);else{d=this.anchor;var f=this.focus,g=this.isBackward();b=g?f:d;d=g?d:f;var h=0,k=c[0];f="element"===
b.type?0:b.offset;"text"===b.type&&f===k.getTextContentSize()&&(h=1,k=c[1],f=0);if(null!=k){g=k.getFormatFlags(a,null);var n=e-1,m=c[n];e="text"===d.type?d.offset:m.getTextContentSize();if(k.is(m))f!==e&&(0===f&&e===k.getTextContentSize()?k.setFormat(g):(a=k.splitText(f,e),a=0===f?a[0]:a[1],a.setFormat(g),"text"===b.type&&b.set(a.__key,0,"text"),"text"===d.type&&d.set(a.__key,e-f,"text")),this.format=g);else{0!==f&&([,k]=k.splitText(f),f=0);k.setFormat(g);var p=m.getFormatFlags(a,g);0<e&&(e!==m.getTextContentSize()&&
([m]=m.splitText(e)),m.setFormat(p));for(h+=1;h<n;h++){let l=c[h];if(!l.isToken()){let r=l.getFormatFlags(a,p);l.setFormat(r)}}"text"===b.type&&b.set(k.__key,f,"text");"text"===d.type&&d.set(m.__key,e,"text");this.format=g|p}}}}}insertNodes(a,b){if(!this.isCollapsed()){var c=this.isBackward()?this.anchor:this.focus,d=c.getNode().getNextSibling();d=d?d.getKey():null;c=(c=c.getNode().getPreviousSibling())?c.getKey():null;this.removeText();if(this.isCollapsed()&&"element"===this.focus.type){if(this.focus.key===
d&&0===this.focus.offset){var e=J();this.focus.getNode().insertBefore(e)}else this.focus.key===c&&this.focus.offset===this.focus.getNode().getChildrenSize()&&(e=J(),this.focus.getNode().insertAfter(e));e&&(this.focus.set(e.__key,0,"text"),this.anchor.set(e.__key,0,"text"))}}e=this.anchor;c=e.offset;var f=e.getNode();d=f;"element"===e.type&&(e=e.getNode(),d=e.getChildAtIndex(c-1),d=null===d?e:d);e=[];var g=f.getNextSiblings(),h=L(f)?null:f.getTopLevelElementOrThrow();if(B(f))if(d=f.getTextContent().length,
0===c&&0!==d)d=f.getPreviousSibling(),d=null!==d?d:f.getParentOrThrow(),e.push(f);else if(c===d)d=f;else{if(f.isToken())return!1;[d,f]=f.splitText(c);e.push(f)}f=d;e.push(...g);g=a[0];var k=!1,n=null;for(let r=0;r<a.length;r++){var m=a[r];if(L(d)||z(d)||!D(m)||m.isInline())k&&!D(m)&&!z(m)&&L(d.getParent())&&q(28);else{if(m.is(g)){if(D(d)&&d.isEmpty()&&d.canReplaceWith(m)){d.replace(m);d=m;k=!0;continue}k=m.getFirstDescendant();if(Yb(k)){for(var p=k.getParentOrThrow();p.isInline();)p=p.getParentOrThrow();
n=p.getChildren();k=n.length;if(D(d)){var l=d.getFirstChild();for(let u=0;u<k;u++){let x=n[u];null===l?d.append(x):l.insertAfter(x);l=x}}else{for(l=k-1;0<=l;l--)d.insertAfter(n[l]);d=d.getParentOrThrow()}n=n[k-1];p.remove();k=!0;if(p.is(m))continue}}B(d)&&(null===h&&q(27),d=h)}k=!1;if(D(d)&&!d.isInline())if(n=m,z(m)&&!m.isInline())d=1===a.length&&d.canBeEmpty()&&d.isEmpty()?d.insertBefore(m,!1):d.insertAfter(m,!1);else if(D(m)){if(m.canBeEmpty()||!m.isEmpty())K(d)?(p=d.getChildAtIndex(c),null!==p?
p.insertBefore(m):d.append(m),d=m):m.isInline()?(d.append(m),d=m):d=d.insertAfter(m,!1)}else p=d.getFirstChild(),null!==p?p.insertBefore(m):d.append(m),d=m;else!D(m)||D(m)&&m.isInline()||z(d)&&!d.isInline()?(n=m,C(this)&&z(m)&&(D(d)||B(d))&&!m.isInline()?(B(d)?(p=d.getParentOrThrow(),[d]=d.splitText(c),d=d.getIndexWithinParent()+1):(p=d,d=c),[,d]=Ec(p,d),d=d.insertBefore(m)):d=d.insertAfter(m,!1)):(m=d.getParentOrThrow(),Zb(d)&&d.remove(),d=m,r--)}b&&(B(f)?f.select():(a=d.getPreviousSibling(),B(a)?
a.select():(a=d.getIndexWithinParent(),d.getParentOrThrow().select(a,a))));if(D(d)){if(a=B(n)?n:D(n)&&n.isInline()?n.getLastDescendant():d.getLastDescendant(),b||(null===a?d.select():B(a)?""===a.getTextContent()?a.selectPrevious():a.select():a.selectNext()),0!==e.length)for(b=d,a=e.length-1;0<=a;a--)c=e[a],h=c.getParentOrThrow(),!D(d)||We(c)||z(c)&&(!c.isInline()||c.isIsolated())?D(d)||We(c)?D(c)&&!c.canInsertAfter(d)?(f=h.constructor.clone(h),D(f)||q(29),f.append(c),d.insertAfter(f)):d.insertAfter(c):
(d.insertBefore(c),d=c):(b===d?d.append(c):d.insertBefore(c),d=c),h.isEmpty()&&!h.canBeEmpty()&&h.remove()}else b||(B(d)?d.select():(b=d.getParentOrThrow(),a=d.getIndexWithinParent()+1,b.select(a,a)));return!0}insertParagraph(){this.isCollapsed()||this.removeText();var a=this.anchor,b=a.offset,c=[];if("text"===a.type){var d=a.getNode();var e=d.getNextSiblings().reverse();var f=d.getParentOrThrow();var g=f.isInline(),h=g?f.getTextContentSize():d.getTextContentSize();0===b?e.push(d):(g&&(c=f.getNextSiblings()),
b===h||g&&b===d.getTextContentSize()||([,d]=d.splitText(b),e.push(d)))}else{f=a.getNode();if(L(f)){e=ce();c=f.getChildAtIndex(b);e.select();null!==c?c.insertBefore(e,!1):f.append(e);return}e=f.getChildren().slice(b).reverse()}d=e.length;if(0===b&&0<d&&f.isInline()){if(c=f.getParentOrThrow(),e=c.insertNewAfter(this,!1),D(e))for(c=c.getChildren(),f=0;f<c.length;f++)e.append(c[f])}else if(g=f.insertNewAfter(this,!1),null===g)this.insertLineBreak();else if(D(g))if(h=f.getFirstChild(),0===b&&(f.is(a.getNode())||
h&&h.is(a.getNode()))&&0<d)f.insertBefore(g);else{f=null;b=c.length;a=g.getParentOrThrow();if(0<b)for(h=0;h<b;h++)a.append(c[h]);if(0!==d)for(c=0;c<d;c++)b=e[c],null===f?g.append(b):f.insertBefore(b),f=b;g.canBeEmpty()||0!==g.getChildrenSize()?g.selectStart():(g.selectPrevious(),g.remove())}}insertLineBreak(a){let b=fe();var c=this.anchor;"element"===c.type&&(c=c.getNode(),K(c)&&this.insertParagraph());a?this.insertNodes([b],!0):this.insertNodes([b])&&b.selectNext(0,0)}getCharacterOffsets(){return Pe(this)}extract(){var a=
this.getNodes(),b=a.length,c=b-1,d=this.anchor;let e=this.focus;var f=a[0];let g=a[c],[h,k]=Pe(this);if(0===b)return[];if(1===b)return B(f)&&!this.isCollapsed()?(a=h>k?k:h,c=f.splitText(a,h>k?h:k),a=0===a?c[0]:c[1],null!=a?[a]:[]):[f];b=d.isBefore(e);B(f)&&(d=b?h:k,d===f.getTextContentSize()?a.shift():0!==d&&([,f]=f.splitText(d),a[0]=f));B(g)&&(f=g.getTextContent().length,b=b?k:h,0===b?a.pop():b!==f&&([g]=g.splitText(b),a[c]=g));return a}modify(a,b,c){var d=this.focus,e=this.anchor,f="move"===a,g=
uc(d,b);if(z(g)&&!g.isIsolated())f&&g.isKeyboardSelectable()?(b=Xe(),b.add(g.__key),zb(b)):(a=b?g.getPreviousSibling():g.getNextSibling(),B(a)?(g=a.__key,b=b?a.getTextContent().length:0,d.set(g,b,"text"),f&&e.set(g,b,"text")):(c=g.getParentOrThrow(),D(a)?(c=a.__key,g=b?a.getChildrenSize():0):(g=g.getIndexWithinParent(),c=c.__key,b||g++),d.set(c,g,"element"),f&&e.set(c,g,"element")));else if(e=F(),d=wb(e._window)){var h=e._blockCursorElement,k=e._rootElement;null===k||null===h||!D(g)||g.isInline()||
g.canBeEmpty()||Dc(h,e,k);d.modify(a,b?"backward":"forward",c);if(0<d.rangeCount&&(g=d.getRangeAt(0),e=this.anchor.getNode(),e=K(e)?e:yc(e),this.applyDOMRange(g),this.dirty=!0,!f)){f=this.getNodes();a=[];c=!1;for(h=0;h<f.length;h++)k=f[h],xc(k,e)?a.push(k):c=!0;c&&0<a.length&&(b?(b=a[0],D(b)?b.selectStart():b.getParentOrThrow().selectStart()):(b=a[a.length-1],D(b)?b.selectEnd():b.getParentOrThrow().selectEnd()));if(d.anchorNode!==g.startContainer||d.anchorOffset!==g.startOffset)b=this.focus,f=this.anchor,
d=f.key,g=f.offset,e=f.type,Ke(f,b.key,b.offset,b.type),Ke(b,d,g,e),this._cachedNodes=null}}}deleteCharacter(a){let b=this.isCollapsed();if(this.isCollapsed()){var c=this.anchor,d=this.focus,e=c.getNode();if(!a&&("element"===c.type&&D(e)&&c.offset===e.getChildrenSize()||"text"===c.type&&c.offset===e.getTextContentSize())){var f=e.getParent();f=e.getNextSibling()||(null===f?null:f.getNextSibling());if(D(f)&&f.isShadowRoot())return}f=uc(d,a);if(z(f)&&!f.isIsolated()){f.isKeyboardSelectable()&&D(e)&&
0===e.getChildrenSize()?(e.remove(),a=Xe(),a.add(f.__key),zb(a)):(f.remove(),F().dispatchCommand(ca,void 0));return}if(!a&&D(f)&&D(e)&&e.isEmpty()){e.remove();f.selectStart();return}this.modify("extend",a,"character");if(!this.isCollapsed()){f="text"===d.type?d.getNode():null;e="text"===c.type?c.getNode():null;if(null!==f&&f.isSegmented()){if(c=d.offset,d=f.getTextContentSize(),f.is(e)||a&&c!==d||!a&&0!==c){Ye(f,a,c);return}}else if(null!==e&&e.isSegmented()&&(c=c.offset,d=e.getTextContentSize(),
e.is(f)||a&&0!==c||!a&&c!==d)){Ye(e,a,c);return}e=this.anchor;f=this.focus;c=e.getNode();d=f.getNode();if(c===d&&"text"===e.type&&"text"===f.type){var g=e.offset,h=f.offset;let k=g<h;d=k?g:h;h=k?h:g;g=h-1;d!==g&&(c=c.getTextContent().slice(d,h),lc(c)||(a?f.offset=g:e.offset=g))}}else if(a&&0===c.offset&&("element"===c.type?c.getNode():c.getNode().getParentOrThrow()).collapseAtStart(this))return}this.removeText();a&&!b&&this.isCollapsed()&&"element"===this.anchor.type&&0===this.anchor.offset&&(a=this.anchor.getNode(),
a.isEmpty()&&K(a.getParent())&&0===a.getIndexWithinParent()&&a.collapseAtStart(this))}deleteLine(a){this.isCollapsed()&&("text"===this.anchor.type&&this.modify("extend",a,"lineboundary"),0===(a?this.focus:this.anchor).offset&&this.modify("extend",a,"character"));this.removeText()}deleteWord(a){this.isCollapsed()&&this.modify("extend",a,"word");this.removeText()}}function Td(a){return a instanceof Le}
function Ze(a){let b=a.offset;if("text"===a.type)return b;a=a.getNode();return b===a.getChildrenSize()?a.getTextContent().length:0}function Pe(a){let b=a.anchor;a=a.focus;return"element"===b.type&&"element"===a.type&&b.key===a.key&&b.offset===a.offset?[0,0]:[Ze(b),Ze(a)]}
function Ye(a,b,c){let d=a.getTextContent().split(/(?=\s)/g),e=d.length,f=0,g=0;for(let h=0;h<e;h++){let k=d[h],n=h===e-1;g=f;f+=k.length;if(b&&f===c||f>c||n){d.splice(h,1);n&&(g=void 0);break}}b=d.join("").trim();""===b?a.remove():(a.setTextContent(b),a.select(g,g))}
function $e(a,b,c,d){var e=b;if(1===a.nodeType){let h=!1;var f=a.childNodes,g=f.length;e===g&&(h=!0,e=g-1);let k=f[e];g=!1;k===d._blockCursorElement?(k=f[e+1],g=!0):null!==d._blockCursorElement&&e--;d=kc(k);if(B(d))e=h?d.getTextContentSize():0;else{f=kc(a);if(null===f)return null;if(D(f)){a=f.getChildAtIndex(e);if(b=D(a))b=a.getParent(),b=null===c||null===b||!b.canBeEmpty()||b!==c.getNode();b&&(c=h?a.getLastDescendant():a.getFirstDescendant(),null===c?(f=a,e=0):(a=c,f=D(a)?a:a.getParentOrThrow()));
B(a)?(d=a,f=null,e=h?a.getTextContentSize():0):a!==f&&h&&!g&&e++}else e=f.getIndexWithinParent(),e=0===b&&z(f)&&kc(a)===f?e:e+1,f=f.getParentOrThrow();if(D(f))return new ye(f.__key,e,"element")}}else d=kc(a);return B(d)?new ye(d.__key,e,"text"):null}
function af(a,b,c){var d=a.offset,e=a.getNode();0===d?(d=e.getPreviousSibling(),e=e.getParent(),b)?(c||!b)&&null===d&&D(e)&&e.isInline()&&(b=e.getPreviousSibling(),B(b)&&(a.key=b.__key,a.offset=b.getTextContent().length)):D(d)&&!c&&d.isInline()?(a.key=d.__key,a.offset=d.getChildrenSize(),a.type="element"):B(d)&&(a.key=d.__key,a.offset=d.getTextContent().length):d===e.getTextContent().length&&(d=e.getNextSibling(),e=e.getParent(),b&&D(d)&&d.isInline()?(a.key=d.__key,a.offset=0,a.type="element"):(c||
b)&&null===d&&D(e)&&e.isInline()&&!e.canInsertTextAfter()&&(b=e.getNextSibling(),B(b)&&(a.key=b.__key,a.offset=0)))}function Ve(a,b,c){if("text"===a.type&&"text"===b.type){var d=a.isBefore(b);let e=a.is(b);af(a,d,e);af(b,!d,e);e&&(b.key=a.key,b.offset=a.offset,b.type=a.type);d=F();d.isComposing()&&d._compositionKey!==a.key&&C(c)&&(d=c.anchor,c=c.focus,Ke(a,d.key,d.offset,d.type),Ke(b,c.key,c.offset,c.type))}}
function Ue(a,b,c,d,e,f){if(null===a||null===c||!Mb(e,a,c))return null;b=$e(a,b,C(f)?f.anchor:null,e);if(null===b)return null;d=$e(c,d,C(f)?f.focus:null,e);if(null===d||"element"===b.type&&"element"===d.type&&(a=kc(a),c=kc(c),z(a)&&z(c)))return null;Ve(b,d,f);return[b,d]}function We(a){return D(a)&&!a.isInline()}function qe(a,b,c,d,e,f){let g=bc();a=new Me(new ye(a,b,e),new ye(c,d,f),0,"");a.dirty=!0;return g._selection=a}function Xe(){return new Le(new Set)}
function bf(a){let b=a.getEditorState()._selection,c=wb(a._window);return Td(b)||Oe(b)?b.clone():Pd(b,c,a)}
function Pd(a,b,c){var d=c._window;if(null===d)return null;var e=d.event,f=e?e.type:void 0;d="selectionchange"===f;e=!pb&&(d||"beforeinput"===f||"compositionstart"===f||"compositionend"===f||"click"===f&&e&&3===e.detail||"drop"===f||void 0===f);let g;if(!C(a)||e){if(null===b)return null;e=b.anchorNode;f=b.focusNode;g=b.anchorOffset;b=b.focusOffset;if(d&&C(a)&&!Mb(c,e,f))return a.clone()}else return a.clone();c=Ue(e,g,f,b,c,a);if(null===c)return null;let [h,k]=c;return new Me(h,k,C(a)?a.format:0,C(a)?
a.style:"")}function v(){return bc()._selection}function pc(){return F()._editorState._selection}
function $d(a,b,c,d=1){var e=a.anchor,f=a.focus,g=e.getNode(),h=f.getNode();if(b.is(g)||b.is(h)){g=b.__key;if(a.isCollapsed()){if(b=e.offset,c<=b&&0<d||c<b&&0>d)c=Math.max(0,b+d),e.set(g,c,"element"),f.set(g,c,"element"),cf(a)}else{let n=a.isBackward();h=n?f:e;var k=h.getNode();e=n?e:f;f=e.getNode();b.is(k)&&(k=h.offset,(c<=k&&0<d||c<k&&0>d)&&h.set(g,Math.max(0,k+d),"element"));b.is(f)&&(b=e.offset,(c<=b&&0<d||c<b&&0>d)&&e.set(g,Math.max(0,b+d),"element"))}cf(a)}}
function cf(a){var b=a.anchor,c=b.offset;let d=a.focus;var e=d.offset,f=b.getNode(),g=d.getNode();if(a.isCollapsed())D(f)&&(g=f.getChildrenSize(),g=(e=c>=g)?f.getChildAtIndex(g-1):f.getChildAtIndex(c),B(g)&&(c=0,e&&(c=g.getTextContentSize()),b.set(g.__key,c,"text"),d.set(g.__key,c,"text")));else{if(D(f)){let h=f.getChildrenSize();c=(a=c>=h)?f.getChildAtIndex(h-1):f.getChildAtIndex(c);B(c)&&(f=0,a&&(f=c.getTextContentSize()),b.set(c.__key,f,"text"))}D(g)&&(c=g.getChildrenSize(),e=(b=e>=c)?g.getChildAtIndex(c-
1):g.getChildAtIndex(e),B(e)&&(g=0,b&&(g=e.getTextContentSize()),d.set(e.__key,g,"text")))}}function df(a,b){b=b.getEditorState()._selection;a=a._selection;if(C(a)){var c=a.anchor;let d=a.focus,e;"text"===c.type&&(e=c.getNode(),e.selectionTransform(b,a));"text"===d.type&&(c=d.getNode(),e!==c&&c.selectionTransform(b,a))}}
function Zd(a,b,c,d,e){let f=null,g=0,h=null;null!==d?(f=d.__key,B(d)?(g=d.getTextContentSize(),h="text"):D(d)&&(g=d.getChildrenSize(),h="element")):null!==e&&(f=e.__key,B(e)?h="text":D(e)&&(h="element"));null!==f&&null!==h?a.set(f,g,h):(g=b.getIndexWithinParent(),-1===g&&(g=c.getChildrenSize()),a.set(c.__key,g,"element"))}function re(a,b,c,d,e){"text"===a.type?(a.key=c,b||(a.offset+=e)):a.offset>d.getIndexWithinParent()&&--a.offset}
function Te(a,b,c){let d=[],e=null,f=null;a=a.getChildren();for(let m=0;m<a.length;m++){var g=a[m];Re(g)||q(108);var h=g.getChildren();g=0;for(let p of h){for(Qe(p)||q(109);void 0!==d[m]&&void 0!==d[m][g];)g++;h=m;var k=g,n=p;let l={cell:n,startColumn:k,startRow:h},r=n.__rowSpan,u=n.__colSpan;for(let x=0;x<r;x++){void 0===d[h+x]&&(d[h+x]=[]);for(let y=0;y<u;y++)d[h+x][k+y]=l}b.is(n)&&(e=l);c.is(n)&&(f=l);g+=p.__colSpan}}null===e&&q(110);null===f&&q(111);return[d,e,f]}
let S=null,T=null,Z=!1,ef=!1,ac=0,ff={characterData:!0,childList:!0,subtree:!0};function fc(){return Z||null!==S&&S._readOnly}function G(){Z&&q(13)}function bc(){null===S&&q(15);return S}function F(){null===T&&q(16);return T}function gf(a,b,c){var d=b.__type;let e=a._nodes.get(d);void 0===e&&q(30,d);a=c.get(d);void 0===a&&(a=Array.from(e.transforms),c.set(d,a));c=a.length;for(d=0;d<c&&(a[d](b),b.isAttached());d++);}
function hf(a,b){b=b._dirtyLeaves;a=a._nodeMap;for(let c of b)b=a.get(c),B(b)&&b.isAttached()&&b.isSimpleText()&&!b.isUnmergeable()&&Gb(b)}
function jf(a,b){let c=b._dirtyLeaves,d=b._dirtyElements;a=a._nodeMap;let e=ec(),f=new Map;var g=c;let h=g.size;for(var k=d,n=k.size;0<h||0<n;){if(0<h){b._dirtyLeaves=new Set;for(let m of g)g=a.get(m),B(g)&&g.isAttached()&&g.isSimpleText()&&!g.isUnmergeable()&&Gb(g),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&gf(b,g,f),c.add(m);g=b._dirtyLeaves;h=g.size;if(0<h){ac++;continue}}b._dirtyLeaves=new Set;b._dirtyElements=new Map;for(let m of k)if(k=m[0],n=m[1],"root"===k||n)g=a.get(k),void 0!==
g&&void 0!==g&&g.__key!==e&&g.isAttached()&&gf(b,g,f),d.set(k,n);g=b._dirtyLeaves;h=g.size;k=b._dirtyElements;n=k.size;ac++}b._dirtyLeaves=c;b._dirtyElements=d}function kf(a,b){var c=a.type,d=b.get(c);void 0===d&&q(17,c);c=d.klass;a.type!==c.getType()&&q(18,c.name);c=c.importJSON(a);a=a.children;if(D(c)&&Array.isArray(a))for(d=0;d<a.length;d++){let e=kf(a[d],b);c.append(e)}return c}function lf(a,b){let c=S,d=Z,e=T;S=a;Z=!0;T=null;try{return b()}finally{S=c,Z=d,T=e}}
function mf(a,b){let c=a._pendingEditorState,d=a._rootElement,e=a._headless||null===d;if(null!==c){var f=a._editorState,g=f._selection,h=c._selection,k=0!==a._dirtyType,n=S,m=Z,p=T,l=a._updating,r=a._observer,u=null;a._pendingEditorState=null;a._editorState=c;if(!e&&k&&null!==r){T=a;S=c;Z=!1;a._updating=!0;try{let E=a._dirtyType,Q=a._dirtyElements,R=a._dirtyLeaves;r.disconnect();var x=E,y=Q,A=R;N=Jc=M="";Mc=2===x;Pc=null;O=a;Kc=a._config;Lc=a._nodes;Oc=O._listeners.mutation;Qc=y;Rc=A;Sc=f._nodeMap;
bd=c._nodeMap;Nc=c._readOnly;cd=new Map(a._keyToDOMMap);let ia=new Map;dd=ia;rd("root",null);dd=cd=Kc=bd=Sc=Rc=Qc=Lc=O=void 0;u=ia}catch(E){E instanceof Error&&a._onError(E);if(ef)throw E;nf(a,null,d,c);Cb(a);a._dirtyType=2;ef=!0;mf(a,f);ef=!1;return}finally{r.observe(d,ff),a._updating=l,S=n,Z=m,T=p}}c._readOnly||(c._readOnly=!0);var Y=a._dirtyLeaves,ba=a._dirtyElements,Va=a._normalizedNodes,la=a._updateTags,Tc=a._deferred;k&&(a._dirtyType=0,a._cloneNotNeeded.clear(),a._dirtyLeaves=new Set,a._dirtyElements=
new Map,a._normalizedNodes=new Set,a._updateTags=new Set);var Be=a._decorators,Ob=a._pendingDecorators||Be,Cf=c._nodeMap,Uc;for(Uc in Ob)Cf.has(Uc)||(Ob===Be&&(Ob=gc(a)),delete Ob[Uc]);var ja=e?null:wb(a._window);if(a._editable&&null!==ja&&(k||null===h||h.dirty)){T=a;S=c;try{null!==r&&r.disconnect();if(k||null===h||h.dirty){let E=a._blockCursorElement;null!==E&&Dc(E,a,d);a:{let Q=ja.anchorNode,R=ja.focusNode,ia=ja.anchorOffset,lb=ja.focusOffset,V=document.activeElement;if(!(la.has("collaboration")&&
V!==d||null!==V&&Lb(V)))if(C(h)){var mb=h.anchor,Vc=h.focus,Ce=mb.key,Df=Vc.key,De=wc(a,Ce),Ee=wc(a,Df),Pb=mb.offset,Fe=Vc.offset,Wc=h.format,Xc=h.style,Ge=h.isCollapsed(),nb=De,Qb=Ee,Yc=!1;if("text"===mb.type){nb=Wb(De);let W=mb.getNode();Yc=W.getFormat()!==Wc||W.getStyle()!==Xc}else C(g)&&"text"===g.anchor.type&&(Yc=!0);"text"===Vc.type&&(Qb=Wb(Ee));if(null!==nb&&null!==Qb){if(Ge&&(null===g||Yc||C(g)&&(g.format!==Wc||g.style!==Xc))){var Ef=performance.now();Ld=[Wc,Xc,Pb,Ce,Ef]}if(ia===Pb&&lb===
Fe&&Q===nb&&R===Qb&&("Range"!==ja.type||!Ge)&&(null!==V&&d.contains(V)||d.focus({preventScroll:!0}),"element"!==mb.type))break a;try{ja.setBaseAndExtent(nb,Pb,Qb,Fe)}catch(W){}if(!la.has("skip-scroll-into-view")&&h.isCollapsed()&&null!==d&&d===document.activeElement){let W=h instanceof Me&&"element"===h.anchor.type?nb.childNodes[Pb]||null:0<ja.rangeCount?ja.getRangeAt(0):null;if(null!==W){let X;if(W instanceof Text){let U=document.createRange();U.selectNode(W);X=U.getBoundingClientRect()}else X=W.getBoundingClientRect();
let wa=d.ownerDocument,Da=wa.defaultView;if(null!==Da)for(var {top:Zc,bottom:$c}=X,Rb,Sb,oa=d;null!==oa;){let U=oa===wa.body;if(U)Rb=0,Sb=Db(a).innerHeight;else{let Tb=oa.getBoundingClientRect();Rb=Tb.top;Sb=Tb.bottom}let Ea=0;Zc<Rb?Ea=-(Rb-Zc):$c>Sb&&(Ea=$c-Sb);if(0!==Ea)if(U)Da.scrollBy(0,Ea);else{let Tb=oa.scrollTop;oa.scrollTop+=Ea;let He=oa.scrollTop-Tb;Zc-=He;$c-=He}if(U)break;oa=Ub(oa)}}}Hd=!0}}else null!==g&&Mb(a,Q,R)&&ja.removeAllRanges()}}a:{let E=a._blockCursorElement;if(C(h)&&h.isCollapsed()&&
"element"===h.anchor.type&&d.contains(document.activeElement)){let Q=h.anchor,R=Q.getNode(),ia=Q.offset,lb=R.getChildrenSize(),V=!1,W=null;if(ia===lb){let X=R.getChildAtIndex(ia-1);Cc(X)&&(V=!0)}else{let X=R.getChildAtIndex(ia);if(Cc(X)){let wa=X.getPreviousSibling();if(null===wa||Cc(wa))V=!0,W=a.getElementByKey(X.__key)}}if(V){let X=a.getElementByKey(R.__key);if(null===E){let wa=a._config.theme,Da=document.createElement("div");Da.contentEditable="false";Da.setAttribute("data-lexical-cursor","true");
let U=wa.blockCursor;if(void 0!==U){if("string"===typeof U){let Ea=U.split(" ");U=wa.blockCursor=Ea}void 0!==U&&Da.classList.add(...U)}a._blockCursorElement=E=Da}d.style.caretColor="transparent";null===W?X.appendChild(E):X.insertBefore(E,W);break a}}null!==E&&Dc(E,a,d)}null!==r&&r.observe(d,ff)}finally{T=p,S=n}}if(null!==u){var Ff=u;let E=Array.from(a._listeners.mutation),Q=E.length;for(let R=0;R<Q;R++){let [ia,lb]=E[R],V=Ff.get(lb);void 0!==V&&ia(V,{dirtyLeaves:Y,prevEditorState:f,updateTags:la})}}C(h)||
null===h||null!==g&&g.is(h)||a.dispatchCommand(ca,void 0);var ad=a._pendingDecorators;null!==ad&&(a._decorators=ad,a._pendingDecorators=null,of("decorator",a,!0,ad));var Gf=hc(b||f),Ie=hc(c);Gf!==Ie&&of("textcontent",a,!0,Ie);of("update",a,!0,{dirtyElements:ba,dirtyLeaves:Y,editorState:c,normalizedNodes:Va,prevEditorState:b||f,tags:la});a._deferred=[];if(0!==Tc.length){let E=a._updating;a._updating=!0;try{for(let Q=0;Q<Tc.length;Q++)Tc[Q]()}finally{a._updating=E}}var Je=a._updates;if(0!==Je.length){let E=
Je.shift();if(E){let [Q,R]=E;pf(a,Q,R)}}}}function of(a,b,c,...d){let e=b._updating;b._updating=c;try{let f=Array.from(b._listeners[a]);for(a=0;a<f.length;a++)f[a].apply(null,d)}finally{b._updating=e}}
function P(a,b,c){if(!1===a._updating||T!==a){let f=!1;a.update(()=>{f=P(a,b,c)});return f}let d=mc(a);for(let f=4;0<=f;f--)for(let g=0;g<d.length;g++){var e=d[g]._commands.get(b);if(void 0!==e&&(e=e[f],void 0!==e)){e=Array.from(e);let h=e.length;for(let k=0;k<h;k++)if(!0===e[k](c,a))return!0}}return!1}
function qf(a,b){let c=a._updates;for(b=b||!1;0!==c.length;){var d=c.shift();if(d){let [e,f]=d,g;void 0!==f&&(d=f.onUpdate,g=f.tag,f.skipTransforms&&(b=!0),d&&a._deferred.push(d),g&&a._updateTags.add(g));e()}}return b}
function pf(a,b,c){let d=a._updateTags;var e,f=e=!1;if(void 0!==c){var g=c.onUpdate;e=c.tag;null!=e&&d.add(e);e=c.skipTransforms||!1;f=c.discrete||!1}g&&a._deferred.push(g);c=a._editorState;g=a._pendingEditorState;let h=!1;if(null===g||g._readOnly)g=a._pendingEditorState=new rf(new Map((g||c)._nodeMap)),h=!0;g._flushSync=f;f=S;let k=Z,n=T,m=a._updating;S=g;Z=!1;a._updating=!0;T=a;try{h&&(a._headless?null!=c._selection&&(g._selection=c._selection.clone()):g._selection=bf(a));let p=a._compositionKey;
b();e=qf(a,e);df(g,a);0!==a._dirtyType&&(e?hf(g,a):jf(g,a),qf(a),Ic(c,g,a._dirtyLeaves,a._dirtyElements));p!==a._compositionKey&&(g._flushSync=!0);let l=g._selection;if(C(l)){let r=g._nodeMap,u=l.focus.key;void 0!==r.get(l.anchor.key)&&void 0!==r.get(u)||q(19)}else Td(l)&&0===l._nodes.size&&(g._selection=null)}catch(p){p instanceof Error&&a._onError(p);a._pendingEditorState=c;a._dirtyType=2;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();mf(a);return}finally{S=f,Z=k,T=n,
a._updating=m,ac=0}0!==a._dirtyType||sf(g,a)?g._flushSync?(g._flushSync=!1,mf(a)):h&&Kb(()=>{mf(a)}):(g._flushSync=!1,h&&(d.clear(),a._deferred=[],a._pendingEditorState=null))}function w(a,b,c){a._updating?a._updates.push([b,c]):pf(a,b,c)}class tf extends ae{constructor(a){super(a)}decorate(){q(47)}isIsolated(){return!1}isInline(){return!0}isKeyboardSelectable(){return!0}}function z(a){return a instanceof tf}
class uf extends ae{constructor(a){super(a);this.__last=this.__first=null;this.__indent=this.__format=this.__size=0;this.__dir=null}getFormat(){return this.getLatest().__format}getFormatType(){let a=this.getFormat();return jb[a]||""}getIndent(){return this.getLatest().__indent}getChildren(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getChildrenKeys(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b.__key),b=b.getNextSibling();return a}getChildrenSize(){return this.getLatest().__size}isEmpty(){return 0===
this.getChildrenSize()}isDirty(){let a=F()._dirtyElements;return null!==a&&a.has(this.__key)}isLastChild(){let a=this.getLatest(),b=this.getParentOrThrow().getLastChild();return null!==b&&b.is(a)}getAllTextNodes(){let a=[],b=this.getFirstChild();for(;null!==b;){B(b)&&a.push(b);if(D(b)){let c=b.getAllTextNodes();a.push(...c)}b=b.getNextSibling()}return a}getFirstDescendant(){let a=this.getFirstChild();for(;null!==a;){if(D(a)){let b=a.getFirstChild();if(null!==b){a=b;continue}}break}return a}getLastDescendant(){let a=
this.getLastChild();for(;null!==a;){if(D(a)){let b=a.getLastChild();if(null!==b){a=b;continue}}break}return a}getDescendantByIndex(a){let b=this.getChildren(),c=b.length;if(a>=c)return a=b[c-1],D(a)&&a.getLastDescendant()||a||null;a=b[a];return D(a)&&a.getFirstDescendant()||a||null}getFirstChild(){let a=this.getLatest().__first;return null===a?null:I(a)}getFirstChildOrThrow(){let a=this.getFirstChild();null===a&&q(45,this.__key);return a}getLastChild(){let a=this.getLatest().__last;return null===
a?null:I(a)}getLastChildOrThrow(){let a=this.getLastChild();null===a&&q(96,this.__key);return a}getChildAtIndex(a){var b=this.getChildrenSize();let c;if(a<b/2){c=this.getFirstChild();for(b=0;null!==c&&b<=a;){if(b===a)return c;c=c.getNextSibling();b++}return null}c=this.getLastChild();for(--b;null!==c&&b>=a;){if(b===a)return c;c=c.getPreviousSibling();b--}return null}getTextContent(){let a="",b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContent();D(e)&&d!==c-1&&!e.isInline()&&
(a+="\n\n")}return a}getTextContentSize(){let a=0,b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContentSize();D(e)&&d!==c-1&&!e.isInline()&&(a+=2)}return a}getDirection(){return this.getLatest().__dir}hasFormat(a){return""!==a?(a=ib[a],0!==(this.getFormat()&a)):!1}select(a,b){G();let c=v(),d=a,e=b;var f=this.getChildrenSize();if(!this.canBeEmpty())if(0===a&&0===b){if(a=this.getFirstChild(),B(a)||D(a))return a.select(0,0)}else if(!(void 0!==a&&a!==f||void 0!==b&&b!==f)&&
(a=this.getLastChild(),B(a)||D(a)))return a.select();void 0===d&&(d=f);void 0===e&&(e=f);f=this.__key;if(C(c))c.anchor.set(f,d,"element"),c.focus.set(f,e,"element"),c.dirty=!0;else return qe(f,d,f,e,"element","element");return c}selectStart(){let a=this.getFirstDescendant();return D(a)||B(a)?a.select(0,0):null!==a?a.selectPrevious():this.select(0,0)}selectEnd(){let a=this.getLastDescendant();return D(a)||B(a)?a.select():null!==a?a.selectNext():this.select()}clear(){let a=this.getWritable();this.getChildren().forEach(b=>
b.remove());return a}append(...a){return this.splice(this.getChildrenSize(),0,a)}setDirection(a){let b=this.getWritable();b.__dir=a;return b}setFormat(a){this.getWritable().__format=""!==a?ib[a]:0;return this}setIndent(a){this.getWritable().__indent=a;return this}splice(a,b,c){let d=c.length,e=this.getChildrenSize(),f=this.getWritable(),g=f.__key;var h=[],k=[];let n=this.getChildAtIndex(a+b),m=null,p=e-b+d;if(0!==a)if(a===e)m=this.getLastChild();else{var l=this.getChildAtIndex(a);null!==l&&(m=l.getPreviousSibling())}if(0<
b){var r=null===m?this.getFirstChild():m.getNextSibling();for(l=0;l<b;l++){null===r&&q(100);var u=r.getNextSibling(),x=r.__key;r=r.getWritable();cc(r);k.push(x);r=u}}l=m;for(u=0;u<d;u++){x=c[u];null!==l&&x.is(l)&&(m=l=l.getPreviousSibling());r=x.getWritable();r.__parent===g&&p--;cc(r);let y=x.__key;null===l?(f.__first=y,r.__prev=null):(l=l.getWritable(),l.__next=y,r.__prev=l.__key);x.__key===g&&q(76);r.__parent=g;h.push(y);l=x}a+b===e?null!==l&&(l.getWritable().__next=null,f.__last=l.__key):null!==
n&&(a=n.getWritable(),null!==l?(b=l.getWritable(),a.__prev=l.__key,b.__next=n.__key):a.__prev=null);f.__size=p;if(k.length&&(a=v(),C(a))){k=new Set(k);h=new Set(h);let {anchor:y,focus:A}=a;vf(y,k,h)&&Zd(y,y.getNode(),this,m,n);vf(A,k,h)&&Zd(A,A.getNode(),this,m,n);0!==p||this.canBeEmpty()||L(this)||this.remove()}return f}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"element",version:1}}insertNewAfter(){return null}canIndent(){return!0}collapseAtStart(){return!1}excludeFromCopy(){return!1}canExtractContents(){return!0}canReplaceWith(){return!0}canInsertAfter(){return!0}canBeEmpty(){return!0}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}isInline(){return!1}isShadowRoot(){return!1}canMergeWith(){return!1}extractWithChild(){return!1}}
function D(a){return a instanceof uf}function vf(a,b,c){for(a=a.getNode();a;){let d=a.__key;if(b.has(d)&&!c.has(d))return!0;a=a.getParent()}return!1}
class wf extends uf{static getType(){return"root"}static clone(){return new wf}constructor(){super("root");this.__cachedText=null}getTopLevelElementOrThrow(){q(51)}getTextContent(){let a=this.__cachedText;return!fc()&&0!==F()._dirtyType||null===a?super.getTextContent():a}remove(){q(52)}replace(){q(53)}insertBefore(){q(54)}insertAfter(){q(55)}updateDOM(){return!1}append(...a){for(let b=0;b<a.length;b++){let c=a[b];D(c)||z(c)||q(56)}return super.append(...a)}static importJSON(a){let b=ic();b.setFormat(a.format);
b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"root",version:1}}collapseAtStart(){return!0}}function K(a){return a instanceof wf}function sf(a,b){b=b.getEditorState()._selection;a=a._selection;if(null!==a){if(a.dirty||!a.is(b))return!0}else if(null!==b)return!0;return!1}function xf(){return new rf(new Map([["root",new wf]]))}
function yf(a,b){let c=a.exportJSON();if(b)for(var d in c)b.includes(d)||delete c[d];var e=a.constructor;c.type!==e.getType()&&q(130,e.name);d=c.children;if(D(a))for(Array.isArray(d)||q(59,e.name),a=a.getChildren(),e=0;e<a.length;e++){let f=yf(a[e],b);d.push(f)}return c}
class rf{constructor(a,b){this._nodeMap=a;this._selection=b||null;this._readOnly=this._flushSync=!1}isEmpty(){return 1===this._nodeMap.size&&null===this._selection}read(a){return lf(this,a)}clone(a){a=new rf(this._nodeMap,void 0===a?this._selection:a);a._readOnly=!0;return a}toJSON(){return lf(this,()=>({root:yf(ic())}))}}
class zf extends uf{static getType(){return"paragraph"}static clone(a){return new zf(a.__key)}createDOM(a){let b=document.createElement("p");a=rc(a.theme,"paragraph");void 0!==a&&b.classList.add(...a);return b}updateDOM(){return!1}static importDOM(){return{p:()=>({conversion:Af,priority:0})}}exportDOM(a){({element:a}=super.exportDOM(a));if(a&&aa.isHTMLElement(a)){this.isEmpty()&&a.append(document.createElement("br"));var b=this.getFormatType();a.style.textAlign=b;if(b=this.getDirection())a.dir=b;
b=this.getIndent();0<b&&(a.style.textIndent=`${20*b}px`)}return{element:a}}static importJSON(a){let b=ce();b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{...super.exportJSON(),type:"paragraph",version:1}}insertNewAfter(a,b){a=ce();let c=this.getDirection();a.setDirection(c);this.insertAfter(a,b);return a}collapseAtStart(){let a=this.getChildren();if(0===a.length||B(a[0])&&""===a[0].getTextContent().trim()){if(null!==this.getNextSibling())return this.selectNext(),
this.remove(),!0;if(null!==this.getPreviousSibling())return this.selectPrevious(),this.remove(),!0}return!1}}function Af(a){let b=ce();a.style&&(b.setFormat(a.style.textAlign),a=parseInt(a.style.textIndent,10)/20,0<a&&b.setIndent(a));return{node:b}}function ce(){return Ac(new zf)}
function nf(a,b,c,d){let e=a._keyToDOMMap;e.clear();a._editorState=xf();a._pendingEditorState=d;a._compositionKey=null;a._dirtyType=0;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();a._normalizedNodes=new Set;a._updateTags=new Set;a._updates=[];a._blockCursorElement=null;d=a._observer;null!==d&&(d.disconnect(),a._observer=null);null!==b&&(b.textContent="");null!==c&&(c.textContent="",e.set("root",c))}
function Bf(a){let b=new Map,c=new Set;a.forEach(d=>{d=null!=d.klass.importDOM?d.klass.importDOM.bind(d.klass):null;if(null!=d&&!c.has(d)){c.add(d);var e=d();null!==e&&Object.keys(e).forEach(f=>{let g=b.get(f);void 0===g&&(g=[],b.set(f,g));g.push(e[f])})}});return b}
class Hf{constructor(a,b,c,d,e,f,g){this._parentEditor=b;this._rootElement=null;this._editorState=a;this._compositionKey=this._pendingEditorState=null;this._deferred=[];this._keyToDOMMap=new Map;this._updates=[];this._updating=!1;this._listeners={decorator:new Set,editable:new Set,mutation:new Map,root:new Set,textcontent:new Set,update:new Set};this._commands=new Map;this._config=d;this._nodes=c;this._decorators={};this._pendingDecorators=null;this._dirtyType=0;this._cloneNotNeeded=new Set;this._dirtyLeaves=
new Set;this._dirtyElements=new Map;this._normalizedNodes=new Set;this._updateTags=new Set;this._observer=null;this._key=nc();this._onError=e;this._htmlConversions=f;this._editable=g;this._headless=null!==b&&b._headless;this._blockCursorElement=this._window=null}isComposing(){return null!=this._compositionKey}registerUpdateListener(a){let b=this._listeners.update;b.add(a);return()=>{b.delete(a)}}registerEditableListener(a){let b=this._listeners.editable;b.add(a);return()=>{b.delete(a)}}registerDecoratorListener(a){let b=
this._listeners.decorator;b.add(a);return()=>{b.delete(a)}}registerTextContentListener(a){let b=this._listeners.textcontent;b.add(a);return()=>{b.delete(a)}}registerRootListener(a){let b=this._listeners.root;a(this._rootElement,null);b.add(a);return()=>{a(null,this._rootElement);b.delete(a)}}registerCommand(a,b,c){void 0===c&&q(35);let d=this._commands;d.has(a)||d.set(a,[new Set,new Set,new Set,new Set,new Set]);let e=d.get(a);void 0===e&&q(36,String(a));let f=e[c];f.add(b);return()=>{f.delete(b);
e.every(g=>0===g.size)&&d.delete(a)}}registerMutationListener(a,b){void 0===this._nodes.get(a.getType())&&q(37,a.name);let c=this._listeners.mutation;c.set(b,a);return()=>{c.delete(b)}}registerNodeTransformToKlass(a,b){var c=a.getType();c=this._nodes.get(c);void 0===c&&q(37,a.name);c.transforms.add(b);return c}registerNodeTransform(a,b){var c=this.registerNodeTransformToKlass(a,b);let d=[c];c=c.replaceWithKlass;null!=c&&(c=this.registerNodeTransformToKlass(c,b),d.push(c));jc(this,a.getType());return()=>
{d.forEach(e=>e.transforms.delete(b))}}hasNode(a){return this._nodes.has(a.getType())}hasNodes(a){return a.every(this.hasNode.bind(this))}dispatchCommand(a,b){return P(this,a,b)}getDecorators(){return this._decorators}getRootElement(){return this._rootElement}getKey(){return this._key}setRootElement(a){let b=this._rootElement;if(a!==b){let f=rc(this._config.theme,"root");var c=this._pendingEditorState||this._editorState;this._rootElement=a;nf(this,b,a,c);if(null!==b){if(!this._config.disableEvents){0!==
Gd&&(Gd--,0===Gd&&b.ownerDocument.removeEventListener("selectionchange",Wd));var d=b.__lexicalEditor;if(null!==d&&void 0!==d){if(null!==d._parentEditor){var e=mc(d);e=e[e.length-1]._key;Vd.get(e)===d&&Vd.delete(e)}else Vd.delete(d._key);b.__lexicalEditor=null}d=Ud(b);for(e=0;e<d.length;e++)d[e]();b.__lexicalEventHandles=[]}null!=f&&b.classList.remove(...f)}null!==a?(c=(c=a.ownerDocument)&&c.defaultView||null,d=a.style,d.userSelect="text",d.whiteSpace="pre-wrap",d.wordBreak="break-word",a.setAttribute("data-lexical-editor",
"true"),this._window=c,this._dirtyType=2,Cb(this),this._updateTags.add("history-merge"),mf(this),this._config.disableEvents||Xd(a,this),null!=f&&a.classList.add(...f)):(this._editorState=c,this._window=this._pendingEditorState=null);of("root",this,!1,a,b)}}getElementByKey(a){return this._keyToDOMMap.get(a)||null}getEditorState(){return this._editorState}setEditorState(a,b){a.isEmpty()&&q(38);Bb(this);let c=this._pendingEditorState,d=this._updateTags;b=void 0!==b?b.tag:null;null===c||c.isEmpty()||
(null!=b&&d.add(b),mf(this));this._pendingEditorState=a;this._dirtyType=2;this._dirtyElements.set("root",!1);this._compositionKey=null;null!=b&&d.add(b);mf(this)}parseEditorState(a,b){a="string"===typeof a?JSON.parse(a):a;let c=xf(),d=S,e=Z,f=T,g=this._dirtyElements,h=this._dirtyLeaves,k=this._cloneNotNeeded,n=this._dirtyType;this._dirtyElements=new Map;this._dirtyLeaves=new Set;this._cloneNotNeeded=new Set;this._dirtyType=0;S=c;Z=!1;T=this;try{kf(a.root,this._nodes),b&&b(),c._readOnly=!0}catch(m){m instanceof
Error&&this._onError(m)}finally{this._dirtyElements=g,this._dirtyLeaves=h,this._cloneNotNeeded=k,this._dirtyType=n,S=d,Z=e,T=f}return c}update(a,b){w(this,a,b)}focus(a,b={}){let c=this._rootElement;null!==c&&(c.setAttribute("autocapitalize","off"),w(this,()=>{let d=v(),e=ic();null!==d?d.dirty=!0:0!==e.getChildrenSize()&&("rootStart"===b.defaultSelection?e.selectStart():e.selectEnd())},{onUpdate:()=>{c.removeAttribute("autocapitalize");a&&a()},tag:"focus"}),null===this._pendingEditorState&&c.removeAttribute("autocapitalize"))}blur(){var a=
this._rootElement;null!==a&&a.blur();a=wb(this._window);null!==a&&a.removeAllRanges()}isEditable(){return this._editable}setEditable(a){this._editable!==a&&(this._editable=a,of("editable",this,!0,a))}toJSON(){return{editorState:this._editorState.toJSON()}}}
class If extends uf{constructor(a,b){super(b);this.__colSpan=a;this.__rowSpan=1}exportJSON(){return{...super.exportJSON(),colSpan:this.__colSpan,rowSpan:this.__rowSpan}}getColSpan(){return this.__colSpan}setColSpan(a){this.getWritable().__colSpan=a;return this}getRowSpan(){return this.__rowSpan}setRowSpan(a){this.getWritable().__rowSpan=a;return this}}function Qe(a){return a instanceof If}class Jf extends uf{}function Se(a){return a instanceof Jf}class Kf extends uf{}
function Re(a){return a instanceof Kf}exports.$addUpdateTag=function(a){G();F()._updateTags.add(a)};exports.$applyNodeReplacement=Ac;exports.$copyNode=zc;exports.$createLineBreakNode=fe;exports.$createNodeSelection=Xe;exports.$createParagraphNode=ce;exports.$createRangeSelection=function(){let a=new ye("root",0,"element"),b=new ye("root",0,"element");return new Me(a,b,0,"")};exports.$createTabNode=te;exports.$createTextNode=J;exports.$getAdjacentNode=uc;exports.$getNearestNodeFromDOMNode=vb;
exports.$getNearestRootOrShadowRoot=yc;exports.$getNodeByKey=I;exports.$getPreviousSelection=pc;exports.$getRoot=ic;exports.$getSelection=v;exports.$getTextContent=function(){let a=v();return null===a?"":a.getTextContent()};exports.$hasAncestor=xc;exports.$hasUpdateTag=function(a){return F()._updateTags.has(a)};exports.$insertNodes=function(a,b){let c=v()||pc();null===c&&(c=ic().selectEnd());return c.insertNodes(a,b)};exports.$isBlockElementNode=We;exports.$isDecoratorNode=z;
exports.$isElementNode=D;exports.$isInlineElementOrDecoratorNode=function(a){return D(a)&&a.isInline()||z(a)&&a.isInline()};exports.$isLeafNode=Yb;exports.$isLineBreakNode=Zb;exports.$isNodeSelection=Td;exports.$isParagraphNode=function(a){return a instanceof zf};exports.$isRangeSelection=C;exports.$isRootNode=K;exports.$isRootOrShadowRoot=L;exports.$isTabNode=function(a){return a instanceof xe};exports.$isTextNode=B;
exports.$nodesOfType=function(a){var b=bc();let c=b._readOnly,d=a.getType();b=b._nodeMap;let e=[];for(let [,f]of b)f instanceof a&&f.__type===d&&(c||f.isAttached())&&e.push(f);return e};exports.$normalizeSelection__EXPERIMENTAL=Hb;exports.$parseSerializedNode=function(a){return kf(a,F()._nodes)};exports.$selectAll=function(){var a=ic();a=a.select(0,a.getChildrenSize());zb(Hb(a))};exports.$setCompositionKey=H;exports.$setSelection=zb;exports.$splitNode=Ec;exports.BLUR_COMMAND=Sa;
exports.CAN_REDO_COMMAND={};exports.CAN_UNDO_COMMAND={};exports.CLEAR_EDITOR_COMMAND={};exports.CLEAR_HISTORY_COMMAND={};exports.CLICK_COMMAND=da;exports.COMMAND_PRIORITY_CRITICAL=4;exports.COMMAND_PRIORITY_EDITOR=0;exports.COMMAND_PRIORITY_HIGH=3;exports.COMMAND_PRIORITY_LOW=1;exports.COMMAND_PRIORITY_NORMAL=2;exports.CONTROLLED_TEXT_INSERTION_COMMAND=ka;exports.COPY_COMMAND=Oa;exports.CUT_COMMAND=Pa;exports.DELETE_CHARACTER_COMMAND=ea;exports.DELETE_LINE_COMMAND=qa;exports.DELETE_WORD_COMMAND=pa;
exports.DEPRECATED_$computeGridMap=Te;exports.DEPRECATED_$createGridSelection=function(){let a=new ye("root",0,"element"),b=new ye("root",0,"element");return new Ne("root",a,b)};exports.DEPRECATED_$getNodeTriplet=function(a){a instanceof If||(a instanceof ae?(a=Fc(a,Qe),Qe(a)||q(114)):(a=Fc(a.getNode(),Qe),Qe(a)||q(114)));let b=a.getParent();Re(b)||q(115);let c=b.getParent();Se(c)||q(116);return[a,b,c]};exports.DEPRECATED_$isGridCellNode=Qe;exports.DEPRECATED_$isGridNode=Se;
exports.DEPRECATED_$isGridRowNode=Re;exports.DEPRECATED_$isGridSelection=Oe;exports.DEPRECATED_GridCellNode=If;exports.DEPRECATED_GridNode=Jf;exports.DEPRECATED_GridRowNode=Kf;exports.DRAGEND_COMMAND=Na;exports.DRAGOVER_COMMAND=Ma;exports.DRAGSTART_COMMAND=La;exports.DROP_COMMAND=Ka;exports.DecoratorNode=tf;exports.ElementNode=uf;exports.FOCUS_COMMAND=Ra;exports.FORMAT_ELEMENT_COMMAND={};exports.FORMAT_TEXT_COMMAND=ra;exports.INDENT_CONTENT_COMMAND={};exports.INSERT_LINE_BREAK_COMMAND=fa;
exports.INSERT_PARAGRAPH_COMMAND=ha;exports.INSERT_TAB_COMMAND={};exports.KEY_ARROW_DOWN_COMMAND=Ba;exports.KEY_ARROW_LEFT_COMMAND=ya;exports.KEY_ARROW_RIGHT_COMMAND=va;exports.KEY_ARROW_UP_COMMAND=Aa;exports.KEY_BACKSPACE_COMMAND=Ga;exports.KEY_DELETE_COMMAND=Ia;exports.KEY_DOWN_COMMAND=ua;exports.KEY_ENTER_COMMAND=Ca;exports.KEY_ESCAPE_COMMAND=Ha;exports.KEY_MODIFIER_COMMAND=Ta;exports.KEY_SPACE_COMMAND=Fa;exports.KEY_TAB_COMMAND=Ja;exports.LineBreakNode=de;exports.MOVE_TO_END=xa;
exports.MOVE_TO_START=za;exports.OUTDENT_CONTENT_COMMAND={};exports.PASTE_COMMAND=ma;exports.ParagraphNode=zf;exports.REDO_COMMAND=ta;exports.REMOVE_TEXT_COMMAND=na;exports.RootNode=wf;exports.SELECTION_CHANGE_COMMAND=ca;exports.SELECT_ALL_COMMAND=Qa;exports.TabNode=xe;exports.TextNode=le;exports.UNDO_COMMAND=sa;exports.createCommand=function(){return{}};
exports.createEditor=function(a){var b=a||{},c=T,d=b.theme||{};let e=void 0===a?c:b.parentEditor||null,f=b.disableEvents||!1,g=xf(),h=b.namespace||(null!==e?e._config.namespace:nc()),k=b.editorState,n=[wf,le,de,xe,zf,...(b.nodes||[])],m=b.onError;b=void 0!==b.editable?b.editable:!0;if(void 0===a&&null!==c)a=c._nodes;else for(a=new Map,c=0;c<n.length;c++){let l=n[c],r=null;var p=null;"function"!==typeof l&&(p=l,l=p.replace,r=p.with,p=p.withKlass?p.withKlass:null);let u=l.getType(),x=l.transform(),
y=new Set;null!==x&&y.add(x);a.set(u,{klass:l,replace:r,replaceWithKlass:p,transforms:y})}d=new Hf(g,e,a,{disableEvents:f,namespace:h,theme:d},m?m:console.error,Bf(a),b);void 0!==k&&(d._pendingEditorState=k,d._dirtyType=2);return d};exports.getNearestEditorFromDOMNode=Nb;exports.isSelectionCapturedInDecoratorInput=Lb;exports.isSelectionWithinEditor=Mb
