/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var c=require("@lexical/react/LexicalComposerContext"),h=require("@lexical/table"),r=require("@lexical/utils"),w=require("lexical"),x=require("react");function y(m){let n=new URLSearchParams;n.append("code",m);for(let p=1;p<arguments.length;p++)n.append("v",arguments[p]);throw Error(`Minified Lexical error #${m}; visit https://lexical.dev/docs/error?${n} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}
exports.TablePlugin=function({hasCellMerge:m=!0,hasCellBackgroundColor:n=!0,hasTabHandler:p=!0}){let [d]=c.useLexicalComposerContext();x.useEffect(()=>{d.hasNodes([h.TableNode,h.TableCellNode,h.TableRowNode])||y(10);return d.registerCommand(h.INSERT_TABLE_COMMAND,({columns:a,rows:e,includeHeaders:g})=>{a=h.$createTableNodeWithDimensions(Number(e),Number(a),g);r.$insertNodeToNearestRoot(a);a=a.getFirstDescendant();w.$isTextNode(a)&&a.select();return!0},w.COMMAND_PRIORITY_EDITOR)},[d]);x.useEffect(()=>
{let a=new Map,e=b=>{const f=b.getKey(),l=d.getElementByKey(f);l&&!a.has(f)&&(b=h.applyTableHandlers(b,l,d,p),a.set(f,b))};d.getEditorState().read(()=>{let b=w.$nodesOfType(h.TableNode);for(let f of b)h.$isTableNode(f)&&e(f)});let g=d.registerMutationListener(h.TableNode,b=>{for(const [f,l]of b)"created"===l?d.getEditorState().read(()=>{const q=w.$getNodeByKey(f);h.$isTableNode(q)&&e(q)}):"destroyed"===l&&(b=a.get(f),void 0!==b&&(b.removeListeners(),a.delete(f)))});return()=>{g();for(let [,b]of a)b.removeListeners()}},
[d,p]);x.useEffect(()=>{if(!m)return d.registerNodeTransform(h.TableCellNode,a=>{if(1<a.getColSpan()||1<a.getRowSpan()){var [,,e]=w.DEPRECATED_$getNodeTriplet(a);[a]=w.DEPRECATED_$computeGridMap(e,a,a);let f=a.length,l=a[0].length;e=e.getFirstChild();if(!w.DEPRECATED_$isGridRowNode(e))throw Error("Expected TableNode first child to be a RowNode");let q=[];for(let k=0;k<f;k++){if(0!==k&&(e=e.getNextSibling(),!w.DEPRECATED_$isGridRowNode(e)))throw Error("Expected TableNode first child to be a RowNode");
let u=null;for(let t=0;t<l;t++){var g=a[k][t],b=g.cell;if(g.startRow===k&&g.startColumn===t)u=b,q.push(b);else if(1<b.getColSpan()||1<b.getRowSpan())if(b=h.$createTableCellNode(b.__headerState),null!==u)u.insertAfter(b);else{g=e;let v=g.getFirstChild();null!==v?v.insertBefore(b):g.append(b)}}}for(let k of q)k.setColSpan(1),k.setRowSpan(1)}})},[d,m]);x.useEffect(()=>{if(!n)return d.registerNodeTransform(h.TableCellNode,a=>{null!==a.getBackgroundColor()&&a.setBackgroundColor(null)})},[d,n,m]);return null}
