/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var h=require("@lexical/react/LexicalComposerContext"),r=require("lexical"),w=require("react"),x=require("@lexical/utils"),y="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?w.useLayoutEffect:w.useEffect;class z{constructor(c){this.key=c;this.ref={current:null};this.setRefElement=this.setRefElement.bind(this)}setRefElement(c){this.ref={current:c}}}
let A=c=>{const a=document.getElementById("typeahead-menu");if(a){var d=a.getBoundingClientRect();d.top+d.height>window.innerHeight&&a.scrollIntoView({block:"center"});0>d.top&&a.scrollIntoView({block:"center"});c.scrollIntoView({block:"nearest"})}};
function B(c){var a=r.$getSelection();if(!r.$isRangeSelection(a)||!a.isCollapsed())return null;var d=a.anchor;if("text"!==d.type)return null;a=d.getNode();if(!a.isSimpleText())return null;d=d.offset;let g=a.getTextContent().slice(0,d);var f=c.matchingString;c=c.replaceableString.length;for(let p=c;p<=f.length;p++)g.substr(-p)===f.substr(0,p)&&(c=p);c=d-c;if(0>c)return null;let t;0===c?[t]=a.splitText(d):[,t]=a.splitText(c,d);return t}
function C(c,a){let d=getComputedStyle(c),g="absolute"===d.position;a=a?/(auto|scroll|hidden)/:/(auto|scroll)/;if("fixed"===d.position)return document.body;for(;c=c.parentElement;)if(d=getComputedStyle(c),(!g||"static"!==d.position)&&a.test(d.overflow+d.overflowY+d.overflowX))return c;return document.body}function D(c,a){c=c.getBoundingClientRect();a=a.getBoundingClientRect();return c.top>a.top&&c.top<a.bottom}
function E(c,a,d,g){let [f]=h.useLexicalComposerContext();w.useEffect(()=>{if(null!=a&&null!=c){let t=f.getRootElement(),p=null!=t?C(t,!1):document.body,k=!1,b=D(a,p),m=function(){k||(window.requestAnimationFrame(function(){d();k=!1}),k=!0);const q=D(a,p);q!==b&&(b=q,null!=g&&g(q))},n=new ResizeObserver(d);window.addEventListener("resize",d);document.addEventListener("scroll",m,{capture:!0,passive:!0});n.observe(a);return()=>{n.unobserve(a);window.removeEventListener("resize",d);document.removeEventListener("scroll",
m)}}},[a,f,g,d,c])}let F=r.createCommand("SCROLL_TYPEAHEAD_OPTION_INTO_VIEW_COMMAND");
function G({close:c,editor:a,anchorElementRef:d,resolution:g,options:f,menuRenderFn:t,onSelectOption:p,shouldSplitNodeWithQuery:k=!1}){let [b,m]=w.useState(null);w.useEffect(()=>{m(0)},[g.match&&g.match.matchingString]);let n=w.useCallback(e=>{a.update(()=>{const l=null!=g.match&&k?B(g.match):null;p(e,l,c,g.match?g.match.matchingString:"")})},[a,k,g.match,p,c]),q=w.useCallback(e=>{const l=a.getRootElement();null!==l&&(l.setAttribute("aria-activedescendant","typeahead-item-"+e),m(e))},[a]);w.useEffect(()=>
()=>{let e=a.getRootElement();null!==e&&e.removeAttribute("aria-activedescendant")},[a]);y(()=>{null===f?m(null):null===b&&q(0)},[f,b,q]);w.useEffect(()=>x.mergeRegister(a.registerCommand(F,({option:e})=>e.ref&&null!=e.ref.current?(A(e.ref.current),!0):!1,r.COMMAND_PRIORITY_LOW)),[a,q]);w.useEffect(()=>x.mergeRegister(a.registerCommand(r.KEY_ARROW_DOWN_COMMAND,e=>{if(null!==f&&f.length&&null!==b){let l=b!==f.length-1?b+1:0;q(l);let v=f[l];null!=v.ref&&v.ref.current&&a.dispatchCommand(F,{index:l,option:v});
e.preventDefault();e.stopImmediatePropagation()}return!0},r.COMMAND_PRIORITY_LOW),a.registerCommand(r.KEY_ARROW_UP_COMMAND,e=>{if(null!==f&&f.length&&null!==b){var l=0!==b?b-1:f.length-1;q(l);l=f[l];null!=l.ref&&l.ref.current&&A(l.ref.current);e.preventDefault();e.stopImmediatePropagation()}return!0},r.COMMAND_PRIORITY_LOW),a.registerCommand(r.KEY_ESCAPE_COMMAND,e=>{e.preventDefault();e.stopImmediatePropagation();c();return!0},r.COMMAND_PRIORITY_LOW),a.registerCommand(r.KEY_TAB_COMMAND,e=>{if(null===
f||null===b||null==f[b])return!1;e.preventDefault();e.stopImmediatePropagation();n(f[b]);return!0},r.COMMAND_PRIORITY_LOW),a.registerCommand(r.KEY_ENTER_COMMAND,e=>{if(null===f||null===b||null==f[b])return!1;null!==e&&(e.preventDefault(),e.stopImmediatePropagation());n(f[b]);return!0},r.COMMAND_PRIORITY_LOW)),[n,c,a,f,b,q]);let u=w.useMemo(()=>({options:f,selectOptionAndCleanUp:n,selectedIndex:b,setHighlightedIndex:m}),[n,b,f]);return t(d,u,g.match?g.match.matchingString:"")}
function H(c,a,d){let [g]=h.useLexicalComposerContext(),f=w.useRef(document.createElement("div")),t=w.useCallback(()=>{const k=g.getRootElement(),b=f.current;var m=b.firstChild;if(null!==k&&null!==c){const {left:q,top:u,width:e,height:l}=c.getRect();b.style.top=`${u+window.pageYOffset}px`;b.style.left=`${q+window.pageXOffset}px`;b.style.height=`${l}px`;b.style.width=`${e}px`;if(null!==m){var n=m.getBoundingClientRect();m=n.height;n=n.width;const v=k.getBoundingClientRect();q+n>v.right&&(b.style.left=
`${v.right-n+window.pageXOffset}px`);(u+m>window.innerHeight||u+m>v.bottom)&&u-v.top>m&&(b.style.top=`${u-m+window.pageYOffset-(l+10)}px`)}b.isConnected||(null!=d&&(b.className=d),b.setAttribute("aria-label","Typeahead menu"),b.setAttribute("id","typeahead-menu"),b.setAttribute("role","listbox"),b.style.display="block",b.style.position="absolute",document.body.append(b));f.current=b;k.setAttribute("aria-controls","typeahead-menu")}},[g,c,d]);w.useEffect(()=>{let k=g.getRootElement();if(null!==c)return t(),
()=>{null!==k&&k.removeAttribute("aria-controls");let b=f.current;null!==b&&b.isConnected&&b.remove()}},[g,t,c]);let p=w.useCallback(k=>{null!==c&&(k||a(null))},[c,a]);E(c,f.current,t,p);return f}function I(c){w.startTransition?w.startTransition(c):c()}
exports.LexicalNodeMenuPlugin=function({options:c,nodeKey:a,onClose:d,onOpen:g,onSelectOption:f,menuRenderFn:t,anchorClassName:p}){let [k]=h.useLexicalComposerContext(),[b,m]=w.useState(null);p=H(b,m,p);let n=w.useCallback(()=>{m(null);null!=d&&null!==b&&d()},[d,b]),q=w.useCallback(e=>{m(e);null!=g&&null===b&&g(e)},[g,b]),u=w.useCallback(()=>{a?k.update(()=>{const e=r.$getNodeByKey(a),l=k.getElementByKey(a);null!=e&&null!=l&&null==b&&I(()=>q({getRect:()=>l.getBoundingClientRect()}))}):null==a&&null!=
b&&n()},[n,k,a,q,b]);w.useEffect(()=>{u()},[u,a]);w.useEffect(()=>{if(null!=a)return k.registerUpdateListener(({dirtyElements:e})=>{e.get(a)&&u()})},[k,u,a]);return null===b||null===k?null:w.createElement(G,{close:n,resolution:b,editor:k,anchorElementRef:p,options:c,menuRenderFn:t,onSelectOption:f})};exports.MenuOption=z
