/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// The literal below is regenerated by `pnpm run update-version` alongside
// the package.json version bump. In a Rollup build the
// `process.env.LEXICAL_VERSION` reference is statically replaced with the
// build-specific string (e.g. "0.44.0+prod.esm") and the fallback is dropped
// by minification; consumed as source it stays this literal so
// `LexicalEditor.version` and the extension dedupe check still have a value.
export const LEXICAL_VERSION: string =
  process.env.LEXICAL_VERSION ?? '0.44.0+source';
