/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {CodeHighlightNode} from './CodeHighlightNode';
import type {CodeNode} from './CodeNode';

import {decodeTableOf, type GeneratedJSONFactory} from 'lexical';

/** CodeNode's generated implementations, for its `$config`. @internal */
export const GENERATED_CODE: GeneratedJSONFactory = () => {
  /** Generated from CodeNode's serialization schema. Do not edit by hand. */
  function exportCodeNode(node: CodeNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      language: node.__language,
      theme: node.__theme,
      direction: node.__dir,
      format: node.getFormatType(),
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from CodeNode's serialization schema. Do not edit by hand. */
  function exportCompactCodeNode(node: CodeNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const language = node.__language;
    if (language !== undefined) {
      json.language = language;
    }
    const theme = node.__theme;
    if (theme !== undefined) {
      json.theme = theme;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from CodeNode's serialization schema. Do not edit by hand. */
  function afterCloneCodeNode(node: CodeNode, prevNode: CodeNode): void {
    node.__language = prevNode.__language;
    node.__theme = prevNode.__theme;
  }

  return {
    exportJSON: exportCodeNode,
    exportCompactJSON: exportCompactCodeNode,
    afterCloneFrom: afterCloneCodeNode,
  };
};

/** CodeHighlightNode's generated implementations, for its `$config`. @internal */
export const GENERATED_CODEHIGHLIGHT: GeneratedJSONFactory = fields => {
  const CODEHIGHLIGHT_MODE_DECODE = decodeTableOf(fields, 'mode') as {
    readonly [key: string]: 'normal' | 'segmented' | 'token';
  };

  /** Generated from CodeHighlightNode's serialization schema. Do not edit by hand. */
  function exportCodeHighlightNode(node: CodeHighlightNode): {
    [key: string]: unknown;
  } {
    return {
      highlightType: node.getHighlightType(),
      detail: node.__detail,
      format: node.__format,
      mode: CODEHIGHLIGHT_MODE_DECODE[node.__mode],
      style: node.__style,
      text: node.__text,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from CodeHighlightNode's serialization schema. Do not edit by hand. */
  function exportCompactCodeHighlightNode(node: CodeHighlightNode): {
    [key: string]: unknown;
  } {
    const json: {[key: string]: unknown} = {type: node.__type};
    const highlightType = node.getHighlightType();
    if (highlightType !== undefined) {
      json.highlightType = highlightType;
    }
    const detail = node.__detail;
    if (detail !== undefined && detail !== 0) {
      json.detail = detail;
    }
    const format = node.__format;
    if (format !== undefined && format !== 0) {
      json.format = format;
    }
    const mode = CODEHIGHLIGHT_MODE_DECODE[node.__mode];
    if (mode !== undefined && mode !== 'normal') {
      json.mode = mode;
    }
    const style = node.__style;
    if (style !== undefined && style !== '') {
      json.style = style;
    }
    const text = node.__text;
    if (text !== undefined && text !== '') {
      json.text = text;
    }
    return json;
  }

  return {
    exportJSON: exportCodeHighlightNode,
    exportCompactJSON: exportCompactCodeHighlightNode,
  };
};
