/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {HeadingNode, QuoteNode} from './index';

import {
  type GeneratedJSONFactory,
  getterTableOf,
  setterDefaultOf,
  setterTableOf,
} from 'lexical';

// The JSON number grammar, anchored, matching numberValue: `Number()` alone
// reads '0x10' as 16 and '' as 0, and neither is a shape a JSON encoder
// produces. Emitted from the same source the codegen verified against, so the
// two cannot be different functions.
const JSON_NUMBER = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/;

function num(v: unknown, d: number): number {
  if (typeof v === 'number') {
    return Number.isFinite(v) ? v : d;
  }
  if (typeof v !== 'string' || !JSON_NUMBER.test(v)) {
    return d;
  }
  const n = Number(v);
  return Number.isFinite(n) ? n : d;
}

function numC(
  v: unknown,
  d: number,
  min: number,
  max: number,
  integer: boolean,
): number {
  const n = num(v, d);
  return n >= min && n <= max && (!integer || Number.isInteger(n)) ? n : d;
}

/**
 * HeadingNode's schema-declared fields, for a clone. Generated from that
 * schema; do not edit by hand.
 *
 * @internal
 */
export function afterCloneHeadingNode(
  node: HeadingNode,
  prevNode: HeadingNode,
): void {
  node.__tag = prevNode.__tag;
}

/** HeadingNode's generated implementations, for its `$config`. @internal */
export const GENERATED_HEADING: GeneratedJSONFactory = fields => {
  const HEADING_FORMAT_GETTER = getterTableOf(fields, 'format') as {
    readonly [key: string]:
      | ''
      | 'center'
      | 'end'
      | 'justify'
      | 'left'
      | 'right'
      | 'start';
  };

  const HEADING_FORMAT_SETTER = setterTableOf(fields, 'format') as {
    readonly [key: string]: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  };

  const HEADING_FORMAT_SETTER_DEFAULT = setterDefaultOf(fields, 'format') as
    | 0
    | 1
    | 2
    | 3
    | 4
    | 5
    | 6;

  /** Generated from HeadingNode's serialization schema. Do not edit by hand. */
  function exportHeadingNode(node: HeadingNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      tag: node.__tag,
      direction: node.__dir,
      format: HEADING_FORMAT_GETTER[node.__format],
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from HeadingNode's serialization schema. Do not edit by hand. */
  function exportCompactHeadingNode(node: HeadingNode): {
    [key: string]: unknown;
  } {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const tag = node.__tag;
    if (tag !== undefined && tag !== 'h1') {
      json.tag = tag;
    }
    const direction = node.__dir;
    if (direction != null) {
      json.direction = direction;
    }
    const format = HEADING_FORMAT_GETTER[node.__format];
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from HeadingNode's serialization schema. Do not edit by hand. */
  function updateHeadingNode(
    node: HeadingNode,
    json: {readonly [key: string]: unknown},
  ): HeadingNode {
    const direction = json.direction;
    node.__dir =
      direction === null || direction === 'ltr' || direction === 'rtl'
        ? direction
        : null;
    const format = json.format;
    node.__format =
      typeof format === 'string' && format in HEADING_FORMAT_SETTER
        ? HEADING_FORMAT_SETTER[format]
        : HEADING_FORMAT_SETTER_DEFAULT;
    node.__indent = numC(json.indent, 0, 0, Infinity, true);
    node.__textFormat = num(json.textFormat, 0);
    const textStyle = json.textStyle;
    node.__textStyle = typeof textStyle === 'string' ? textStyle : '';
    const tag = json.tag;
    node.__tag =
      tag === 'h1' ||
      tag === 'h2' ||
      tag === 'h3' ||
      tag === 'h4' ||
      tag === 'h5' ||
      tag === 'h6'
        ? tag
        : 'h1';
    return node;
  }

  return {
    exportJSON: exportHeadingNode,
    exportCompactJSON: exportCompactHeadingNode,
    updateFromJSON: updateHeadingNode,
    afterCloneFrom: afterCloneHeadingNode,
  };
};

/** QuoteNode's generated implementations, for its `$config`. @internal */
export const GENERATED_QUOTE: GeneratedJSONFactory = fields => {
  const QUOTE_FORMAT_GETTER = getterTableOf(fields, 'format') as {
    readonly [key: string]:
      | ''
      | 'center'
      | 'end'
      | 'justify'
      | 'left'
      | 'right'
      | 'start';
  };

  const QUOTE_FORMAT_SETTER = setterTableOf(fields, 'format') as {
    readonly [key: string]: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  };

  const QUOTE_FORMAT_SETTER_DEFAULT = setterDefaultOf(fields, 'format') as
    | 0
    | 1
    | 2
    | 3
    | 4
    | 5
    | 6;

  /** Generated from QuoteNode's serialization schema. Do not edit by hand. */
  function exportQuoteNode(node: QuoteNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      direction: node.__dir,
      format: QUOTE_FORMAT_GETTER[node.__format],
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from QuoteNode's serialization schema. Do not edit by hand. */
  function exportCompactQuoteNode(node: QuoteNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const direction = node.__dir;
    if (direction != null) {
      json.direction = direction;
    }
    const format = QUOTE_FORMAT_GETTER[node.__format];
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from QuoteNode's serialization schema. Do not edit by hand. */
  function updateQuoteNode(
    node: QuoteNode,
    json: {readonly [key: string]: unknown},
  ): QuoteNode {
    const direction = json.direction;
    node.__dir =
      direction === null || direction === 'ltr' || direction === 'rtl'
        ? direction
        : null;
    const format = json.format;
    node.__format =
      typeof format === 'string' && format in QUOTE_FORMAT_SETTER
        ? QUOTE_FORMAT_SETTER[format]
        : QUOTE_FORMAT_SETTER_DEFAULT;
    node.__indent = numC(json.indent, 0, 0, Infinity, true);
    node.__textFormat = num(json.textFormat, 0);
    const textStyle = json.textStyle;
    node.__textStyle = typeof textStyle === 'string' ? textStyle : '';
    return node;
  }

  return {
    exportJSON: exportQuoteNode,
    exportCompactJSON: exportCompactQuoteNode,
    updateFromJSON: updateQuoteNode,
  };
};
