/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {HeadingNode, QuoteNode} from './index';
import type {GeneratedJSON} from 'lexical';

// The JSON number grammar, anchored, matching numberValue: `Number()` alone
// reads '0x10' as 16 and '' as 0, and neither is a shape a JSON encoder
// produces. Emitted from the same source the codegen verified against, so the
// two cannot be different functions.
const JSON_NUMBER = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/;

function num(v: unknown, d: number): number {
  if (typeof v === 'number') {
    return Number.isFinite(v) ? v : d;
  }
  if (typeof v !== 'string' || !JSON_NUMBER.test(v)) {
    return d;
  }
  const n = Number(v);
  return Number.isFinite(n) ? n : d;
}

function numC(
  v: unknown,
  d: number,
  min: number,
  max: number,
  integer: boolean,
): number {
  const n = num(v, d);
  return n >= min && n <= max && (!integer || Number.isInteger(n)) ? n : d;
}

/** Generated from HeadingNode's serialization schema. Do not edit by hand. */
function exportHeadingNode(node: HeadingNode): {[key: string]: unknown} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  return {
    children: [],
    tag: node.__tag,
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat:
      textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
    textStyle:
      textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
    type: 'heading',
    version: 1,
  };
}

/** Generated from HeadingNode's serialization schema. Do not edit by hand. */
function exportCompactHeadingNode(node: HeadingNode): {[key: string]: unknown} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  const json: {[key: string]: unknown} = {children: []};
  const tag = node.__tag;
  if (tag !== undefined && tag !== 'h1') {
    json.tag = tag;
  }
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  if (
    textFormat !== undefined &&
    textFormat !== 0 &&
    shouldSerializeTextStyles
  ) {
    json.textFormat = textFormat;
  }
  if (
    textStyle !== undefined &&
    textStyle !== '' &&
    shouldSerializeTextStyles
  ) {
    json.textStyle = textStyle;
  }
  json.type = 'heading';
  return json;
}

/** Generated from HeadingNode's serialization schema. Do not edit by hand. */
function updateHeadingNode(
  node: HeadingNode,
  json: {readonly [key: string]: unknown},
): HeadingNode {
  let self = node;
  let n: unknown;
  let v: unknown;
  v = json.direction;
  self.__dir = v === null || v === 'ltr' || v === 'rtl' ? v : null;
  v = json.format;
  n = self.setFormat(
    v === '' ||
      v === 'left' ||
      v === 'start' ||
      v === 'center' ||
      v === 'right' ||
      v === 'end' ||
      v === 'justify'
      ? v
      : '',
  );
  self = (n || self) as HeadingNode;
  v = json.indent;
  self.__indent = numC(v, 0, 0, Infinity, true);
  v = json.textFormat;
  n = self.setTextFormat(num(v, 0));
  self = (n || self) as HeadingNode;
  v = json.textStyle;
  n = self.setTextStyle(typeof v === 'string' ? v : '');
  self = (n || self) as HeadingNode;
  v = json.tag;
  self.__tag =
    v === 'h1' ||
    v === 'h2' ||
    v === 'h3' ||
    v === 'h4' ||
    v === 'h5' ||
    v === 'h6'
      ? v
      : 'h1';
  return self;
}

/** HeadingNode's generated implementations, for its `$config`. @internal */
export const GENERATED_HEADING: GeneratedJSON = {
  exportJSON: exportHeadingNode,
  exportCompactJSON: exportCompactHeadingNode,
  updateFromJSON: updateHeadingNode,
};

/** Generated from QuoteNode's serialization schema. Do not edit by hand. */
function exportQuoteNode(node: QuoteNode): {[key: string]: unknown} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  return {
    children: [],
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat:
      textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
    textStyle:
      textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
    type: 'quote',
    version: 1,
  };
}

/** Generated from QuoteNode's serialization schema. Do not edit by hand. */
function exportCompactQuoteNode(node: QuoteNode): {[key: string]: unknown} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  const json: {[key: string]: unknown} = {children: []};
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  if (
    textFormat !== undefined &&
    textFormat !== 0 &&
    shouldSerializeTextStyles
  ) {
    json.textFormat = textFormat;
  }
  if (
    textStyle !== undefined &&
    textStyle !== '' &&
    shouldSerializeTextStyles
  ) {
    json.textStyle = textStyle;
  }
  json.type = 'quote';
  return json;
}

/** Generated from QuoteNode's serialization schema. Do not edit by hand. */
function updateQuoteNode(
  node: QuoteNode,
  json: {readonly [key: string]: unknown},
): QuoteNode {
  let self = node;
  let n: unknown;
  let v: unknown;
  v = json.direction;
  self.__dir = v === null || v === 'ltr' || v === 'rtl' ? v : null;
  v = json.format;
  n = self.setFormat(
    v === '' ||
      v === 'left' ||
      v === 'start' ||
      v === 'center' ||
      v === 'right' ||
      v === 'end' ||
      v === 'justify'
      ? v
      : '',
  );
  self = (n || self) as QuoteNode;
  v = json.indent;
  self.__indent = numC(v, 0, 0, Infinity, true);
  v = json.textFormat;
  n = self.setTextFormat(num(v, 0));
  self = (n || self) as QuoteNode;
  v = json.textStyle;
  n = self.setTextStyle(typeof v === 'string' ? v : '');
  self = (n || self) as QuoteNode;
  return self;
}

/** QuoteNode's generated implementations, for its `$config`. @internal */
export const GENERATED_QUOTE: GeneratedJSON = {
  exportJSON: exportQuoteNode,
  exportCompactJSON: exportCompactQuoteNode,
  updateFromJSON: updateQuoteNode,
};
