/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {HeadingNode, QuoteNode} from './index';
import type {GeneratedJSON} from 'lexical';

/** Generated from HeadingNode's serialization schema. Do not edit by hand. */
function exportHeadingNode(node: HeadingNode): {[key: string]: unknown} {
  return {
    children: [],
    tag: node.__tag,
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat: node.getSerializedTextFormat(),
    textStyle: node.getSerializedTextStyle(),
    type: 'heading',
    version: 1,
  };
}

/** Generated from HeadingNode's serialization schema. Do not edit by hand. */
function exportCompactHeadingNode(node: HeadingNode): {[key: string]: unknown} {
  const json: {[key: string]: unknown} = {children: []};
  const tag = node.__tag;
  if (tag !== undefined && tag !== 'h1') {
    json.tag = tag;
  }
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  const textFormat = node.getSerializedTextFormat();
  if (textFormat !== undefined && textFormat !== 0) {
    json.textFormat = textFormat;
  }
  const textStyle = node.getSerializedTextStyle();
  if (textStyle !== undefined && textStyle !== '') {
    json.textStyle = textStyle;
  }
  json.type = 'heading';
  return json;
}

/** HeadingNode's generated implementations, for its `$config`. @internal */
export const GENERATED_HEADING: GeneratedJSON = {
  exportJSON: exportHeadingNode,
  exportCompactJSON: exportCompactHeadingNode,
};

/** Generated from QuoteNode's serialization schema. Do not edit by hand. */
function exportQuoteNode(node: QuoteNode): {[key: string]: unknown} {
  return {
    children: [],
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat: node.getSerializedTextFormat(),
    textStyle: node.getSerializedTextStyle(),
    type: 'quote',
    version: 1,
  };
}

/** Generated from QuoteNode's serialization schema. Do not edit by hand. */
function exportCompactQuoteNode(node: QuoteNode): {[key: string]: unknown} {
  const json: {[key: string]: unknown} = {children: []};
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  const textFormat = node.getSerializedTextFormat();
  if (textFormat !== undefined && textFormat !== 0) {
    json.textFormat = textFormat;
  }
  const textStyle = node.getSerializedTextStyle();
  if (textStyle !== undefined && textStyle !== '') {
    json.textStyle = textStyle;
  }
  json.type = 'quote';
  return json;
}

/** QuoteNode's generated implementations, for its `$config`. @internal */
export const GENERATED_QUOTE: GeneratedJSON = {
  exportJSON: exportQuoteNode,
  exportCompactJSON: exportCompactQuoteNode,
};
