/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/**
 * What `scripts/generate-node-json.mjs` needs in its first phase, which runs
 * before anything can be imported: the static manifest of every generated
 * module and the do-nothing stub that stands in for each one. The generation
 * itself (`./generateNodeJSON.mjs`) checks what it emits against the same
 * manifest, so the two cannot drift apart silently.
 */

/**
 * Everything phase one needs to write a valid stub for each output, stated
 * statically because phase one runs before anything can be imported. Phase two
 * asserts its resolved targets against this, so the two cannot drift apart
 * silently.
 *
 * `home` marks the module that declares the `GeneratedJSON` interface (the
 * others import the type from `lexical`).
 *
 * `afterClone` names the copy helpers a package exports beside its factories:
 * one per class whose own `$config` declares a schema field. A class that
 * writes its own `afterCloneFrom` imports the helper and calls it, so the stub
 * has to carry the name or nothing importing it can load.
 *
 * @type {readonly {
 *   file: string,
 *   home?: boolean,
 *   entries: readonly string[],
 *   afterClone: readonly string[],
 * }[]}
 */
export const MANIFEST = [
  {
    afterClone: ['afterCloneElementNode', 'afterCloneTextNode'],
    entries: [
      'GENERATED_ELEMENT',
      'GENERATED_TEXT',
      'GENERATED_PARAGRAPH',
      'GENERATED_LINEBREAK',
      'GENERATED_TAB',
    ],
    file: 'packages/lexical/src/LexicalGeneratedJSON.ts',
    home: true,
  },
  {
    afterClone: ['afterCloneHeadingNode'],
    entries: ['GENERATED_HEADING', 'GENERATED_QUOTE'],
    file: 'packages/lexical-rich-text/src/LexicalRichTextGeneratedJSON.ts',
  },
  {
    afterClone: ['afterCloneLinkNode', 'afterCloneAutoLinkNode'],
    entries: ['GENERATED_LINK', 'GENERATED_AUTOLINK'],
    file: 'packages/lexical-link/src/LexicalLinkGeneratedJSON.ts',
  },
  {
    afterClone: ['afterCloneMarkNode'],
    entries: ['GENERATED_MARK'],
    file: 'packages/lexical-mark/src/LexicalMarkGeneratedJSON.ts',
  },
  {
    afterClone: ['afterCloneListNode', 'afterCloneListItemNode'],
    entries: ['GENERATED_LIST', 'GENERATED_LISTITEM'],
    file: 'packages/lexical-list/src/LexicalListGeneratedJSON.ts',
  },
  {
    afterClone: [
      'afterCloneTableNode',
      'afterCloneTableRowNode',
      'afterCloneTableCellNode',
    ],
    entries: ['GENERATED_TABLE', 'GENERATED_TABLEROW', 'GENERATED_TABLECELL'],
    file: 'packages/lexical-table/src/LexicalTableGeneratedJSON.ts',
  },
  {
    afterClone: ['afterCloneCodeNode', 'afterCloneCodeHighlightNode'],
    entries: ['GENERATED_CODE', 'GENERATED_CODEHIGHLIGHT'],
    file: 'packages/lexical-code-core/src/LexicalCodeCoreGeneratedJSON.ts',
  },
  {
    afterClone: ['afterCloneDecoratorBlockNode'],
    entries: ['GENERATED_DECORATORBLOCK'],
    file: 'packages/lexical-react/src/shared/LexicalReactGeneratedJSON.ts',
  },
];

export const HEADER = `/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's \`json\`
// schema. Run \`pnpm run generate-node-json\` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */
`;

export const INTERFACE_SOURCE = `/**
 * The generated implementations for one node class.
 *
 * Each is handed to the class it was generated from through that class's
 * \`$config\`, so nothing has to match code to class at runtime.
 *
 * @internal
 */
export interface GeneratedJSON {
  // Method syntax, so TypeScript checks the parameter bivariantly and a
  // function generated for one class is assignable here — the same reason
  // SerializationSchema.isEqual is declared this way. The alternative is to
  // widen the parameter to 'never', which no generated function actually
  // accepts and every call site then has to cast back.
  exportJSON(node: LexicalNode): {[key: string]: unknown};
  // \`isCompactDefault\` is the running class's own omission test, supplied by
  // the dispatch. Generated code states each property's comparison as source
  // where the default has a literal a value could be \`===\`; where it does not,
  // the comparison is this call, so the two forms omit the same properties
  // without the generated module holding a value import of anything. Most
  // exporters declare the parameter and never call it, and one generated
  // before it existed simply declares one parameter.
  exportCompactJSON?(
    node: LexicalNode,
    isCompactDefault: CompactDefaultTest,
  ): {[key: string]: unknown};
  // Returns the node the properties were applied to, which is the node passed
  // in: it is writable by construction and every setter writes it in place.
  // The return is kept so a caller reads the applied node from one place,
  // whether or not the class has a generated parser.
  updateFromJSON?(
    node: LexicalNode,
    json: {readonly [key: string]: unknown},
  ): LexicalNode;
  // Copies the fields this class's own \`$config\` declared, for the
  // \`afterCloneFrom\` synthesized from the same schema. The superclass's half is
  // that method's \`super\` call, so this covers one class's own fields and
  // nothing above it.
  afterCloneFrom?(node: LexicalNode, prevNode: LexicalNode): void;
}

/**
 * Builds the generated implementations for one class from that class's
 * composed schema, which the registration hands it: the lookup tables the
 * code reads are the schema's own objects, read from it here, so a generated
 * module holds no copy of a table and nothing about one is written into it
 * at build time.
 *
 * @internal
 */
export type GeneratedJSONFactory = (
  fields: ComposedSchemaFields,
) => GeneratedJSON;`;

/**
 * A valid do-nothing module for one output, from the static manifest alone.
 *
 * @param {(typeof MANIFEST)[number]} pkg
 * @returns {string}
 */
export function stubSource(pkg) {
  const lines = [HEADER];
  if (pkg.home) {
    lines.push(
      `\nimport type {LexicalNode} from './LexicalNode';\nimport type {ComposedSchemaFields} from './LexicalSchema';\nimport type {CompactDefaultTest} from './LexicalUtils';\n\n${INTERFACE_SOURCE}\n`,
    );
  } else {
    lines.push(`\nimport type {GeneratedJSONFactory} from 'lexical';\n`);
  }
  for (const name of pkg.entries) {
    lines.push(
      `\n/** @internal */\nexport const ${name}: undefined | GeneratedJSONFactory = undefined;\n`,
    );
  }
  for (const name of pkg.afterClone) {
    // Throws rather than doing nothing. The loosest parameters that accept a
    // node, since the stub may not name a class, and a body that cannot be
    // mistaken for the real one: phase one writes these *in place*, so a run
    // whose phase two fails leaves them in the tree, and a class calls its
    // helper unconditionally from `afterCloneFrom`. A no-op there is silent
    // — the fields keep the constructor's defaults and every node loses them
    // on its next getWritable() — where this says what happened. Nothing
    // between the two phases clones a node, so it is never reached on the
    // path that replaces it.
    lines.push(
      `\n/** @internal */\nexport function ${name}(_node: unknown, _prevNode: unknown): void {\n  throw new Error(\n    '${name}: this module is the do-nothing stub \`pnpm run generate-node-json\` writes before it generates the real one. Its second phase did not finish; run it again.',\n  );\n}\n`,
    );
  }
  return lines.join('');
}
