/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/**
 * What `scripts/generate-node-json.mjs` needs in its first phase, which runs
 * before anything can be imported: the static manifest of every generated
 * module and the do-nothing stub that stands in for each one. The generation
 * itself (`./generateNodeJSON.mjs`) checks what it emits against the same
 * manifest, so the two cannot drift apart silently.
 */

/**
 * Everything phase one needs to write a valid stub for each output, stated
 * statically because phase one runs before anything can be imported. Phase two
 * asserts its resolved targets against this, so the two cannot drift apart
 * silently.
 *
 * `home` marks the module that declares the `GeneratedJSON` interface (the
 * others import the type from `lexical`).
 *
 * @type {readonly {
 *   file: string,
 *   home?: boolean,
 *   entries: readonly string[],
 * }[]}
 */
export const MANIFEST = [
  {
    entries: [
      'GENERATED_TEXT',
      'GENERATED_PARAGRAPH',
      'GENERATED_LINEBREAK',
      'GENERATED_TAB',
    ],
    file: 'packages/lexical/src/LexicalGeneratedJSON.ts',
    home: true,
  },
  {
    entries: ['GENERATED_HEADING', 'GENERATED_QUOTE'],
    file: 'packages/lexical-rich-text/src/LexicalRichTextGeneratedJSON.ts',
  },
  {
    entries: ['GENERATED_LINK', 'GENERATED_AUTOLINK'],
    file: 'packages/lexical-link/src/LexicalLinkGeneratedJSON.ts',
  },
  {
    entries: ['GENERATED_MARK'],
    file: 'packages/lexical-mark/src/LexicalMarkGeneratedJSON.ts',
  },
];

export const HEADER = `/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's \`json\`
// schema. Run \`pnpm run generate-node-json\` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */
`;

export const INTERFACE_SOURCE = `/**
 * The generated implementations for one node class.
 *
 * Each is handed to the class it was generated from through that class's
 * \`$config\`, so nothing has to match code to class at runtime.
 *
 * @internal
 */
export interface GeneratedJSON {
  // Method syntax, so TypeScript checks the parameter bivariantly and a
  // function generated for one class is assignable here — the same reason
  // SerializationSchema.isEqual is declared this way. The alternative is to
  // widen the parameter to 'never', which no generated function actually
  // accepts and every call site then has to cast back.
  exportJSON(node: LexicalNode): {[key: string]: unknown};
  exportCompactJSON?(node: LexicalNode): {[key: string]: unknown};
  // Returns the node the properties were applied to, which is the node passed
  // in unless a setter replaced it — the same value \`$applyJSONSetters\`
  // returns from the walk, for the same reason.
  updateFromJSON?(
    node: LexicalNode,
    json: {readonly [key: string]: unknown},
  ): LexicalNode;
}`;

/**
 * A valid do-nothing module for one output, from the static manifest alone.
 *
 * @param {(typeof MANIFEST)[number]} pkg
 * @returns {string}
 */
export function stubSource(pkg) {
  const lines = [HEADER];
  if (pkg.home) {
    lines.push(
      `\nimport type {LexicalNode} from './LexicalNode';\n\n${INTERFACE_SOURCE}\n`,
    );
  } else {
    lines.push(`\nimport type {GeneratedJSON} from 'lexical';\n`);
  }
  for (const name of pkg.entries) {
    lines.push(
      `\n/** @internal */\nexport const ${name}: undefined | GeneratedJSON = undefined;\n`,
    );
  }
  return lines.join('');
}
