/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {TableCellNode} from './LexicalTableCellNode';
import type {TableNode} from './LexicalTableNode';
import type {TableRowNode} from './LexicalTableRowNode';
import type {GeneratedJSONFactory} from 'lexical';

/** TableNode's generated implementations, for its `$config`. @internal */
export const GENERATED_TABLE: GeneratedJSONFactory = () => {
  /** Generated from TableNode's serialization schema. Do not edit by hand. */
  function exportTableNode(node: TableNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      colWidths: node.__colWidths,
      frozenColumnCount: node.getSerializedFrozenColumnCount(),
      frozenRowCount: node.getSerializedFrozenRowCount(),
      rowStriping: node.getSerializedRowStriping(),
      direction: node.__dir,
      format: node.getFormatType(),
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from TableNode's serialization schema. Do not edit by hand. */
  function exportCompactTableNode(node: TableNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const colWidths = node.__colWidths;
    if (colWidths !== undefined) {
      json.colWidths = colWidths;
    }
    const frozenColumnCount = node.getSerializedFrozenColumnCount();
    if (frozenColumnCount !== undefined && frozenColumnCount !== 0) {
      json.frozenColumnCount = frozenColumnCount;
    }
    const frozenRowCount = node.getSerializedFrozenRowCount();
    if (frozenRowCount !== undefined && frozenRowCount !== 0) {
      json.frozenRowCount = frozenRowCount;
    }
    const rowStriping = node.getSerializedRowStriping();
    if (rowStriping !== undefined && rowStriping !== false) {
      json.rowStriping = rowStriping;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from TableNode's serialization schema. Do not edit by hand. */
  function afterCloneTableNode(node: TableNode, prevNode: TableNode): void {
    node.__colWidths = prevNode.__colWidths;
  }

  return {
    exportJSON: exportTableNode,
    exportCompactJSON: exportCompactTableNode,
    afterCloneFrom: afterCloneTableNode,
  };
};

/** TableRowNode's generated implementations, for its `$config`. @internal */
export const GENERATED_TABLEROW: GeneratedJSONFactory = () => {
  /** Generated from TableRowNode's serialization schema. Do not edit by hand. */
  function exportTableRowNode(node: TableRowNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      height: node.__height,
      direction: node.__dir,
      format: node.getFormatType(),
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from TableRowNode's serialization schema. Do not edit by hand. */
  function exportCompactTableRowNode(node: TableRowNode): {
    [key: string]: unknown;
  } {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const height = node.__height;
    if (height !== undefined) {
      json.height = height;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from TableRowNode's serialization schema. Do not edit by hand. */
  function afterCloneTableRowNode(
    node: TableRowNode,
    prevNode: TableRowNode,
  ): void {
    node.__height = prevNode.__height;
  }

  return {
    exportJSON: exportTableRowNode,
    exportCompactJSON: exportCompactTableRowNode,
    afterCloneFrom: afterCloneTableRowNode,
  };
};

/** TableCellNode's generated implementations, for its `$config`. @internal */
export const GENERATED_TABLECELL: GeneratedJSONFactory = () => {
  /** Generated from TableCellNode's serialization schema. Do not edit by hand. */
  function exportTableCellNode(node: TableCellNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      backgroundColor: node.__backgroundColor,
      colSpan: node.__colSpan,
      headerState: node.__headerState,
      rowSpan: node.__rowSpan,
      verticalAlign: node.getSerializedVerticalAlign(),
      width: node.__width,
      direction: node.__dir,
      format: node.getFormatType(),
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from TableCellNode's serialization schema. Do not edit by hand. */
  function exportCompactTableCellNode(node: TableCellNode): {
    [key: string]: unknown;
  } {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const backgroundColor = node.__backgroundColor;
    if (backgroundColor !== undefined && backgroundColor !== null) {
      json.backgroundColor = backgroundColor;
    }
    const colSpan = node.__colSpan;
    if (colSpan !== undefined && colSpan !== 1) {
      json.colSpan = colSpan;
    }
    const headerState = node.__headerState;
    if (headerState !== undefined && headerState !== 0) {
      json.headerState = headerState;
    }
    const rowSpan = node.__rowSpan;
    if (rowSpan !== undefined && rowSpan !== 1) {
      json.rowSpan = rowSpan;
    }
    const verticalAlign = node.getSerializedVerticalAlign();
    if (verticalAlign !== undefined) {
      json.verticalAlign = verticalAlign;
    }
    const width = node.__width;
    if (width !== undefined) {
      json.width = width;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from TableCellNode's serialization schema. Do not edit by hand. */
  function afterCloneTableCellNode(
    node: TableCellNode,
    prevNode: TableCellNode,
  ): void {
    node.__backgroundColor = prevNode.__backgroundColor;
    node.__colSpan = prevNode.__colSpan;
    node.__headerState = prevNode.__headerState;
    node.__rowSpan = prevNode.__rowSpan;
    node.__width = prevNode.__width;
  }

  return {
    exportJSON: exportTableCellNode,
    exportCompactJSON: exportCompactTableCellNode,
    afterCloneFrom: afterCloneTableCellNode,
  };
};
