/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
export type CodeMode = keyof typeof modes;
export const modes = {
  c: 'C',
  cassandra: 'CQL',
  clojure: 'Clojure',
  clojureScript: 'ClojureScript',
  cmake: 'CMake',
  coffeeScript: 'CoffeeScript',
  commonLisp: 'Common Lisp',
  cpp: 'C++',
  crystal: 'Crystal',
  csharp: 'C#',
  css: 'CSS',
  d: 'D',
  dart: 'Dart',
  diff: 'Diff',
  dockerFile: 'Dockerfile',
  elm: 'Elm',
  erlang: 'Erlang',
  fSharp: 'F#',
  fortran: 'Fortran',
  go: 'Go',
  groovy: 'Groovy',
  haskell: 'Haskell',
  haxe: 'Haxe',
  html: 'HTML',
  http: 'HTTP',
  java: 'Java',
  javascript: 'JavaScript',
  json: 'JSON',
  jsonld: 'JSON-LD',
  jsx: 'JSX',
  julia: 'Julia',
  kotlin: 'Kotlin',
  less: 'LESS',
  liveScript: 'LiveScript',
  lua: 'Lua',
  mariasql: 'MariaDB SQL',
  markdown: 'Markdown',
  mathematica: 'Mathematica',
  mssql: 'MS SQL',
  mysql: 'MySQL',
  nginx: 'Nginx',
  oCaml: 'OCaml',
  objectiveC: 'Objective-C',
  objectiveCpp: 'Objective-C++',
  octave: 'Octave',
  pascal: 'Pascal',
  perl: 'Perl',
  php: 'PHP',
  plsql: 'PL/SQL',
  postgresql: 'PostgreSQL',
  powerShell: 'PowerShell',
  puppet: 'Puppet',
  python: 'Python',
  q: 'Q',
  r: 'R',
  ruby: 'Ruby',
  rust: 'Rust',
  sCSS: 'SCSS',
  sass: 'Sass',
  scala: 'Scala',
  scheme: 'Scheme',
  shell: 'Shell',
  smalltalk: 'Smalltalk',
  sml: 'SML',
  solr: 'Solr',
  sql: 'SQL',
  sqlite: 'SQLite',
  stex: 'LaTeX',
  stylus: 'Stylus',
  swift: 'Swift',
  tcl: 'Tcl',
  toml: 'TOML',
  tsx: 'TSX',
  typescript: 'TypeScript',
  velocity: 'Velocity',
  verilog: 'Verilog',
  wast: 'Web Assembly',
  xml: 'XML',
  yaml: 'YAML',
};
