/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {MarkNode} from './MarkNode';
import type {GeneratedJSON} from 'lexical';

/** Generated from MarkNode's serialization schema. Do not edit by hand. */
function exportMarkNode(node: MarkNode): {[key: string]: unknown} {
  return {
    children: [],
    ids: node.getIDs(),
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat: node.getSerializedTextFormat(),
    textStyle: node.getSerializedTextStyle(),
    type: 'mark',
    version: 1,
  };
}

/**
 * MarkNode's generated implementations, for its `$config` — a factory,
 * because the compact comparison for `ids` goes through the
 * schema's own default and equality (its default is reference-typed, so no
 * literal a value could be `===` exists). The class passes the schemas it
 * declared and the comparisons close over them.
 *
 * @internal
 * @__NO_SIDE_EFFECTS__
 */
export function createGeneratedMarkNode(config: {
  ids: {
    readonly defaultValue: unknown;
    isEqual?(a: unknown, b: unknown): boolean;
  };
}): GeneratedJSON {
  const ids_defaultValue = config.ids.defaultValue;
  const ids_isEqual = config.ids.isEqual;
  /** Generated from MarkNode's serialization schema. Do not edit by hand. */
  function exportCompactMarkNode(node: MarkNode): {[key: string]: unknown} {
    const json: {[key: string]: unknown} = {children: []};
    const ids = node.getIDs();
    if (
      ids !== undefined &&
      ids !== ids_defaultValue &&
      !(ids_isEqual !== undefined && ids_isEqual(ids, ids_defaultValue))
    ) {
      json.ids = ids;
    }
    const direction = node.__dir;
    if (direction !== undefined && direction !== null) {
      json.direction = direction;
    }
    const format = node.getFormatType();
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    const textFormat = node.getSerializedTextFormat();
    if (textFormat !== undefined && textFormat !== 0) {
      json.textFormat = textFormat;
    }
    const textStyle = node.getSerializedTextStyle();
    if (textStyle !== undefined && textStyle !== '') {
      json.textStyle = textStyle;
    }
    json.type = 'mark';
    return json;
  }
  return {
    exportJSON: exportMarkNode,
    exportCompactJSON: exportCompactMarkNode,
  };
}
