/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {MarkNode} from './MarkNode';
import type {GeneratedJSON} from 'lexical';

/** Generated from MarkNode's serialization schema. Do not edit by hand. */
function exportMarkNode(node: MarkNode): {[key: string]: unknown} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  return {
    children: [],
    ids: node.getIDs(),
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat:
      textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
    textStyle:
      textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
    type: 'mark',
    version: 1,
  };
}

/** MarkNode's generated implementations, for its `$config`. @internal */
export const GENERATED_MARK: GeneratedJSON = {
  exportJSON: exportMarkNode,
};
