const puppeteer = require('puppeteer');
const {composition, keydown, select} = require('./test-helpers');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('http://localhost:3000');
  await page.focus('div.editor');
  // await debug(page);

  await page.focus('div.editor');
  await select(page, [1, 0, 0], 1, [1, 0, 0], 1);
  await keydown(page, 'Shift', false);
  await keydown(page, 'H', false);
  await page.keyboard.up('Shift');
  await keydown(page, 'e', false);
  await select(page, [0, 0, 0], 2, [0, 0, 0], 2);
  await page.keyboard.up('e');
  await keydown(page, 'l', false);
  await select(page, [0, 0, 0], 3, [0, 0, 0], 3);
  await page.keyboard.up('l');
  await keydown(page, 'l', false);
  await select(page, [0, 0, 0], 4, [0, 0, 0], 4);
  await page.keyboard.up('l');
  await keydown(page, 'o', false);
  await select(page, [0, 0, 0], 5, [0, 0, 0], 5);
  await page.keyboard.up('o');
  await keydown(page, ' ', false);
  await select(page, [0, 0, 0], 6, [0, 0, 0], 6);
  await page.keyboard.up(' ');
  await keydown(page, 'Shift', false);
  await keydown(page, 'S', false);
  await select(page, [0, 0, 0], 7, [0, 0, 0], 7);
  await page.keyboard.up('S');
  await page.keyboard.up('Shift');
  await keydown(page, 't', false);
  await select(page, [0, 0, 0], 8, [0, 0, 0], 8);
  await page.keyboard.up('t');
  await keydown(page, 'e', false);
  await select(page, [0, 0, 0], 9, [0, 0, 0], 9);
  await page.keyboard.up('e');
  await keydown(page, 'v', false);
  await select(page, [0, 0, 0], 10, [0, 0, 0], 10);
  await keydown(page, 'e', false);
  await select(page, [0, 0, 0], 11, [0, 0, 0], 11);
  await page.keyboard.up('v');
  await keydown(page, 'n', false);
  await select(page, [0, 0, 0], 12, [0, 0, 0], 12);
  await page.keyboard.up('e');
  await page.keyboard.up('n');
  await keydown(page, ' ', false);
  await select(page, [0, 0, 0], 13, [0, 0, 0], 13);
  await page.keyboard.up(' ');
  await keydown(page, 'Shift', false);
  await keydown(page, ':', false);
  await select(page, [0, 0, 0], 14, [0, 0, 0], 14);
  await page.keyboard.up(':');
  await keydown(page, ')', false);
  await select(page, [0, 2, 0], 1, [0, 2, 0], 1);
  await page.keyboard.up(')');
  await page.keyboard.up('Shift');
  await keydown(page, ' ', false);
  await page.keyboard.up(' ');
  await keydown(page, 'Alt', false);
  await page.keyboard.up('Alt');
  await keydown(page, '#', false);
  await select(page, [0, 2, 0], 2, [0, 2, 0], 2);
  await page.keyboard.up('#');
  await keydown(page, 'h', false);
  await select(page, [0, 3, 0], 2, [0, 3, 0], 2);
  await page.keyboard.up('h');
  await keydown(page, 'a', false);
  await select(page, [0, 3, 0], 3, [0, 3, 0], 3);
  await keydown(page, 's', false);
  await select(page, [0, 3, 0], 4, [0, 3, 0], 4);
  await page.keyboard.up('a');
  await page.keyboard.up('s');
  await keydown(page, 'h', false);
  await select(page, [0, 3, 0], 5, [0, 3, 0], 5);
  await page.keyboard.up('h');
  await keydown(page, 't', false);
  await select(page, [0, 3, 0], 6, [0, 3, 0], 6);
  await page.keyboard.up('t');
  await keydown(page, 'a', false);
  await select(page, [0, 3, 0], 7, [0, 3, 0], 7);
  await page.keyboard.up('a');
  await keydown(page, 'g', false);
  await select(page, [0, 3, 0], 8, [0, 3, 0], 8);
  await page.keyboard.up('g');
  await keydown(page, 'f', false);
  await select(page, [0, 3, 0], 9, [0, 3, 0], 9);
  await page.keyboard.up('f');
  await keydown(page, 't', false);
  await select(page, [0, 3, 0], 10, [0, 3, 0], 10);
  await page.keyboard.up('t');
  await keydown(page, 'w', false);
  await select(page, [0, 3, 0], 11, [0, 3, 0], 11);
  await page.keyboard.up('w');
  await keydown(page, ' ', false);
  await select(page, [0, 4, 0], 1, [0, 4, 0], 1);
  await page.keyboard.up(' ');
  await keydown(page, 'Alt', true);
  await composition(page, async (page, update, end) => {
    await update('´');
    await select(page, [0, 4, 0], 2, [0, 4, 0], 2);
    await page.keyboard.up('Alt');
    await keydown(page, 'é', true);
    await select(page, [0, 4, 0], 1, [0, 4, 0], 2);
    await update('é');
    await select(page, [0, 4, 0], 2, [0, 4, 0], 2);
    await end('é');
  });
  await keydown(page, 'e', false);
  await select(page, [0, 4, 0], 3, [0, 4, 0], 3);
  await page.keyboard.up('e');
  await keydown(page, 'ArrowRight', true);
  await select(page, [0, 4, 0], 2, [0, 4, 0], 3);
  await composition(page, async (page, update, end) => {
    await select(page, [0, 4, 0], 2, [0, 4, 0], 2);
    await update('è');
    await select(page, [0, 4, 0], 2, [0, 4, 0], 3);
    await page.keyboard.up('ArrowRight');
    await keydown(page, 'Enter', false);
    await update('è');
    await select(page, [0, 4, 0], 3, [0, 4, 0], 3);
    await end('è');
  });
  await page.keyboard.up('Enter');
  await keydown(page, ' ', false);
  await select(page, [0, 4, 0], 4, [0, 4, 0], 4);
  await page.keyboard.up(' ');
  await keydown(page, 'm', true);
  await composition(page, async (page, update, end) => {
    await update('m');
    await select(page, [0, 4, 0], 5, [0, 4, 0], 5);
    await keydown(page, 'o', false);
    await select(page, [0, 4, 0], 4, [0, 4, 0], 5);
    await update('も');
    await select(page, [0, 4, 0], 5, [0, 4, 0], 5);
    await page.keyboard.up('m');
    await page.keyboard.up('o');
    await keydown(page, 'j', false);
    await select(page, [0, 4, 0], 4, [0, 4, 0], 5);
    await update('もj');
    await select(page, [0, 4, 0], 6, [0, 4, 0], 6);
    await page.keyboard.up('j');
    await keydown(page, 'i', false);
    await select(page, [0, 4, 0], 4, [0, 4, 0], 6);
    await update('もじ');
    await select(page, [0, 4, 0], 6, [0, 4, 0], 6);
    await page.keyboard.up('i');
    await keydown(page, 'Enter', false);
    await select(page, [0, 4, 0], 4, [0, 4, 0], 6);
    await update('もじ');
    await select(page, [0, 4, 0], 6, [0, 4, 0], 6);
    await end('もじ');
  });
  await page.keyboard.up('Enter');
  await page.$eval('div.editor', (e) => e.blur());
  // await expectHTML('<p class="editor-paragraph" dir="ltr"><span>Hello Steven </span><span contenteditable="false" style="color: transparent; background-size: 16px 16px; height: 16px; width: 16px; background-position: center center; background-repeat: no-repeat; display: inline-block; margin: 0px 1px; text-align: center; vertical-align: middle; background-image: url(&quot;https://static.xx.fbcdn.net/images/emoji.php/v9/t4c/1/16/1f642.png&quot;);">🙂</span><span> </span><span class="editor-text-hashtag">#hashtagftw</span><span> éè もじ</span></p>');
})();
