/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

export type {
  BaseCaret,
  CaretDirection,
  CaretRange,
  CaretType,
  ChildCaret,
  CommonAncestorResult,
  CommonAncestorResultAncestor,
  CommonAncestorResultBranch,
  CommonAncestorResultDescendant,
  CommonAncestorResultSame,
  FlipDirection,
  NodeCaret,
  PointCaret,
  RootMode,
  SiblingCaret,
  StepwiseIteratorConfig,
  TextPointCaret,
  TextPointCaretSlice,
  TextPointCaretSliceTuple,
} from './caret/LexicalCaret';
export {
  $comparePointCaretNext,
  $extendCaretToRange,
  $getAdjacentChildCaret,
  $getCaretRange,
  $getChildCaret,
  $getChildCaretOrSelf,
  $getCollapsedCaretRange,
  $getCommonAncestor,
  $getCommonAncestorResultBranchOrder,
  $getSiblingCaret,
  $getTextNodeOffset,
  $getTextPointCaret,
  $getTextPointCaretSlice,
  $isChildCaret,
  $isNodeCaret,
  $isSiblingCaret,
  $isTextPointCaret,
  $isTextPointCaretSlice,
  flipDirection,
  makeStepwiseIterator,
} from './caret/LexicalCaret';
export {
  $caretFromPoint,
  $caretRangeFromSelection,
  $getAdjacentSiblingOrParentSiblingCaret,
  $getCaretInDirection,
  $getCaretRangeInDirection,
  $getChildCaretAtIndex,
  $insertNodeToNearestRootAtCaret,
  $isExtendableTextPointCaret,
  $normalizeCaret,
  $removeTextFromCaretRange,
  $rewindSiblingCaret,
  $setPointFromCaret,
  $setSelectionFromCaretRange,
  $splitAtPointCaretNext,
  $updateRangeSelectionFromCaretRange,
  type SplitAtPointCaretNextOptions,
} from './caret/LexicalCaretUtils';
export {
  BEFORE_INPUT_COMMAND,
  BLUR_COMMAND,
  CAN_REDO_COMMAND,
  CAN_UNDO_COMMAND,
  CLEAR_EDITOR_COMMAND,
  CLEAR_HISTORY_COMMAND,
  CLICK_COMMAND,
  COMPOSITION_END_COMMAND,
  COMPOSITION_START_COMMAND,
  CONTROLLED_TEXT_INSERTION_COMMAND,
  COPY_COMMAND,
  createCommand,
  CUT_COMMAND,
  DELETE_CHARACTER_COMMAND,
  DELETE_LINE_COMMAND,
  DELETE_WORD_COMMAND,
  DRAGEND_COMMAND,
  DRAGOVER_COMMAND,
  DRAGSTART_COMMAND,
  DROP_COMMAND,
  FOCUS_COMMAND,
  FORMAT_ELEMENT_COMMAND,
  FORMAT_TEXT_COMMAND,
  INDENT_CONTENT_COMMAND,
  INPUT_COMMAND,
  INSERT_LINE_BREAK_COMMAND,
  INSERT_PARAGRAPH_COMMAND,
  INSERT_TAB_COMMAND,
  KEY_ARROW_DOWN_COMMAND,
  KEY_ARROW_LEFT_COMMAND,
  KEY_ARROW_RIGHT_COMMAND,
  KEY_ARROW_UP_COMMAND,
  KEY_BACKSPACE_COMMAND,
  KEY_DELETE_COMMAND,
  KEY_DOWN_COMMAND,
  KEY_ENTER_COMMAND,
  KEY_ESCAPE_COMMAND,
  KEY_MODIFIER_COMMAND,
  KEY_SPACE_COMMAND,
  KEY_TAB_COMMAND,
  MOVE_TO_END,
  MOVE_TO_START,
  OUTDENT_CONTENT_COMMAND,
  PASTE_COMMAND,
  type PasteCommandType,
  REDO_COMMAND,
  REMOVE_TEXT_COMMAND,
  SELECT_ALL_COMMAND,
  SELECTION_CHANGE_COMMAND,
  SELECTION_INSERT_CLIPBOARD_NODES_COMMAND,
  SET_TEXT_FORMAT_COMMAND,
  UNDO_COMMAND,
} from './LexicalCommands';
export {
  IS_ALL_FORMATTING,
  IS_BOLD,
  IS_CODE,
  IS_HIGHLIGHT,
  IS_ITALIC,
  IS_STRIKETHROUGH,
  IS_SUBSCRIPT,
  IS_SUPERSCRIPT,
  IS_UNDERLINE,
  NODE_STATE_KEY,
  TEXT_TYPE_TO_FORMAT,
} from './LexicalConstants';
export type {DOMSlot} from './LexicalDOMSlot';
export type {ElementDOMSlot} from './LexicalDOMSlot';
export type {
  CommandListener,
  CommandListenerPriority,
  CommandListenerPriorityBefore,
  CommandPayloadType,
  CreateEditorArgs,
  DOMSlotForNode,
  EditableListener,
  EditorConfig,
  EditorDOMRenderConfig,
  EditorReadMode,
  EditorSetOptions,
  EditorThemeClasses,
  EditorThemeClassName,
  EditorUpdateOptions,
  HTMLConfig,
  Klass,
  KlassConstructor,
  LexicalCommand,
  LexicalEditor,
  LexicalNodeConfig,
  LexicalNodeReplacement,
  MutationListener,
  NodeMutation,
  RootListener,
  SerializedEditor,
  Spread,
  Transform,
  UpdateListener,
  UpdateListenerPayload,
} from './LexicalEditor';
export {
  COMMAND_PRIORITY_BEFORE_CRITICAL,
  COMMAND_PRIORITY_BEFORE_EDITOR,
  COMMAND_PRIORITY_BEFORE_HIGH,
  COMMAND_PRIORITY_BEFORE_LOW,
  COMMAND_PRIORITY_BEFORE_NORMAL,
  COMMAND_PRIORITY_CRITICAL,
  COMMAND_PRIORITY_EDITOR,
  COMMAND_PRIORITY_HIGH,
  COMMAND_PRIORITY_LOW,
  COMMAND_PRIORITY_NORMAL,
  createEditor,
  DEFAULT_EDITOR_DOM_CONFIG,
  getTransformSetFromKlass,
} from './LexicalEditor';
export type {
  EditorState,
  EditorStateReadOptions,
  SerializedEditorState,
} from './LexicalEditorState';
export {$isEditorState} from './LexicalEditorState';
export type {EventHandler} from './LexicalEvents';
export {stopLexicalPropagation} from './LexicalEvents';
export {
  CompiledKeyboardShortcuts,
  compileKeyboardShortcuts,
  CONTROL_OR_ALT,
  CONTROL_OR_META,
  type KeyboardShortcut,
  type KeyboardShortcutMatch,
  registerKeyboardShortcuts,
  type RegisterKeyboardShortcutsOptions,
} from './LexicalKeyboardShortcuts';
export type {
  AbstractStaticNodeConfigRecord,
  BaseStaticNodeConfig,
  DOMChildConversion,
  DOMConversion,
  DOMConversionFn,
  DOMConversionMap,
  DOMConversionOutput,
  DOMConversionProp,
  DOMConversionPropByTagName,
  DOMConversionTagNameMap,
  DOMExportOutput,
  DOMExportOutputMap,
  LexicalExportJSON,
  LexicalNode,
  LexicalUpdateJSON,
  NodeKey,
  NodeMap,
  SerializedLexicalNode,
  SlotChildNode,
  SlotHostNode,
  StaticNodeConfig,
  StaticNodeConfigAccessor,
  StaticNodeConfigRecord,
  StaticNodeConfigValue,
  StaticNodeTypeAccessor,
} from './LexicalNode';
export {$isLexicalNode, buildImportMap} from './LexicalNode';
export {
  $getState,
  $getStateChange,
  $getWritableNodeState,
  $setState,
  type AnyStateConfig,
  createSharedNodeState,
  createState,
  NODE_STATE_DIRECT,
  NODE_STATE_LATEST,
  type NodeStateJSON,
  type NodeStateVersion,
  type StateConfig,
  type StateConfigKey,
  type StateConfigValue,
  type StateValueConfig,
  type StateValueOrUpdater,
  type ValueOrUpdater,
} from './LexicalNodeState';
export {$normalizeSelection as $normalizeSelection__EXPERIMENTAL} from './LexicalNormalization';
export type {RefCountedRegistry} from './LexicalRefCountedRegistry';
export {createRefCountedRegistry} from './LexicalRefCountedRegistry';
export type {
  BaseSelection,
  ElementPointType as ElementPoint,
  NodeSelection,
  Point,
  PointType,
  RangeSelection,
  TextPointType as TextPoint,
} from './LexicalSelection';
export {
  $createNodeSelection,
  $createPoint,
  $createRangeSelection,
  $createRangeSelectionFromDom,
  $formatText,
  $generateNodesFromRawText,
  $getCharacterOffsets,
  $getPreviousSelection,
  $getSelection,
  $getTextContent,
  $insertNodes,
  $isBlockElementNode,
  $isNodeSelection,
  $isRangeSelection,
  $setTextFormat,
  $updateDOMSelection,
  type RawTextVisitor,
  tokenizeRawText,
} from './LexicalSelection';
export type {SlotName} from './LexicalSlot';
export {
  $getSlot,
  $getSlotFrame,
  $getSlotHost,
  $getSlotNames,
  $getSlotNameWithinHost,
  $isSlotChild,
  $isSlotHost,
  $removeSlot,
  $setSlot,
  getDeclaredSlots,
} from './LexicalSlot';
export {
  $assumeActiveEditor,
  $fullReconcile,
  $parseSerializedNode,
  isCurrentlyReadOnlyMode,
} from './LexicalUpdates';
export {
  $addUpdateTag,
  $applyNodeReplacement,
  $cloneWithProperties,
  $cloneWithPropertiesEphemeral,
  $copyNode,
  $create,
  $createChildrenArray,
  $findMatchingParent,
  $getAdjacentNode,
  $getDocument,
  $getDOMSlot,
  $getDOMTextNode,
  $getEditor,
  $getEditorDOMRenderConfig,
  $getNearestNodeFromDOMNode,
  $getNearestRootOrShadowRoot,
  $getNodeByKey,
  $getNodeByKeyOrThrow,
  $getNodeFromDOMNode,
  $getRoot,
  $hasAncestor,
  $hasUpdateTag,
  $isElementDOMSlot,
  $isInlineElementOrDecoratorNode,
  $isLeafNode,
  $isRootOrShadowRoot,
  $isSelectionCapturedInDecoratorInput,
  $isShadowRootNode,
  $isTokenOrSegmented,
  $isTokenOrTab,
  $markSlotEditable,
  $needsBlockCursorBeside,
  $nodesOfType,
  $onUpdate,
  $removeFromParent,
  $selectAll,
  $setCompositionKey,
  $setDirectionFromDOM,
  $setFormatFromDOM,
  $setSelection,
  $splitNode,
  type DOMSelectionBoundaryPoints,
  findAllLexicalElementsDeep,
  getActiveElement,
  getActiveElementDeep,
  getComposedEventTarget,
  getComposedStaticRange,
  getDOMOwnerDocument,
  getDOMSelection,
  getDOMSelectionFromTarget,
  getDOMSelectionPoints,
  getDOMSelectionRange,
  getDOMSelectionRangeAndPoints,
  getDOMShadowRoots,
  getDOMTextNode,
  getEditorPropertyFromDOMNode,
  getNearestEditorFromDOMNode,
  getParentElement,
  getRegisteredNode,
  getRegisteredNodeOrThrow,
  getRegisteredSubtypeMap,
  getRootOwnerDocument,
  getStaticNodeConfig,
  getTextDirection,
  INTERNAL_$isBlock,
  isBlockDomNode,
  isDocumentFragment,
  isDOMCapturingSelection,
  isDOMDocumentNode,
  isDOMNode,
  isDOMShadowRoot,
  isDOMTextNode,
  isDOMUnmanaged,
  isExactShortcutMatch,
  isHTMLAnchorElement,
  isHTMLElement,
  isHTMLTableCellElement,
  isHTMLTableRowElement,
  isInlineDomNode,
  isLexicalEditor,
  isModifierMatch,
  isSelectionCapturedInDecoratorInput,
  isSelectionWithinEditor,
  iterStaticNodeConfigChain,
  type KeyboardEventModifierMask,
  type KeyboardEventModifiers,
  mountSlotContainer,
  type OwnStaticNodeConfig,
  removeFromParent,
  resetRandomKey,
  setDOMUnmanaged,
  type SetDOMUnmanagedOptions,
  setNodeIndentFromDOM,
  type ShadowRootNode,
  toggleTextFormatType,
  unmountSlotContainer,
} from './LexicalUtils';
export {ArtificialNode__DO_NOT_USE} from './nodes/ArtificialNode';
export {$isDecoratorNode, DecoratorNode} from './nodes/LexicalDecoratorNode';
export type {
  ElementFormatType,
  SerializedElementNode,
} from './nodes/LexicalElementNode';
export {$isElementNode, ElementNode} from './nodes/LexicalElementNode';
export type {SerializedLineBreakNode} from './nodes/LexicalLineBreakNode';
export {
  $createLineBreakNode,
  $isLineBreakNode,
  isLastChildInBlockNode,
  isOnlyChildInBlockNode,
  LineBreakNode,
} from './nodes/LexicalLineBreakNode';
export type {SerializedParagraphNode} from './nodes/LexicalParagraphNode';
export {
  $createParagraphNode,
  $isParagraphNode,
  ParagraphNode,
} from './nodes/LexicalParagraphNode';
export type {SerializedRootNode} from './nodes/LexicalRootNode';
export {$isRootNode, RootNode} from './nodes/LexicalRootNode';
export type {SerializedTabNode} from './nodes/LexicalTabNode';
export {$createTabNode, $isTabNode, TabNode} from './nodes/LexicalTabNode';
export type {
  InlineFormattableNode,
  SerializedTextNode,
  TextFormatType,
  TextModeType,
} from './nodes/LexicalTextNode';
export {
  $createTextNode,
  $isInlineFormattable,
  $isTextNode,
  TextNode,
} from './nodes/LexicalTextNode';

// Update Tags
export {
  COLLABORATION_TAG,
  COMPOSITION_END_TAG,
  COMPOSITION_START_TAG,
  CUT_TAG,
  HISTORIC_TAG,
  HISTORY_MERGE_TAG,
  HISTORY_PUSH_TAG,
  PASTE_TAG,
  SKIP_COLLAB_TAG,
  SKIP_DOM_SELECTION_TAG,
  SKIP_SCROLL_INTO_VIEW_TAG,
  SKIP_SELECTION_FOCUS_TAG,
  type UpdateTag,
} from './LexicalUpdateTags';

// LexicalExtension
export {
  CAN_USE_BEFORE_INPUT,
  CAN_USE_DOM,
  IS_ANDROID,
  IS_ANDROID_CHROME,
  IS_APPLE,
  IS_APPLE_WEBKIT,
  IS_CHROME,
  IS_FIREFOX,
  IS_IOS,
  IS_SAFARI,
} from './environment';
export {
  type AnyLexicalExtension,
  type AnyLexicalExtensionArgument,
  type AnyNormalizedLexicalExtensionArgument,
  configExtension,
  type configTypeSymbol,
  declarePeerDependency,
  defineExtension,
  type ExtensionBuildState,
  type ExtensionConfigBase,
  type ExtensionInitState,
  type ExtensionRegisterState,
  type InitialEditorConfig,
  type InitialEditorStateType,
  type initTypeSymbol,
  type LexicalEditorWithDispose,
  type LexicalExtension,
  type LexicalExtensionArgument,
  type LexicalExtensionConfig,
  type LexicalExtensionDependency,
  type LexicalExtensionInit,
  type LexicalExtensionInternal,
  type LexicalExtensionName,
  type LexicalExtensionOutput,
  type NormalizedLexicalExtensionArgument,
  type NormalizedPeerDependency,
  type OutputComponentExtension,
  type OutputExtension,
  type outputTypeSymbol,
  safeCast,
  shallowMergeConfig,
} from './extension-core';
export {
  addClassNamesToElement,
  normalizeClassNames,
  removeClassNamesFromElement,
} from './utils/classNames';
export {mergeRegister} from './utils/mergeRegister';
export {registerEventListener} from './utils/registerEventListener';
export type {EventListenerMap} from './utils/registerEventListeners';
export {registerEventListeners} from './utils/registerEventListeners';
export {
  getStyleObjectFromCSS,
  setDOMStyleFromCSS,
  setDOMStyleObject,
} from './utils/setDOMStyle';
