/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {LexicalNode} from './LexicalNode';
import type {ParagraphNode} from './nodes/LexicalParagraphNode';
import type {TabNode} from './nodes/LexicalTabNode';
import type {TextNode} from './nodes/LexicalTextNode';

/**
 * The generated implementations for one node class.
 *
 * Each is handed to the class it was generated from through that class's
 * `$config`, so nothing has to match code to class at runtime.
 *
 * @internal
 */
export interface GeneratedJSON {
  // Method syntax, so TypeScript checks the parameter bivariantly and a
  // function generated for one class is assignable here — the same reason
  // SerializationSchema.isEqual is declared this way. The alternative is to
  // widen the parameter to 'never', which no generated function actually
  // accepts and every call site then has to cast back.
  exportJSON(node: LexicalNode): {[key: string]: unknown};
  exportCompactJSON?(node: LexicalNode): {[key: string]: unknown};
  updateFromJSON?(
    node: LexicalNode,
    json: {readonly [key: string]: unknown},
  ): void;
}

// The JSON number grammar, anchored, matching numberValue: `Number()` alone
// reads '0x10' as 16 and '' as 0, and neither is a shape a JSON encoder
// produces. Emitted from the same source the codegen verified against, so the
// two cannot be different functions.
const JSON_NUMBER = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/;

function num(v: unknown, d: number): number {
  if (typeof v === 'number') {
    return Number.isFinite(v) ? v : d;
  }
  if (typeof v !== 'string' || !JSON_NUMBER.test(v)) {
    return d;
  }
  // Matching the grammar is not enough to be in domain: '1e999' is a
  // well-formed JSON number that coerces to Infinity, and numberValue tests
  // Number.isFinite on the coerced value rather than on the input.
  const n = Number(v);
  return Number.isFinite(n) ? n : d;
}

// Null-prototype: a key the table does not have must miss rather than
// resolve to Object.prototype.
const TEXT_MODE_DECODE: {
  readonly [key: string]: 'normal' | 'segmented' | 'token';
} = /* @__PURE__ */ Object.assign(Object.create(null), {
  '0': 'normal',
  '1': 'token',
  '2': 'segmented',
});

// Null-prototype: a key the table does not have must miss rather than
// resolve to Object.prototype.
const TEXT_DETAIL_ALIAS: {readonly [key: string]: 1 | 2} =
  /* @__PURE__ */ Object.assign(Object.create(null), {
    directionless: 1,
    unmergeable: 2,
  });

// Null-prototype: a key the table does not have must miss rather than
// resolve to Object.prototype.
const TEXT_FORMAT_ALIAS: {readonly [key: string]: number} =
  /* @__PURE__ */ Object.assign(Object.create(null), {
    bold: 1,
    capitalize: 1024,
    code: 16,
    highlight: 128,
    italic: 2,
    lowercase: 256,
    strikethrough: 4,
    subscript: 32,
    superscript: 64,
    underline: 8,
    uppercase: 512,
  });

// Null-prototype: a key the table does not have must miss rather than
// resolve to Object.prototype.
const TEXT_MODE_ENCODE: {readonly [key: string]: 0 | 1 | 2} =
  /* @__PURE__ */ Object.assign(Object.create(null), {
    normal: 0,
    segmented: 2,
    token: 1,
  });

// Null-prototype: a key the table does not have must miss rather than
// resolve to Object.prototype.
const TAB_MODE_DECODE: {
  readonly [key: string]: 'normal' | 'segmented' | 'token';
} = /* @__PURE__ */ Object.assign(Object.create(null), {
  '0': 'normal',
  '1': 'token',
  '2': 'segmented',
});

/** Generated from TextNode's serialization schema. Do not edit by hand. */
function exportTextNode(node: TextNode): {[key: string]: unknown} {
  return {
    detail: node.__detail,
    format: node.__format,
    mode: TEXT_MODE_DECODE[node.__mode],
    style: node.__style,
    text: node.__text,
    type: 'text',
    version: 1,
  };
}

/** Generated from TextNode's serialization schema. Do not edit by hand. */
function exportCompactTextNode(node: TextNode): {[key: string]: unknown} {
  const json: {[key: string]: unknown} = {};
  const detail = node.__detail;
  if (detail !== undefined && detail !== 0) {
    json.detail = detail;
  }
  const format = node.__format;
  if (format !== undefined && format !== 0) {
    json.format = format;
  }
  const mode = TEXT_MODE_DECODE[node.__mode];
  if (mode !== undefined && mode !== 'normal') {
    json.mode = mode;
  }
  const style = node.__style;
  if (style !== undefined && style !== '') {
    json.style = style;
  }
  const text = node.__text;
  if (text !== undefined && text !== '') {
    json.text = text;
  }
  json.type = 'text';
  return json;
}

/** Generated from TextNode's serialization schema. Do not edit by hand. */
function updateTextNode(
  node: TextNode,
  json: {readonly [key: string]: unknown},
): void {
  let v: unknown;
  v = json.detail;
  node.__detail =
    typeof v === 'string' && v in TEXT_DETAIL_ALIAS
      ? TEXT_DETAIL_ALIAS[v]
      : num(v, 0);
  v = json.format;
  node.__format =
    typeof v === 'string' && v in TEXT_FORMAT_ALIAS
      ? TEXT_FORMAT_ALIAS[v]
      : num(v, 0);
  v = json.mode;
  v = v === 'normal' || v === 'token' || v === 'segmented' ? v : 'normal';
  node.__mode =
    (v as string) in TEXT_MODE_ENCODE ? TEXT_MODE_ENCODE[v as string] : 0;
  v = json.style;
  node.__style = typeof v === 'string' ? v : '';
  v = json.text;
  node.__text = typeof v === 'string' ? v : '';
}

/** TextNode's generated implementations, for its `$config`. @internal */
export const GENERATED_TEXT: GeneratedJSON = {
  exportJSON: exportTextNode,
  exportCompactJSON: exportCompactTextNode,
  updateFromJSON: updateTextNode,
};

/** Generated from ParagraphNode's serialization schema. Do not edit by hand. */
function exportParagraphNode(node: ParagraphNode): {[key: string]: unknown} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  return {
    children: [],
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat:
      textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
    textStyle:
      textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
    type: 'paragraph',
    version: 1,
  };
}

/** Generated from ParagraphNode's serialization schema. Do not edit by hand. */
function exportCompactParagraphNode(node: ParagraphNode): {
  [key: string]: unknown;
} {
  const textFormat = node.__textFormat;
  const textStyle = node.__textStyle;
  const shouldSerializeTextStyles =
    (textFormat !== 0 || textStyle !== '') && node.shouldSerializeTextStyles();
  const json: {[key: string]: unknown} = {children: []};
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  if (
    textFormat !== undefined &&
    textFormat !== 0 &&
    shouldSerializeTextStyles
  ) {
    json.textFormat = textFormat;
  }
  if (
    textStyle !== undefined &&
    textStyle !== '' &&
    shouldSerializeTextStyles
  ) {
    json.textStyle = textStyle;
  }
  json.type = 'paragraph';
  return json;
}

/** ParagraphNode's generated implementations, for its `$config`. @internal */
export const GENERATED_PARAGRAPH: GeneratedJSON = {
  exportJSON: exportParagraphNode,
  exportCompactJSON: exportCompactParagraphNode,
};

/** Generated from LineBreakNode's serialization schema. Do not edit by hand. */
function exportLineBreakNode(): {[key: string]: unknown} {
  return {
    type: 'linebreak',
    version: 1,
  };
}

/** Generated from LineBreakNode's serialization schema. Do not edit by hand. */
function exportCompactLineBreakNode(): {[key: string]: unknown} {
  return {type: 'linebreak'};
}

/** LineBreakNode's generated implementations, for its `$config`. @internal */
export const GENERATED_LINEBREAK: GeneratedJSON = {
  exportJSON: exportLineBreakNode,
  exportCompactJSON: exportCompactLineBreakNode,
};

/** Generated from TabNode's serialization schema. Do not edit by hand. */
function exportTabNode(node: TabNode): {[key: string]: unknown} {
  return {
    detail: node.__detail,
    mode: TAB_MODE_DECODE[node.__mode],
    text: node.__text,
    format: node.__format,
    style: node.__style,
    type: 'tab',
    version: 1,
  };
}

/** Generated from TabNode's serialization schema. Do not edit by hand. */
function exportCompactTabNode(node: TabNode): {[key: string]: unknown} {
  const json: {[key: string]: unknown} = {};
  const format = node.__format;
  if (format !== undefined && format !== 0) {
    json.format = format;
  }
  const style = node.__style;
  if (style !== undefined && style !== '') {
    json.style = style;
  }
  json.type = 'tab';
  return json;
}

/** TabNode's generated implementations, for its `$config`. @internal */
export const GENERATED_TAB: GeneratedJSON = {
  exportJSON: exportTabNode,
  exportCompactJSON: exportCompactTabNode,
};
