/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

// Type-only, so this module has no runtime imports at all. A value import of
// the node classes would be a cycle — they import LexicalNode, which imports
// this — and would evaluate a class before its base was initialized.
import type {TabNode} from './nodes/LexicalTabNode';
import type {TextNode} from './nodes/LexicalTextNode';

/** Generated from TextNode's `json` schema. Do not edit by hand. */
function exportTextNode(node: TextNode): {[key: string]: unknown} {
  const detail = node.getDetail();
  const format = node.getFormat();
  const mode = node.getMode();
  const style = node.getStyle();
  const text = node.getTextContent();
  if (
    detail !== undefined &&
    format !== undefined &&
    mode !== undefined &&
    style !== undefined &&
    text !== undefined
  ) {
    return {
      detail,
      format,
      mode,
      style,
      text,
      type: 'text',
      version: 1,
    };
  }
  const json: {[key: string]: unknown} = {};
  if (detail !== undefined) {
    json.detail = detail;
  }
  if (format !== undefined) {
    json.format = format;
  }
  if (mode !== undefined) {
    json.mode = mode;
  }
  if (style !== undefined) {
    json.style = style;
  }
  if (text !== undefined) {
    json.text = text;
  }
  json.type = 'text';
  json.version = 1;
  return json;
}

/** Generated from LineBreakNode's `json` schema. Do not edit by hand. */
function exportLineBreakNode(): {[key: string]: unknown} {
  return {
    type: 'linebreak',
    version: 1,
  };
}

/** Generated from TabNode's `json` schema. Do not edit by hand. */
function exportTabNode(node: TabNode): {[key: string]: unknown} {
  const detail = node.getDetail();
  const mode = node.getMode();
  const text = node.getTextContent();
  const format = node.getFormat();
  const style = node.getStyle();
  if (
    detail !== undefined &&
    mode !== undefined &&
    text !== undefined &&
    format !== undefined &&
    style !== undefined
  ) {
    return {
      detail,
      mode,
      text,
      format,
      style,
      type: 'tab',
      version: 1,
    };
  }
  const json: {[key: string]: unknown} = {};
  if (detail !== undefined) {
    json.detail = detail;
  }
  if (mode !== undefined) {
    json.mode = mode;
  }
  if (text !== undefined) {
    json.text = text;
  }
  if (format !== undefined) {
    json.format = format;
  }
  if (style !== undefined) {
    json.style = style;
  }
  json.type = 'tab';
  json.version = 1;
  return json;
}

type GeneratedExporter = (node: never) => {[key: string]: unknown};

const EXPORTERS = new Map<string, GeneratedExporter>([
  ['text', exportTextNode as GeneratedExporter],
  ['linebreak', exportLineBreakNode as GeneratedExporter],
  ['tab', exportTabNode as GeneratedExporter],
]);

/**
 * The generated exporter for a node type, or `undefined` for a type that has
 * none.
 *
 * Keyed by the type rather than by the class, which is both what keeps this
 * module free of runtime imports and what makes the lookup exact: a subclass
 * registers under its own type, so it never reaches its parent's exporter —
 * which would write the parent's type and none of the subclass's properties.
 *
 * @internal
 */
export function getGeneratedExporter(
  type: string,
): undefined | GeneratedExporter {
  return EXPORTERS.get(type);
}
