/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {AutoLinkNode, LinkNode} from './LexicalLinkNode';
import type {GeneratedJSON} from 'lexical';

/** Generated from LinkNode's `json` schema. Do not edit by hand. */
function exportLinkNode(node: LinkNode): {[key: string]: unknown} {
  return {
    children: [],
    rel: node.__rel,
    target: node.__target,
    title: node.__title,
    url: node.__url,
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat: node.getSerializedTextFormat(),
    textStyle: node.getSerializedTextStyle(),
    type: 'link',
    version: 1,
  };
}

/** Generated from LinkNode's `json` schema. Do not edit by hand. */
function exportCompactLinkNode(node: LinkNode): {[key: string]: unknown} {
  const json: {[key: string]: unknown} = {children: []};
  const rel = node.__rel;
  if (rel !== undefined && rel !== null) {
    json.rel = rel;
  }
  const target = node.__target;
  if (target !== undefined && target !== null) {
    json.target = target;
  }
  const title = node.__title;
  if (title !== undefined && title !== null) {
    json.title = title;
  }
  const url = node.__url;
  if (url !== undefined && url !== '') {
    json.url = url;
  }
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  const textFormat = node.getSerializedTextFormat();
  if (textFormat !== undefined && textFormat !== 0) {
    json.textFormat = textFormat;
  }
  const textStyle = node.getSerializedTextStyle();
  if (textStyle !== undefined && textStyle !== '') {
    json.textStyle = textStyle;
  }
  json.type = 'link';
  return json;
}

/** LinkNode's generated implementations, for its `$config`. @internal */
export const GENERATED_LINK: GeneratedJSON = {
  exportJSON: exportLinkNode,
  exportCompactJSON: exportCompactLinkNode,
};

/** Generated from AutoLinkNode's `json` schema. Do not edit by hand. */
function exportAutoLinkNode(node: AutoLinkNode): {[key: string]: unknown} {
  return {
    children: [],
    isUnlinked: node.__isUnlinked,
    rel: node.__rel,
    target: node.__target,
    title: node.__title,
    url: node.__url,
    direction: node.__dir,
    format: node.getFormatType(),
    indent: node.__indent,
    textFormat: node.getSerializedTextFormat(),
    textStyle: node.getSerializedTextStyle(),
    type: 'autolink',
    version: 1,
  };
}

/** Generated from AutoLinkNode's `json` schema. Do not edit by hand. */
function exportCompactAutoLinkNode(node: AutoLinkNode): {
  [key: string]: unknown;
} {
  const json: {[key: string]: unknown} = {children: []};
  const isUnlinked = node.__isUnlinked;
  if (isUnlinked !== undefined && isUnlinked !== false) {
    json.isUnlinked = isUnlinked;
  }
  const rel = node.__rel;
  if (rel !== undefined && rel !== null) {
    json.rel = rel;
  }
  const target = node.__target;
  if (target !== undefined && target !== null) {
    json.target = target;
  }
  const title = node.__title;
  if (title !== undefined && title !== null) {
    json.title = title;
  }
  const url = node.__url;
  if (url !== undefined && url !== '') {
    json.url = url;
  }
  const direction = node.__dir;
  if (direction !== undefined && direction !== null) {
    json.direction = direction;
  }
  const format = node.getFormatType();
  if (format !== undefined && format !== '') {
    json.format = format;
  }
  const indent = node.__indent;
  if (indent !== undefined && indent !== 0) {
    json.indent = indent;
  }
  const textFormat = node.getSerializedTextFormat();
  if (textFormat !== undefined && textFormat !== 0) {
    json.textFormat = textFormat;
  }
  const textStyle = node.getSerializedTextStyle();
  if (textStyle !== undefined && textStyle !== '') {
    json.textStyle = textStyle;
  }
  json.type = 'autolink';
  return json;
}

/** AutoLinkNode's generated implementations, for its `$config`. @internal */
export const GENERATED_AUTOLINK: GeneratedJSON = {
  exportJSON: exportAutoLinkNode,
  exportCompactJSON: exportCompactAutoLinkNode,
};
