/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// @generated by scripts/generate-node-json.mjs from each class's `json`
// schema. Run `pnpm run generate-node-json` to regenerate; do not edit.

// Keys are emitted in the order the schema-driven walk writes them, so the two
// produce byte-identical JSON. That order is the schema's, not alphabetical.
/* eslint-disable sort-keys-fix/sort-keys-fix */

import type {AutoLinkNode, LinkNode} from './LexicalLinkNode';

import {
  type GeneratedJSONFactory,
  getterTableOf,
  setterDefaultOf,
  setterTableOf,
} from 'lexical';

// The JSON number grammar, anchored, matching numberValue: `Number()` alone
// reads '0x10' as 16 and '' as 0, and neither is a shape a JSON encoder
// produces. Emitted from the same source the codegen verified against, so the
// two cannot be different functions.
const JSON_NUMBER = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/;

function num(v: unknown, d: number): number {
  if (typeof v === 'number') {
    return Number.isFinite(v) ? v : d;
  }
  if (typeof v !== 'string' || !JSON_NUMBER.test(v)) {
    return d;
  }
  const n = Number(v);
  return Number.isFinite(n) ? n : d;
}

function numC(
  v: unknown,
  d: number,
  min: number,
  max: number,
  integer: boolean,
): number {
  const n = num(v, d);
  return n >= min && n <= max && (!integer || Number.isInteger(n)) ? n : d;
}

/**
 * LinkNode's schema-declared fields, for a clone. Generated from that
 * schema; do not edit by hand.
 *
 * @internal
 */
export function afterCloneLinkNode(node: LinkNode, prevNode: LinkNode): void {
  node.__rel = prevNode.__rel;
  node.__target = prevNode.__target;
  node.__title = prevNode.__title;
  node.__url = prevNode.__url;
}

/** LinkNode's generated implementations, for its `$config`. @internal */
export const GENERATED_LINK: GeneratedJSONFactory = fields => {
  const LINK_FORMAT_GETTER = getterTableOf(fields, 'format') as {
    readonly [key: string]:
      | ''
      | 'center'
      | 'end'
      | 'justify'
      | 'left'
      | 'right'
      | 'start';
  };

  const LINK_FORMAT_SETTER = setterTableOf(fields, 'format') as {
    readonly [key: string]: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  };

  const LINK_FORMAT_SETTER_DEFAULT = setterDefaultOf(fields, 'format') as
    | 0
    | 1
    | 2
    | 3
    | 4
    | 5
    | 6;

  /** Generated from LinkNode's serialization schema. Do not edit by hand. */
  function exportLinkNode(node: LinkNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      rel: node.__rel,
      target: node.__target,
      title: node.__title,
      url: node.__url,
      direction: node.__dir,
      format: LINK_FORMAT_GETTER[node.__format],
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from LinkNode's serialization schema. Do not edit by hand. */
  function exportCompactLinkNode(node: LinkNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const rel = node.__rel;
    if (rel != null) {
      json.rel = rel;
    }
    const target = node.__target;
    if (target != null) {
      json.target = target;
    }
    const title = node.__title;
    if (title != null) {
      json.title = title;
    }
    const url = node.__url;
    if (url !== undefined && url !== '') {
      json.url = url;
    }
    const direction = node.__dir;
    if (direction != null) {
      json.direction = direction;
    }
    const format = LINK_FORMAT_GETTER[node.__format];
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from LinkNode's serialization schema. Do not edit by hand. */
  function updateLinkNode(
    node: LinkNode,
    json: {readonly [key: string]: unknown},
  ): LinkNode {
    let v: unknown;
    v = json.direction;
    node.__dir = v === null || v === 'ltr' || v === 'rtl' ? v : null;
    v = json.format;
    node.__format =
      typeof v === 'string' && v in LINK_FORMAT_SETTER
        ? LINK_FORMAT_SETTER[v]
        : LINK_FORMAT_SETTER_DEFAULT;
    v = json.indent;
    node.__indent = numC(v, 0, 0, Infinity, true);
    v = json.textFormat;
    node.__textFormat = num(v, 0);
    v = json.textStyle;
    node.__textStyle = typeof v === 'string' ? v : '';
    v = json.rel;
    node.__rel =
      v == null || (typeof v === 'string' ? v : '') === ''
        ? null
        : typeof v === 'string'
          ? v
          : '';
    v = json.target;
    node.__target =
      v == null || (typeof v === 'string' ? v : '') === ''
        ? null
        : typeof v === 'string'
          ? v
          : '';
    v = json.title;
    node.__title =
      v == null || (typeof v === 'string' ? v : '') === ''
        ? null
        : typeof v === 'string'
          ? v
          : '';
    v = json.url;
    node.__url = typeof v === 'string' ? v : '';
    return node;
  }

  return {
    exportJSON: exportLinkNode,
    exportCompactJSON: exportCompactLinkNode,
    updateFromJSON: updateLinkNode,
    afterCloneFrom: afterCloneLinkNode,
  };
};

/**
 * AutoLinkNode's schema-declared fields, for a clone. Generated from that
 * schema; do not edit by hand.
 *
 * @internal
 */
export function afterCloneAutoLinkNode(
  node: AutoLinkNode,
  prevNode: AutoLinkNode,
): void {
  node.__isUnlinked = prevNode.__isUnlinked;
}

/** AutoLinkNode's generated implementations, for its `$config`. @internal */
export const GENERATED_AUTOLINK: GeneratedJSONFactory = fields => {
  const AUTOLINK_FORMAT_GETTER = getterTableOf(fields, 'format') as {
    readonly [key: string]:
      | ''
      | 'center'
      | 'end'
      | 'justify'
      | 'left'
      | 'right'
      | 'start';
  };

  const AUTOLINK_FORMAT_SETTER = setterTableOf(fields, 'format') as {
    readonly [key: string]: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  };

  const AUTOLINK_FORMAT_SETTER_DEFAULT = setterDefaultOf(fields, 'format') as
    | 0
    | 1
    | 2
    | 3
    | 4
    | 5
    | 6;

  /** Generated from AutoLinkNode's serialization schema. Do not edit by hand. */
  function exportAutoLinkNode(node: AutoLinkNode): {[key: string]: unknown} {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    return {
      children: [],
      isUnlinked: node.__isUnlinked,
      rel: node.__rel,
      target: node.__target,
      title: node.__title,
      url: node.__url,
      direction: node.__dir,
      format: AUTOLINK_FORMAT_GETTER[node.__format],
      indent: node.__indent,
      textFormat:
        textFormat !== 0 && shouldSerializeTextStyles ? textFormat : undefined,
      textStyle:
        textStyle !== '' && shouldSerializeTextStyles ? textStyle : undefined,
      type: node.__type,
      version: 1,
    };
  }

  /** Generated from AutoLinkNode's serialization schema. Do not edit by hand. */
  function exportCompactAutoLinkNode(node: AutoLinkNode): {
    [key: string]: unknown;
  } {
    const textFormat = node.__textFormat;
    const textStyle = node.__textStyle;
    const shouldSerializeTextStyles =
      (textFormat !== 0 || textStyle !== '') &&
      node.shouldSerializeTextStyles();
    const json: {[key: string]: unknown} = {type: node.__type, children: []};
    const isUnlinked = node.__isUnlinked;
    if (isUnlinked !== undefined && isUnlinked !== false) {
      json.isUnlinked = isUnlinked;
    }
    const rel = node.__rel;
    if (rel != null) {
      json.rel = rel;
    }
    const target = node.__target;
    if (target != null) {
      json.target = target;
    }
    const title = node.__title;
    if (title != null) {
      json.title = title;
    }
    const url = node.__url;
    if (url !== undefined && url !== '') {
      json.url = url;
    }
    const direction = node.__dir;
    if (direction != null) {
      json.direction = direction;
    }
    const format = AUTOLINK_FORMAT_GETTER[node.__format];
    if (format !== undefined && format !== '') {
      json.format = format;
    }
    const indent = node.__indent;
    if (indent !== undefined && indent !== 0) {
      json.indent = indent;
    }
    if (
      textFormat !== undefined &&
      textFormat !== 0 &&
      shouldSerializeTextStyles
    ) {
      json.textFormat = textFormat;
    }
    if (
      textStyle !== undefined &&
      textStyle !== '' &&
      shouldSerializeTextStyles
    ) {
      json.textStyle = textStyle;
    }
    return json;
  }

  /** Generated from AutoLinkNode's serialization schema. Do not edit by hand. */
  function updateAutoLinkNode(
    node: AutoLinkNode,
    json: {readonly [key: string]: unknown},
  ): AutoLinkNode {
    let v: unknown;
    v = json.direction;
    node.__dir = v === null || v === 'ltr' || v === 'rtl' ? v : null;
    v = json.format;
    node.__format =
      typeof v === 'string' && v in AUTOLINK_FORMAT_SETTER
        ? AUTOLINK_FORMAT_SETTER[v]
        : AUTOLINK_FORMAT_SETTER_DEFAULT;
    v = json.indent;
    node.__indent = numC(v, 0, 0, Infinity, true);
    v = json.textFormat;
    node.__textFormat = num(v, 0);
    v = json.textStyle;
    node.__textStyle = typeof v === 'string' ? v : '';
    v = json.rel;
    node.__rel =
      v == null || (typeof v === 'string' ? v : '') === ''
        ? null
        : typeof v === 'string'
          ? v
          : '';
    v = json.target;
    node.__target =
      v == null || (typeof v === 'string' ? v : '') === ''
        ? null
        : typeof v === 'string'
          ? v
          : '';
    v = json.title;
    node.__title =
      v == null || (typeof v === 'string' ? v : '') === ''
        ? null
        : typeof v === 'string'
          ? v
          : '';
    v = json.url;
    node.__url = typeof v === 'string' ? v : '';
    v = json.isUnlinked;
    node.__isUnlinked = typeof v === 'boolean' ? v : false;
    return node;
  }

  return {
    exportJSON: exportAutoLinkNode,
    exportCompactJSON: exportCompactAutoLinkNode,
    updateFromJSON: updateAutoLinkNode,
    afterCloneFrom: afterCloneAutoLinkNode,
  };
};
