name: Setup playwright
description: Set up Playwright, depends on setup-pnpm

inputs:
  node-version:
    required: true
    description: 'Node version, e.g. 24.x'
  fail-on-cache-miss:
    required: false
    description: 'true to fail on cache miss'

runs:
  using: 'composite'
  steps:
    - name: Compute path
      id: vars
      shell: bash
      run: echo "cache_playwright_path=${{ runner.os == 'macOS' && '~/Library/Caches/ms-playwright' || runner.os == 'Windows' && 'C:\\Users\\runneradmin\\AppData\\Local\\ms-playwright' || '~/.cache/ms-playwright' }}" >> "$GITHUB_OUTPUT"
    - name: Install required ubuntu-latest packages
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install xvfb
    # setup-pnpm must be completed before this point
    - name: Restore playwright from cache
      uses: actions/cache/restore@v5
      id: playwright-cache
      with:
        path: ${{ steps.vars.outputs.cache_playwright_path }}
        key: playwright-v2-${{ inputs.node-version }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('pnpm-lock.yaml') }}
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
    - name: Install playwright
      shell: bash
      run: |
        pnpm exec playwright install
        pnpm exec playwright install --list
    - name: Save playwright to cache
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{ steps.vars.outputs.cache_playwright_path }}
        key: ${{ steps.playwright-cache.outputs.cache-primary-key }}
