name: Lexical Core Tests

on:
  workflow_call:

permissions: {}

jobs:
  integrity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run ci-check
      - run: pnpm run build
      - run: pnpm run build-www
      - run: pnpm run --filter @lexical/website build
      - run: pnpm run --filter lexical-playground build-vercel

  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run test-unit
