name: Lexical Integration Tests

on:
  workflow_call:

permissions: {}

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run test-integration
      - run: pnpm run test-eslint-integration
