name: Publish to NPM
on:
  workflow_dispatch:
    inputs:
      ignore-previously-published:
        description: Ignore 403 errors for 'You cannot publish over the previously published versions'
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/call-release.yml
    with:
      publish: true
      post-release: true
      ref: main
      channel: latest
      ignore-previously-published: ${{ inputs.ignore-previously-published }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
