name: Create New Release Branch
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version Increment'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - prerelease
          - patch
          - minor

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/call-release.yml
    with:
      increment-version: true
      increment: ${{ inputs.increment }}
      channel: ${{ inputs.increment == 'prerelease' && 'next' || 'latest' }}
